// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as path from 'path'

import { ItemCategoryTable } from './tables/ItemCategory'
import { ItemTable } from './tables/Item'

/** Tables */
export class Tables {
    /** Peroperty for table ItemCategory */
    public get itemCategory(): ItemCategoryTable { return this._itemCategory }
    private _itemCategory: ItemCategoryTable = new ItemCategoryTable()

    /** Peroperty for table Item */
    public get item(): ItemTable { return this._item }
    private _item: ItemTable = new ItemTable()

    /** Read all tables asynchronously. */
    public async readAll(basePath: string): Promise<void> {
        await this._itemCategory.read(path.join(basePath, 'ItemCategory.json'))
        await this._item.read(path.join(basePath, 'Item.json'))
    }

    /** Read all tables synchronously. */
    public readAllSync(basePath: string): void {
        this._itemCategory.readSync(path.join(basePath, 'ItemCategory.json'))
        this._item.readSync(path.join(basePath, 'Item.json'))

        this.solveCrossReferences()
    }

    private solveCrossReferences(): void {
    }
}

