// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as path from 'path'

import { ItemCategoryTable } from './tables/ItemCategory'
import { ItemTable } from './tables/Item'

/** Tables */
export class Tables {
    /** Peroperty for table ItemCategory */
    public get itemCategory(): ItemCategoryTable { return this._itemCategory }
    private _itemCategory: ItemCategoryTable = new ItemCategoryTable()

    /** Peroperty for table Item */
    public get item(): ItemTable { return this._item }
    private _item: ItemTable = new ItemTable()

    /**
     * Read all tables asynchronously.
     *
     * `fileExtension` defaults to what the JSON exporter writes. Pass a different one when the
     * data files were renamed after export.
     */
    public async readAll(basePath: string, fileExtension: string = '.json'): Promise<void> {
        await this._itemCategory.read(path.join(basePath, `ItemCategory${fileExtension}`))
        await this._item.read(path.join(basePath, `Item${fileExtension}`))
    }

    /** Read all tables synchronously. */
    public readAllSync(basePath: string, fileExtension: string = '.json'): void {
        this._itemCategory.readSync(path.join(basePath, `ItemCategory${fileExtension}`))
        this._item.readSync(path.join(basePath, `Item${fileExtension}`))

        this.solveCrossReferences()
    }

    private solveCrossReferences(): void {
    }
}
