# ------------------------------------------------------------------------------
# Generated by SheetMan. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------

require_relative '../sheetman/scb_reader'


module X
  # Generated from test/fixtures/xlsx/reserved-words/reserved-words.xlsx : Data : B2
  # Named after a C++ keyword.
  class TemplateRecord
    attr_accessor :index, :class_, :int, :delete, :operator, :namespace, :constructor, :function

    def initialize
      @index = 0
      @class_ = ''
      @int = 0
      @delete = false
      @operator = ''
      @namespace = ''
      @constructor = ''
      @function = ''
    end

  end

  # Every row of Template.
  class TemplateTable
    attr_accessor :records

    def initialize
      @records = []
      @by_index = {}
      @by_operator = {}
    end

    # The row with this Index, or nil when the table has none.
    #
    # The lookup to reach for when a missing row is an ordinary answer - an optional
    # reference, a key that came from user input.
    def find_by_index(key)
      @by_index[key]
    end

    # The row with this Index, or a raised error naming what was missing.
    #
    # For a key that has to be there - one from another table, or a constant. The name
    # says it raises, because a caller reading `get_by_index(key).name` at a
    # glance cannot otherwise tell whether the next line is a check or a rescue.
    def get_by_index_or_throw(key)
      record = @by_index[key]

      if record.nil?
        raise Sheetman::RecordNotFoundError,
              "there is no record in table `Template` that corresponds to " \
              "field `Index` value #{key.inspect}"
      end

      record
    end

    # Whether the table holds a row with this Index.
    def contains_index?(key)
      @by_index.key?(key)
    end

    # The row with this Operator, or nil when the table has none.
    #
    # The lookup to reach for when a missing row is an ordinary answer - an optional
    # reference, a key that came from user input.
    def find_by_operator(key)
      @by_operator[key]
    end

    # The row with this Operator, or a raised error naming what was missing.
    #
    # For a key that has to be there - one from another table, or a constant. The name
    # says it raises, because a caller reading `get_by_operator(key).name` at a
    # glance cannot otherwise tell whether the next line is a check or a rescue.
    def get_by_operator_or_throw(key)
      record = @by_operator[key]

      if record.nil?
        raise Sheetman::RecordNotFoundError,
              "there is no record in table `Template` that corresponds to " \
              "field `Operator` value #{key.inspect}"
      end

      record
    end

    # Whether the table holds a row with this Operator.
    def contains_operator?(key)
      @by_operator.key?(key)
    end

    # Loads the table from a .scb file written by SheetMan.
    # Column by column, matched by tag rather than position: a column this build does
    # not know is skipped by its block length, and one whose type changed incompatibly
    # fails naming the field.
    def read(filename)
      reader = Sheetman::Reader.new(Sheetman.read_all_bytes(filename))
      count, columns = Sheetman.read_table_header(reader)

      # Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
      records = Array.new(count) { TemplateRecord.new }

      columns.each do |column|
        block_end = reader.position + column.byte_length

        case column.tag
        when 1
          Sheetman.check_column(column, 'Template.Index', Sheetman::KIND_SCALAR, 1, [Sheetman::ELEMENT_I32, Sheetman::ELEMENT_VARINT])
          cursor = Sheetman::ColumnCursor.new(reader, column, count, 'Template.Index')
          records.each do |record|
            record.index = cursor.next_i32
          end
        when 2
          Sheetman.check_column(column, 'Template.Class', Sheetman::KIND_SCALAR, 1, [Sheetman::ELEMENT_STRING])
          cursor = Sheetman::ColumnCursor.new(reader, column, count, 'Template.Class')
          records.each do |record|
            record.class_ = cursor.next_string
          end
        when 3
          Sheetman.check_column(column, 'Template.Int', Sheetman::KIND_SCALAR, 1, [Sheetman::ELEMENT_I32, Sheetman::ELEMENT_VARINT])
          cursor = Sheetman::ColumnCursor.new(reader, column, count, 'Template.Int')
          records.each do |record|
            record.int = cursor.next_i32
          end
        when 4
          Sheetman.check_column(column, 'Template.Delete', Sheetman::KIND_SCALAR, 1, [Sheetman::ELEMENT_BOOL])
          records.each do |record|
            record.delete = reader.read_bool
          end
        when 5
          Sheetman.check_column(column, 'Template.Operator', Sheetman::KIND_SCALAR, 1, [Sheetman::ELEMENT_STRING])
          cursor = Sheetman::ColumnCursor.new(reader, column, count, 'Template.Operator')
          records.each do |record|
            record.operator = cursor.next_string
          end
        when 6
          Sheetman.check_column(column, 'Template.Namespace', Sheetman::KIND_SCALAR, 1, [Sheetman::ELEMENT_STRING])
          cursor = Sheetman::ColumnCursor.new(reader, column, count, 'Template.Namespace')
          records.each do |record|
            record.namespace = cursor.next_string
          end
        when 7
          Sheetman.check_column(column, 'Template.Constructor', Sheetman::KIND_SCALAR, 1, [Sheetman::ELEMENT_STRING])
          cursor = Sheetman::ColumnCursor.new(reader, column, count, 'Template.Constructor')
          records.each do |record|
            record.constructor = cursor.next_string
          end
        when 8
          Sheetman.check_column(column, 'Template.Function', Sheetman::KIND_SCALAR, 1, [Sheetman::ELEMENT_STRING])
          cursor = Sheetman::ColumnCursor.new(reader, column, count, 'Template.Function')
          records.each do |record|
            record.function = cursor.next_string
          end
        else
          # A column added after this code was generated.
          reader.skip(column.byte_length)
        end

        Sheetman.check_block_end(reader, column, block_end)
      end

      by_index = records.to_h { |record| [record.index, record] }
      by_operator = records.to_h { |record| [record.operator, record] }

      # Published, now that every column read.
      @records = records
      @by_index = by_index
      @by_operator = by_operator
    end
  end
end
