// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/lite_binary_reader'

/** A type for handling rows when parsing .json. */
interface IDataRow {
    index: number
    intFromNumeric: number
    floatFromNumeric: number
    whenFromDateCell: string
    bigFromNumeric: string
}

// Generated from test/fixtures/xlsx/excel-typed\excel-typed.xlsx : Typed : B2
/** Values entered as real Excel types rather than text. */
export class ExcelTypedRecord {
    /** Default constructor */
    constructor() {
    }

    /** primary index */
    public get index(): number { return this._index }
    public _index: number

    /** numeric cell holding an integer */
    public get intFromNumeric(): number { return this._intFromNumeric }
    public _intFromNumeric: number

    /** numeric cell holding a fraction */
    public get floatFromNumeric(): number { return this._floatFromNumeric }
    public _floatFromNumeric: number

    /** genuine Excel date cell */
    public get whenFromDateCell(): string { return this._whenFromDateCell }
    public _whenFromDateCell: string

    /** numeric cell beyond double precision */
    public get bigFromNumeric(): bigint { return this._bigFromNumeric }
    public _bigFromNumeric: bigint

    /** Populate field values. */
    public populateFieldValues(dataRow: IDataRow): void {
        this._index = dataRow.index
        this._intFromNumeric = dataRow.intFromNumeric
        this._floatFromNumeric = Math.fround(dataRow.floatFromNumeric)
        this._whenFromDateCell = dataRow.whenFromDateCell
        this._bigFromNumeric = BigInt(dataRow.bigFromNumeric)
    }

    /** Populate field values. */
    public populateFieldValuesCompact(dataRow: any[]): void {
        let offset = 0
        this._index = dataRow[offset++]
        this._intFromNumeric = dataRow[offset++]
        this._floatFromNumeric = Math.fround(dataRow[offset++])
        this._whenFromDateCell = dataRow[offset++]
        this._bigFromNumeric = BigInt(dataRow[offset++])
    }
}

// Generated from test/fixtures/xlsx/excel-typed\excel-typed.xlsx : Typed : B2
/** Values entered as real Excel types rather than text. */
export class ExcelTypedTable {
    /** Default constructor. */
    constructor() {
    }

    /** All records. */
    public get records(): ExcelTypedRecord[] { return this._records }
    private _records: ExcelTypedRecord[] = []

    // Indexing by 'index'
    public get recordsByIndex(): Map<number, ExcelTypedRecord> { return this._recordsByIndex }
    private _recordsByIndex: Map<number, ExcelTypedRecord> = new Map<number, ExcelTypedRecord>()

    /** Gets the value associated with the specified key. throw Error if not found. */
    public getByIndex(key: number): ExcelTypedRecord {
        const found = this._recordsByIndex.get(key)
        if (!found)
            throw new Error(`There is no record in table "ExcelTyped" that corresponds to field "index" value ${key}`)

        return found
    }

    /** Gets the value associated with the specified key. */
    public tryGetByIndex(key: number): ExcelTypedRecord | undefined {
        return this._recordsByIndex.get(key)
    }

    /** Determines whether the table contains the specified key. */
    public containsIndex(key: number): boolean {
        return !!this._recordsByIndex.has(key)
    }

    /** Read a table from specified file. */
    public async read(filename: string): Promise<void> {
        const json = await fs.promises.readFile(filename, "utf8")
        this.readFromJson(json)
    }

    /** Read a table from specified file synchronously. */
    public readSync(filename: string): void {
        const json = fs.readFileSync(filename, "utf8")
        this.readFromJson(json)
    }

    private readFromJson(json: string): void {
        const dataRows: any[] = JSON.parse(json)
        if (this.isCompactRowFormatted(dataRows)) {
            for (const dataRow of dataRows) {
                const record = new ExcelTypedRecord()
                record.populateFieldValuesCompact(dataRow)
                this._records.push(record)
            }
        } else {
            for (const dataRow of dataRows as IDataRow[]) {
                const record = new ExcelTypedRecord()
                record.populateFieldValues(dataRow)
                this._records.push(record)
            }
        }

        this.mapping()
    }

    private isCompactRowFormatted(rows: any[]): boolean {
        return rows.length > 0 && Array.isArray(rows[0])
    }

    /** Read a table from a binary .table file. */
    public readBinarySync(filename: string): void
    {
        this.readBinaryFrom(sheetman.readAllBytes(filename))
    }

    /**
     * Read a table from binary data already in memory.
     *
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public readBinaryFrom(data: Uint8Array): void
    {
        const reader = new sheetman.LiteBinaryReader(data)
        const { rowCount, columns } = sheetman.readTableHeader(reader)

        this._records = []
        for (let i = 0; i < rowCount; ++i)
            this._records.push(new ExcelTypedRecord())

        for (const column of columns)
        {
            const blockEnd = reader.position + column.byteLength

            switch (column.tag)
            {
                case 1:
                    sheetman.checkColumn(column, 'ExcelTyped.Index', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._index = reader.readI32As(column.element)
                    }
                    break
                case 2:
                    sheetman.checkColumn(column, 'ExcelTyped.IntFromNumeric', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._intFromNumeric = reader.readI32As(column.element)
                    }
                    break
                case 3:
                    sheetman.checkColumn(column, 'ExcelTyped.FloatFromNumeric', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_F32])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._floatFromNumeric = reader.readFloat()
                    }
                    break
                case 4:
                    sheetman.checkColumn(column, 'ExcelTyped.WhenFromDateCell', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I64])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._whenFromDateCell = reader.readDateTime()
                    }
                    break
                case 5:
                    sheetman.checkColumn(column, 'ExcelTyped.BigFromNumeric', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I64, sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._bigFromNumeric = reader.readI64As(column.element)
                    }
                    break
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byteLength)
                    break
            }

            sheetman.checkBlockEnd(reader, column, blockEnd)
        }

        this.mapping()
    }

    /** Index mapping. */
    private mapping(): void {
        for (const record of this._records)
        {
            this._recordsByIndex.set(record.index, record)
        }
    }
}
