// ------------------------------------------------------------------------------
// Generated by SheetMan. DO NOT EDIT.
//
// SheetMan's binary reader, emitted alongside the generated accessor so the output
// needs nothing installed to import.
// ------------------------------------------------------------------------------
//
// Reads the .table files SheetMan's binary exporter writes:
//
//   fixed8      one byte
//   fixed32     four bytes, little endian
//   fixed64     eight bytes, little endian
//   varint32    seven bits per byte, high bit set while more bytes follow,
//               at most five bytes
//   counter32   zig-zag encoded int32 written as a varint32
//   string      counter32 byte length, then that many UTF-8 bytes
//
// One of several readers of one format the exporter defines. The conformance corpus is
// what keeps them agreeing.
//
// Dart's int is 64 bits on the VM and a double on the web, where it carries 53. Anything
// wider than that is read as a BigInt here rather than an int, which is the same call the
// TypeScript reader makes and for the same reason: a value past 2^53 does not fail on the
// web, it comes back changed. That covers int64 and both tick counts, which reach 3.1e18.
//
// Dart has no single-precision float either, so a float32 read widens to a double holding
// the stored value.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

/// Stamped at the head of every table file by the exporter.
const int formatVersion = 100;

/// A table file is truncated, malformed, or not a table file.
class LiteBinaryException implements Exception {
  LiteBinaryException(this.message);

  final String message;

  @override
  String toString() => 'LiteBinaryException: $message';
}

/// A 128 bit identifier, stored in .NET Guid byte order.
///
/// That order is not plain big-endian: the first three components are little endian and
/// the trailing eight bytes are not, which is what toString has to account for.
class Uuid {
  Uuid(this.bytes);

  Uuid.empty() : bytes = Uint8List(16);

  final Uint8List bytes;

  // Component order matching .NET's Guid.ToString("D").
  static const List<int> _order = [3, 2, 1, 0, 5, 4, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15];

  @override
  String toString() {
    final out = StringBuffer();

    for (var position = 0; position < _order.length; position++) {
      if (position == 4 || position == 6 || position == 8 || position == 10) {
        out.write('-');
      }

      out.write(bytes[_order[position]].toRadixString(16).padLeft(2, '0'));
    }

    return out.toString();
  }

  @override
  bool operator ==(Object other) {
    if (other is! Uuid) return false;

    for (var i = 0; i < 16; i++) {
      if (bytes[i] != other.bytes[i]) return false;
    }

    return true;
  }

  @override
  int get hashCode => Object.hashAll(bytes);
}

/// Sequential reader over a table file's bytes.
class LiteBinaryReader {
  LiteBinaryReader(this._data)
      : _view = ByteData.view(_data.buffer, _data.offsetInBytes, _data.lengthInBytes);

  final Uint8List _data;
  final ByteData _view;

  int _position = 0;

  /// Bytes consumed so far.
  int get position => _position;

  /// Bytes left to read.
  int get remaining => _data.lengthInBytes - _position;

  int _take(int count) {
    if (remaining < count) {
      throw LiteBinaryException(
          'table data ended after $_position of ${_data.lengthInBytes} bytes '
          'while $count more were expected');
    }

    final start = _position;
    _position += count;

    return start;
  }

  int readUint8() => _data[_take(1)];

  bool readBool() => readUint8() != 0;

  int readInt32() => _view.getInt32(_take(4), Endian.little);

  int readUint32() => _view.getUint32(_take(4), Endian.little);

  /// A 64-bit integer, as a BigInt.
  ///
  /// Not an int: on the web that is a double and anything past 2^53 comes back changed
  /// rather than failing, which is the quietest way a table can be wrong.
  BigInt readInt64() {
    final at = _take(8);

    // Assembled from two 32-bit halves, because getInt64 throws on the web.
    final low = BigInt.from(_view.getUint32(at, Endian.little));
    final high = BigInt.from(_view.getInt32(at + 4, Endian.little));

    return (high << 32) | low;
  }

  /// A single-precision value, widened to a double holding the stored value.
  double readFloat() => _view.getFloat32(_take(4), Endian.little);

  double readDouble() => _view.getFloat64(_take(8), Endian.little);

  /// A length-prefixed UTF-8 string.
  String readString() {
    final length = readCounter32();

    if (length < 0) throw LiteBinaryException('string length is negative');
    if (length == 0) return '';

    final at = _take(length);
    return utf8.decode(Uint8List.sublistView(_data, at, at + length));
  }

  /// A timestamp as .NET ticks: 100 ns units since 0001-01-01.
  ///
  /// A BigInt, for the same reason as int64: the values reach 3.1e18, which the web's
  /// int cannot hold. DateTime would not do either - it keeps microseconds where a tick
  /// is a hundred nanoseconds.
  BigInt readDateTimeTicks() => readInt64();

  /// A duration as .NET ticks.
  BigInt readDurationTicks() => readInt64();

  Uuid readUuid() {
    final at = _take(16);
    return Uuid(Uint8List.fromList(_data.sublist(at, at + 16)));
  }

  /// An int32 written in as few bytes as its magnitude needed, either sign.
  int readOptimalInt32() {
    final encoded = _readVarint32();

    // Undoes the zig-zag fold by dividing rather than shifting, and negating rather than
    // xoring. Both bit operations are 32-bit on the web, and `encoded` reaches 2^32 - 1 -
    // so the idiomatic `(e >> 1) ^ -(e & 1)` is wrong there for half the range.
    final half = encoded ~/ 2;

    return encoded.isEven ? half : -half - 1;
  }

  /// A count, in the same encoding as readOptimalInt32.
  int readCounter32() => readOptimalInt32();

  /// An enum value, which travels zig-zag encoded rather than fixed width.
  int readEnum() => readOptimalInt32();

  int _readVarint32() {
    var value = 0;

    // Multiplied and added rather than shifted and ored: both of those are 32-bit on the
    // web, and the fifth byte of a varint lands past that.
    var scale = 1;

    for (var step = 0; step < 5; step++) {
      final b = readUint8();

      value += (b & 0x7F) * scale;

      if (b & 0x80 == 0) return value;

      scale *= 128;
    }

    throw LiteBinaryException('varint32 is longer than five bytes');
  }
}

/// Reads and checks a table file's header, returning the row count that follows it.
///
/// The reserved byte is written as zero and is where compression or encryption flags
/// would go; a non-zero value means the file needs handling this build does not have.
int readTableHeader(LiteBinaryReader reader) {
  final version = reader.readUint32();

  if (version != formatVersion) {
    throw LiteBinaryException(
        'table format version $version is not supported (expected $formatVersion)');
  }

  if (reader.readUint8() != 0) {
    throw LiteBinaryException('table declares unsupported features');
  }

  final count = reader.readCounter32();

  if (count < 0) throw LiteBinaryException('table row count is negative');

  return count;
}

/// Reads a whole file into memory.
Uint8List readAllBytes(String filename) => File(filename).readAsBytesSync();
