# ------------------------------------------------------------------------------
# Generated by SheetMan. DO NOT EDIT.
#
# SheetMan's binary reader, emitted alongside the generated accessor so the output
# needs nothing installed to require.
# ------------------------------------------------------------------------------
#
# Reads the .table files SheetMan's binary exporter writes:
#
#   fixed8      one byte
#   fixed32     four bytes, little endian
#   fixed64     eight bytes, little endian
#   varint32    seven bits per byte, high bit set while more bytes follow,
#               at most five bytes
#   counter32   zig-zag encoded int32 written as a varint32
#   string      counter32 byte length, then that many UTF-8 bytes
#
# One of several readers of one format the exporter defines. The conformance corpus is
# what keeps them agreeing.
#
# Ruby's Integer is arbitrary precision, so a 64-bit value needs no special handling on
# the way in. It has no single-precision float, so a float32 read widens to a Float,
# which is a double - the value is exactly the one stored, held in a wider type.

module Sheetman
  # Stamped at the head of every table file by the exporter.
  FORMAT_VERSION = 100

  # A table file is truncated, malformed, or not a table file.
  class LiteBinaryError < StandardError; end

  # A 128 bit identifier, stored in .NET Guid byte order.
  #
  # That order is not plain big-endian: the first three components are little endian and
  # the trailing eight bytes are not, which is what to_s has to account for.
  class Uuid
    # Component order matching .NET's Guid.ToString("D").
    ORDER = [3, 2, 1, 0, 5, 4, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15].freeze

    attr_reader :bytes

    def initialize(bytes = ("\0" * 16).b)
      @bytes = bytes.b
    end

    def to_s
      out = +''

      ORDER.each_with_index do |index, position|
        out << '-' if [4, 6, 8, 10].include?(position)
        out << format('%02x', @bytes.getbyte(index))
      end

      out
    end

    def ==(other)
      other.is_a?(Uuid) && other.bytes == @bytes
    end

    alias eql? ==

    def hash
      @bytes.hash
    end
  end

  # Sequential reader over a table file's bytes.
  #
  # Every read either advances the cursor or raises, so a caller need not check a return
  # value.
  class Reader
    attr_reader :position

    def initialize(data)
      @data = data.b
      @position = 0
    end

    # Bytes left to read.
    def remaining
      @data.bytesize - @position
    end

    def read_uint8
      take(1).getbyte(0)
    end

    def read_bool
      read_uint8 != 0
    end

    def read_int32
      take(4).unpack1('l<')
    end

    def read_uint32
      take(4).unpack1('L<')
    end

    def read_int64
      take(8).unpack1('q<')
    end

    # A single-precision value.
    #
    # Read as its stored bit pattern and widened to a Float, which is a double. Printing
    # it shows digits the original 32 bits never carried, which is why the conformance
    # comparison narrows before comparing.
    def read_float
      take(4).unpack1('e')
    end

    def read_double
      take(8).unpack1('E')
    end

    # A length-prefixed UTF-8 string.
    def read_string
      length = read_counter32
      raise LiteBinaryError, 'string length is negative' if length.negative?
      return '' if length.zero?

      take(length).force_encoding(Encoding::UTF_8)
    end

    # A timestamp as .NET ticks: 100 ns units since 0001-01-01.
    #
    # Ticks rather than a Time: a tick is finer than what Time keeps, and the corpus
    # reaches both 0001-01-01 and 9999-12-31.
    def read_datetime_ticks
      read_int64
    end

    # A duration as .NET ticks.
    def read_duration_ticks
      read_int64
    end

    def read_uuid
      Uuid.new(take(16))
    end

    # An int32 written in as few bytes as its magnitude needed, either sign.
    def read_optimal_int32
      encoded = read_varint32

      # Undoes the zig-zag fold: the low bit carried the sign.
      (encoded >> 1) ^ -(encoded & 1)
    end

    # A count, in the same encoding as read_optimal_int32.
    def read_counter32
      read_optimal_int32
    end

    # An enum value, which travels zig-zag encoded rather than fixed width.
    def read_enum
      read_optimal_int32
    end

    private

    def take(count)
      if remaining < count
        raise LiteBinaryError,
              "table data ended after #{@position} of #{@data.bytesize} bytes " \
              "while #{count} more were expected"
      end

      slice = @data.byteslice(@position, count)
      @position += count

      slice
    end

    def read_varint32
      value = 0

      shift = 0
      while shift < 35
        byte = read_uint8
        value |= (byte & 0x7F) << shift

        return value if (byte & 0x80).zero?

        shift += 7
      end

      raise LiteBinaryError, 'varint32 is longer than five bytes'
    end
  end

  # Reads and checks a table file's header, returning the row count that follows it.
  #
  # The reserved byte is written as zero and is where compression or encryption flags
  # would go; a non-zero value means the file needs handling this build does not have.
  def self.read_table_header(reader)
    version = reader.read_uint32

    unless version == FORMAT_VERSION
      raise LiteBinaryError,
            "table format version #{version} is not supported (expected #{FORMAT_VERSION})"
    end

    raise LiteBinaryError, 'table declares unsupported features' unless reader.read_uint8.zero?

    count = reader.read_counter32
    raise LiteBinaryError, 'table row count is negative' if count.negative?

    count
  end

  # Reads a whole file into memory.
  def self.read_all_bytes(filename)
    File.binread(filename)
  end
end
