# ------------------------------------------------------------------------------
# Generated by SheetMan. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------

import enum
import os

from . import sheetman


class TemplateRecord:
    """Generated from test/fixtures/xlsx/reserved-words\\reserved-words.xlsx : Data : B2.

    Named after a C++ keyword.
    """

    __slots__ = ("index", "class_", "int", "delete", "operator", "namespace", "constructor", "function")

    def __init__(self):
        self.index = 0
        self.class_ = ""
        self.int = 0
        self.delete = False
        self.operator = ""
        self.namespace = ""
        self.constructor = ""
        self.function = ""

    def __repr__(self):
        return "TemplateRecord(index=%r, class_=%r, int=%r, delete=%r, operator=%r, namespace=%r, constructor=%r, function=%r)" % (self.index, self.class_, self.int, self.delete, self.operator, self.namespace, self.constructor, self.function)


class TemplateTable:
    """Every row of Template."""

    __slots__ = ("records", "by_index", "by_operator")

    def __init__(self):
        self.records = []
        self.by_index = {}
        self.by_operator = {}

    def find_by_index(self, key):
        """The row with this Index, or None when the table has none.

        The lookup to reach for when a missing row is an ordinary answer - an optional
        reference, a key that came from user input.
        """
        return self.by_index.get(key)

    def get_by_index_or_throw(self, key):
        """The row with this Index, or a raised error naming what was missing.

        For a key that has to be there - one from another table, or a constant. The name
        says it raises, because a caller reading `get_by_index(key).name` at a
        glance cannot otherwise tell whether the next line is a check or a try.
        """
        record = self.by_index.get(key)

        if record is None:
            raise sheetman.RecordNotFoundError(
                "there is no record in table `Template` that corresponds to "
                "field `Index` value %r" % (key,))

        return record

    def contains_index(self, key):
        """Whether the table holds a row with this Index."""
        return key in self.by_index

    def find_by_operator(self, key):
        """The row with this Operator, or None when the table has none.

        The lookup to reach for when a missing row is an ordinary answer - an optional
        reference, a key that came from user input.
        """
        return self.by_operator.get(key)

    def get_by_operator_or_throw(self, key):
        """The row with this Operator, or a raised error naming what was missing.

        For a key that has to be there - one from another table, or a constant. The name
        says it raises, because a caller reading `get_by_operator(key).name` at a
        glance cannot otherwise tell whether the next line is a check or a try.
        """
        record = self.by_operator.get(key)

        if record is None:
            raise sheetman.RecordNotFoundError(
                "there is no record in table `Template` that corresponds to "
                "field `Operator` value %r" % (key,))

        return record

    def contains_operator(self, key):
        """Whether the table holds a row with this Operator."""
        return key in self.by_operator

    def read(self, filename):
        """Loads the table from a .table file written by SheetMan.

        Column by column, matched by tag rather than position: a column this build does
        not know is skipped by its block length, and one whose type changed incompatibly
        fails naming the field.
        """
        reader = sheetman.Reader(sheetman.read_all_bytes(filename))
        count, columns = sheetman.read_table_header(reader)

        # Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        records = [TemplateRecord() for _ in range(count)]

        for column in columns:
            block_end = reader.position + column.byte_length
            if column.tag == 1:
                sheetman.check_column(column, "Template.Index", sheetman.KIND_SCALAR, 1, (sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT))
                for record in records:
                    record.index = reader.read_i32_as(column.element)
            elif column.tag == 2:
                sheetman.check_column(column, "Template.Class", sheetman.KIND_SCALAR, 1, (sheetman.ELEMENT_STRING,))
                for record in records:
                    record.class_ = reader.read_string()
            elif column.tag == 3:
                sheetman.check_column(column, "Template.Int", sheetman.KIND_SCALAR, 1, (sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT))
                for record in records:
                    record.int = reader.read_i32_as(column.element)
            elif column.tag == 4:
                sheetman.check_column(column, "Template.Delete", sheetman.KIND_SCALAR, 1, (sheetman.ELEMENT_BOOL,))
                for record in records:
                    record.delete = reader.read_bool()
            elif column.tag == 5:
                sheetman.check_column(column, "Template.Operator", sheetman.KIND_SCALAR, 1, (sheetman.ELEMENT_STRING,))
                for record in records:
                    record.operator = reader.read_string()
            elif column.tag == 6:
                sheetman.check_column(column, "Template.Namespace", sheetman.KIND_SCALAR, 1, (sheetman.ELEMENT_STRING,))
                for record in records:
                    record.namespace = reader.read_string()
            elif column.tag == 7:
                sheetman.check_column(column, "Template.Constructor", sheetman.KIND_SCALAR, 1, (sheetman.ELEMENT_STRING,))
                for record in records:
                    record.constructor = reader.read_string()
            elif column.tag == 8:
                sheetman.check_column(column, "Template.Function", sheetman.KIND_SCALAR, 1, (sheetman.ELEMENT_STRING,))
                for record in records:
                    record.function = reader.read_string()
            else:
                # A column added after this code was generated.
                reader.skip(column.byte_length)

            sheetman.check_block_end(reader, column, block_end)

        by_index = {record.index: record for record in records}
        by_operator = {record.operator: record for record in records}

        # Published, now that every column read.
        self.records = records
        self.by_index = by_index
        self.by_operator = by_operator
