// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef SHEETMAN_GENERATED_COREACCESSOR_LOCALIZATION_H
#define SHEETMAN_GENERATED_COREACCESSOR_LOCALIZATION_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "sheetman/lite_binary_reader.h"
#include "CoreAccessor_forward.h"

namespace sheetman_fixtures {
namespace core {

// Generated from test/fixtures/xlsx/core\core.xlsx : Serial : B2
/// Trailing-number columns collapse into arrays.
struct LocalizationRecord
{
    /// primary index
    std::int32_t index = 0;
    /// lookup key
    std::string key;
    /// english text 1
    std::vector<std::string> text_en_array;
    /// korean text 1
    std::vector<std::string> text_ko_array;

};

/// Trailing-number columns collapse into arrays.
class LocalizationTable
{
    public:
    const std::vector<LocalizationRecord>& records() const { return records_; }

    /// Record with the given primary index, or nullptr when there is none.
    const LocalizationRecord* find(std::int32_t index) const
    {
        const auto it = by_index_.find(index);
        return it == by_index_.end() ? nullptr : &records_[it->second];
    }

    /// Loads the table from a .table file written by SheetMan.
    void read(const std::string& filename)
    {
        const std::vector<std::uint8_t> buffer = sheetman::read_all_bytes(filename);
        sheetman::LiteBinaryReader reader(buffer);

        // Column by column, matched by tag rather than position: a column this build
        // does not know is skipped by its block length, and one whose type changed
        // incompatibly fails naming the field.
        const sheetman::Header header = sheetman::read_table_header(reader);
        const std::size_t row_count = static_cast<std::size_t>(header.row_count);

        records_.clear();
        records_.resize(row_count);

        for (const sheetman::Column& column : header.columns)
        {
            const std::size_t block_end = reader.position() + static_cast<std::size_t>(column.byte_length);

            switch (column.tag)
            {
                case 1:
                {
                    sheetman::check_column(column, "Localization.Index", sheetman::kKindScalar, 1, {sheetman::kElementI32, sheetman::kElementVarint});
                    for (std::size_t i = 0; i < row_count; ++i)
                    {
                        auto& record = records_[i];
                        reader.read_i32_as(column.element, record.index);
                    }
                    break;
                }
                case 2:
                {
                    sheetman::check_column(column, "Localization.Key", sheetman::kKindScalar, 1, {sheetman::kElementString});
                    for (std::size_t i = 0; i < row_count; ++i)
                    {
                        auto& record = records_[i];
                        reader.read(record.key);
                    }
                    break;
                }
                case 3:
                {
                    sheetman::check_column(column, "Localization.TextEn_array", sheetman::kKindFixedArray, 2, {sheetman::kElementString});
                    for (std::size_t i = 0; i < row_count; ++i)
                    {
                        auto& record = records_[i];
                        record.text_en_array.resize(2);
                        for (std::size_t j = 0; j < 2; ++j)
                        {
                            reader.read(record.text_en_array[j]);
                        }
                    }
                    break;
                }
                case 4:
                {
                    sheetman::check_column(column, "Localization.TextKo_array", sheetman::kKindFixedArray, 2, {sheetman::kElementString});
                    for (std::size_t i = 0; i < row_count; ++i)
                    {
                        auto& record = records_[i];
                        record.text_ko_array.resize(2);
                        for (std::size_t j = 0; j < 2; ++j)
                        {
                            reader.read(record.text_ko_array[j]);
                        }
                    }
                    break;
                }
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byte_length);
                    break;
            }

            sheetman::check_block_end(reader, column, block_end);
        }

        build_index();
    }

    private:
    friend class Tables;

    void build_index()
    {
        by_index_.clear();
        by_index_.reserve(records_.size());
        for (std::size_t i = 0; i < records_.size(); ++i)
        {
            by_index_.emplace(records_[i].index, i);
        }
    }

    std::vector<LocalizationRecord> records_;
    std::unordered_map<std::int32_t, std::size_t> by_index_;
};

}  // namespace core
}  // namespace sheetman_fixtures

#endif  // SHEETMAN_GENERATED_COREACCESSOR_LOCALIZATION_H
