// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef SHEETMAN_GENERATED_COREACCESSOR_SERVER_TUNING_H
#define SHEETMAN_GENERATED_COREACCESSOR_SERVER_TUNING_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "sheetman/lite_binary_reader.h"
#include "CoreAccessor_forward.h"

namespace sheetman_fixtures {
namespace core {

// Generated from test/fixtures/xlsx/core\core.xlsx : Sides : B2
/// Server-only table. Must not appear in client output.
struct ServerTuningRecord
{
    /// primary index
    std::int32_t index = 0;
    /// tuning key
    std::string key;
    /// tuning amount
    std::int32_t amount = 0;

};

/// Server-only table. Must not appear in client output.
class ServerTuningTable
{
    public:
    const std::vector<ServerTuningRecord>& records() const { return records_; }

    /// Record with the given primary index, or nullptr when there is none.
    const ServerTuningRecord* find(std::int32_t index) const
    {
        const auto it = by_index_.find(index);
        return it == by_index_.end() ? nullptr : &records_[it->second];
    }

    /// Loads the table from a .table file written by SheetMan.
    void read(const std::string& filename)
    {
        const std::vector<std::uint8_t> buffer = sheetman::read_all_bytes(filename);
        sheetman::LiteBinaryReader reader(buffer);

        // Column by column, matched by tag rather than position: a column this build
        // does not know is skipped by its block length, and one whose type changed
        // incompatibly fails naming the field.
        const sheetman::Header header = sheetman::read_table_header(reader);
        const std::size_t row_count = static_cast<std::size_t>(header.row_count);

        records_.clear();
        records_.resize(row_count);

        for (const sheetman::Column& column : header.columns)
        {
            const std::size_t block_end = reader.position() + static_cast<std::size_t>(column.byte_length);

            switch (column.tag)
            {
                case 1:
                {
                    sheetman::check_column(column, "ServerTuning.Index", sheetman::kKindScalar, 1, {sheetman::kElementI32, sheetman::kElementVarint});
                    for (std::size_t i = 0; i < row_count; ++i)
                    {
                        auto& record = records_[i];
                        reader.read_i32_as(column.element, record.index);
                    }
                    break;
                }
                case 2:
                {
                    sheetman::check_column(column, "ServerTuning.Key", sheetman::kKindScalar, 1, {sheetman::kElementString});
                    for (std::size_t i = 0; i < row_count; ++i)
                    {
                        auto& record = records_[i];
                        reader.read(record.key);
                    }
                    break;
                }
                case 3:
                {
                    sheetman::check_column(column, "ServerTuning.Amount", sheetman::kKindScalar, 1, {sheetman::kElementI32, sheetman::kElementVarint});
                    for (std::size_t i = 0; i < row_count; ++i)
                    {
                        auto& record = records_[i];
                        reader.read_i32_as(column.element, record.amount);
                    }
                    break;
                }
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byte_length);
                    break;
            }

            sheetman::check_block_end(reader, column, block_end);
        }

        build_index();
    }

    private:
    friend class Tables;

    void build_index()
    {
        by_index_.clear();
        by_index_.reserve(records_.size());
        for (std::size_t i = 0; i < records_.size(); ++i)
        {
            by_index_.emplace(records_[i].index, i);
        }
    }

    std::vector<ServerTuningRecord> records_;
    std::unordered_map<std::int32_t, std::size_t> by_index_;
};

}  // namespace core
}  // namespace sheetman_fixtures

#endif  // SHEETMAN_GENERATED_COREACCESSOR_SERVER_TUNING_H
