// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef SHEETMAN_GENERATED_COREACCESSOR_ARRAY_TYPES_H
#define SHEETMAN_GENERATED_COREACCESSOR_ARRAY_TYPES_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "sheetman/lite_binary_reader.h"
#include "CoreAccessor_forward.h"
#include "CoreAccessor_enum_grade.h"

namespace sheetman_fixtures {
namespace core {

// Generated from test/fixtures/xlsx/core\core.xlsx : Arrays : B2
/// One cell holding several delimited values, length varying per row.
struct ArrayTypesRecord
{
    /// primary index
    std::int32_t index = 0;
    /// free-form tags
    std::vector<std::string> tags;
    /// cost per level
    std::vector<std::int32_t> costs;
    /// drop weights
    std::vector<float> weights;
    /// allowed grades
    std::vector<Grade> grades;
    /// fixed slot 1
    std::vector<std::int32_t> slot_array;

    /// Reads one record. Field order must match the exporter's.
    void read(sheetman::LiteBinaryReader& reader)
    {
        reader.read(index);
        {
            const std::int32_t count = reader.read_counter32();
            tags.resize(static_cast<std::size_t>(count));
            for (std::int32_t i = 0; i < count; ++i)
            {
                reader.read(tags[static_cast<std::size_t>(i)]);
            }
        }
        {
            const std::int32_t count = reader.read_counter32();
            costs.resize(static_cast<std::size_t>(count));
            for (std::int32_t i = 0; i < count; ++i)
            {
                reader.read(costs[static_cast<std::size_t>(i)]);
            }
        }
        {
            const std::int32_t count = reader.read_counter32();
            weights.resize(static_cast<std::size_t>(count));
            for (std::int32_t i = 0; i < count; ++i)
            {
                reader.read(weights[static_cast<std::size_t>(i)]);
            }
        }
        {
            const std::int32_t count = reader.read_counter32();
            grades.resize(static_cast<std::size_t>(count));
            for (std::int32_t i = 0; i < count; ++i)
            {
                reader.read_enum(grades[static_cast<std::size_t>(i)]);
            }
        }
        slot_array.resize(2);
        for (std::size_t i = 0; i < 2; ++i)
        {
            reader.read(slot_array[i]);
        }
    }
};

/// One cell holding several delimited values, length varying per row.
class ArrayTypesTable
{
    public:
    const std::vector<ArrayTypesRecord>& records() const { return records_; }

    /// Record with the given primary index, or nullptr when there is none.
    const ArrayTypesRecord* find(std::int32_t index) const
    {
        const auto it = by_index_.find(index);
        return it == by_index_.end() ? nullptr : &records_[it->second];
    }

    /// Loads the table from a .table file written by SheetMan.
    void read(const std::string& filename)
    {
        const std::vector<std::uint8_t> buffer = sheetman::read_all_bytes(filename);
        sheetman::LiteBinaryReader reader(buffer);

        const std::int32_t row_count = sheetman::read_table_header(reader);

        records_.clear();
        records_.resize(static_cast<std::size_t>(row_count));
        for (std::int32_t i = 0; i < row_count; ++i)
        {
            records_[static_cast<std::size_t>(i)].read(reader);
        }

        build_index();
    }

    private:
    friend class Tables;

    void build_index()
    {
        by_index_.clear();
        by_index_.reserve(records_.size());
        for (std::size_t i = 0; i < records_.size(); ++i)
        {
            by_index_.emplace(records_[i].index, i);
        }
    }

    std::vector<ArrayTypesRecord> records_;
    std::unordered_map<std::int32_t, std::size_t> by_index_;
};

}  // namespace core
}  // namespace sheetman_fixtures

#endif  // SHEETMAN_GENERATED_COREACCESSOR_ARRAY_TYPES_H
