// ------------------------------------------------------------------------------
// Generated by SheetMan. DO NOT EDIT.
//
// SheetMan's binary reader, emitted alongside the generated accessor so the output
// needs nothing installed to compile.
// ------------------------------------------------------------------------------
//
// Reads the .table files SheetMan's binary exporter writes:
//
//   fixed8      one byte
//   fixed32     four bytes, little endian
//   fixed64     eight bytes, little endian
//   varint32    seven bits per byte, high bit set while more bytes follow,
//               at most five bytes
//   counter32   zig-zag encoded int written as a varint32
//   string      counter32 byte length, then that many UTF-8 bytes
//
// One of several readers of one format the exporter defines. The conformance corpus is
// what keeps them agreeing.
//
// Java has no unsigned types, which is the thing to be careful about here. A byte is
// signed, so a byte with the high bit set is negative and has to be masked before it is
// shifted into a varint. And the zig-zag undo shifts an int that is logically unsigned,
// so it needs the unsigned shift operator rather than the arithmetic one.

package sheetman;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/** Sequential reader over a table file's bytes. */
public final class LiteBinaryReader {

    /** Stamped at the head of every table file by the exporter. */
    public static final int FORMAT_VERSION = 100;

    /** A table file is truncated, malformed, or not a table file. */
    public static final class LiteBinaryException extends RuntimeException {
        public LiteBinaryException(String message) {
            super(message);
        }
    }

    /**
     * A 128 bit identifier, stored in .NET Guid byte order.
     *
     * <p>That order is not plain big-endian: the first three components are little endian
     * and the trailing eight bytes are not, which is what toString has to account for.
     */
    public static final class Uuid {
        // Component order matching .NET's Guid.ToString("D").
        private static final int[] ORDER = {3, 2, 1, 0, 5, 4, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15};
        private static final char[] HEX = "0123456789abcdef".toCharArray();

        private final byte[] bytes;

        public Uuid(byte[] bytes) {
            this.bytes = bytes.clone();
        }

        public static Uuid empty() {
            return new Uuid(new byte[16]);
        }

        public byte[] bytes() {
            return bytes.clone();
        }

        @Override
        public String toString() {
            StringBuilder out = new StringBuilder(36);

            for (int position = 0; position < ORDER.length; position++) {
                if (position == 4 || position == 6 || position == 8 || position == 10) {
                    out.append('-');
                }

                // Masked, because a byte is signed and the high half would sign-extend.
                int value = bytes[ORDER[position]] & 0xFF;
                out.append(HEX[value >> 4]).append(HEX[value & 0x0F]);
            }

            return out.toString();
        }

        @Override
        public boolean equals(Object other) {
            return other instanceof Uuid && java.util.Arrays.equals(bytes, ((Uuid) other).bytes);
        }

        @Override
        public int hashCode() {
            return java.util.Arrays.hashCode(bytes);
        }
    }

    private final byte[] data;
    private int position;

    public LiteBinaryReader(byte[] data) {
        this.data = data;
        this.position = 0;
    }

    /** Bytes consumed so far. */
    public int position() {
        return position;
    }

    /** Bytes left to read. */
    public int remaining() {
        return data.length - position;
    }

    private int take(int count) {
        if (remaining() < count) {
            throw new LiteBinaryException(
                "table data ended after " + position + " of " + data.length
                    + " bytes while " + count + " more were expected");
        }

        int start = position;
        position += count;

        return start;
    }

    /** One byte, as an unsigned value in an int. */
    public int readUInt8() {
        return data[take(1)] & 0xFF;
    }

    public boolean readBool() {
        return readUInt8() != 0;
    }

    public int readInt32() {
        int at = take(4);

        return (data[at] & 0xFF)
            | ((data[at + 1] & 0xFF) << 8)
            | ((data[at + 2] & 0xFF) << 16)
            | ((data[at + 3] & 0xFF) << 24);
    }

    public long readInt64() {
        int at = take(8);

        long value = 0;
        for (int i = 7; i >= 0; i--) {
            value = (value << 8) | (data[at + i] & 0xFFL);
        }

        return value;
    }

    /**
     * A single-precision value as its stored bit pattern, so the value survives exactly
     * rather than through a decimal rendering.
     */
    public float readFloat() {
        return Float.intBitsToFloat(readInt32());
    }

    public double readDouble() {
        return Double.longBitsToDouble(readInt64());
    }

    /** A length-prefixed UTF-8 string. */
    public String readString() {
        int length = readCounter32();

        if (length < 0) {
            throw new LiteBinaryException("string length is negative");
        }

        if (length == 0) {
            return "";
        }

        int at = take(length);
        return new String(data, at, length, StandardCharsets.UTF_8);
    }

    /**
     * A timestamp as .NET ticks: 100 ns units since 0001-01-01.
     *
     * <p>Ticks rather than a java.time type, because a tick is finer than what Instant
     * stores in its nanosecond field only in principle - the real reason is that the
     * conversion is lossy in the other direction and a caller passing the value through
     * should not pay for it.
     */
    public long readDateTimeTicks() {
        return readInt64();
    }

    /** A duration as .NET ticks. */
    public long readDurationTicks() {
        return readInt64();
    }

    public Uuid readUuid() {
        int at = take(16);

        byte[] value = new byte[16];
        System.arraycopy(data, at, value, 0, 16);

        return new Uuid(value);
    }

    /** An int written in as few bytes as its magnitude needed, either sign. */
    public int readOptimalInt32() {
        int encoded = readVarint32();

        // Undoes the zig-zag fold: the low bit carried the sign. The shift has to be the
        // unsigned one - `encoded` is logically unsigned, and an arithmetic shift would
        // drag the sign bit down through it for any value above 2^31.
        return (encoded >>> 1) ^ -(encoded & 1);
    }

    /** A count, in the same encoding as readOptimalInt32. */
    public int readCounter32() {
        return readOptimalInt32();
    }

    /** An enum value, which travels zig-zag encoded rather than fixed width. */
    public int readEnum() {
        return readOptimalInt32();
    }

    private int readVarint32() {
        int value = 0;

        for (int shift = 0; shift < 35; shift += 7) {
            int b = readUInt8();
            value |= (b & 0x7F) << shift;

            if ((b & 0x80) == 0) {
                return value;
            }
        }

        throw new LiteBinaryException("varint32 is longer than five bytes");
    }

    /**
     * Reads and checks a table file's header, returning the row count that follows it.
     *
     * <p>The reserved byte is written as zero and is where compression or encryption flags
     * would go; a non-zero value means the file needs handling this build does not have.
     */
    public static int readTableHeader(LiteBinaryReader reader) {
        int version = reader.readInt32();

        if (version != FORMAT_VERSION) {
            throw new LiteBinaryException(
                "table format version " + Integer.toUnsignedString(version)
                    + " is not supported (expected " + FORMAT_VERSION + ")");
        }

        if (reader.readUInt8() != 0) {
            throw new LiteBinaryException("table declares unsupported features");
        }

        int count = reader.readCounter32();

        if (count < 0) {
            throw new LiteBinaryException("table row count is negative");
        }

        return count;
    }

    /** Reads a whole file into memory. */
    public static byte[] readAllBytes(Path filename) {
        try {
            return Files.readAllBytes(filename);
        } catch (IOException e) {
            throw new LiteBinaryException("could not read " + filename + ": " + e.getMessage());
        }
    }
}
