// ------------------------------------------------------------------------------
// Generated by SheetMan. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package x;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import sheetman.LiteBinaryReader;

/** Every row of Template. */
public final class TemplateTable {
    private List<TemplateRecord> records = new ArrayList<>();
    private Map<Integer, TemplateRecord> byIndex = new HashMap<>();
    private Map<String, TemplateRecord> byOperator = new HashMap<>();

    /**
     * Every row, in the order the sheet declared them.
     *
     * The list a read published, not one a read fills. A refresh replaces the reference
     * rather than the contents, so whoever holds this holds one whole load.
     */
    public List<TemplateRecord> records() {
        return records;
    }

    /**
     * The row with this Index, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public TemplateRecord findByIndex(int key) {
        return byIndex.get(key);
    }

    /**
     * The row with this Index, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByIndex(key).name() at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public TemplateRecord getByIndexOrThrow(int key) {
        TemplateRecord record = byIndex.get(key);

        if (record == null) {
            throw new LiteBinaryReader.RecordNotFoundException(
                "there is no record in table `Template` that corresponds to field "
                + "`Index` value " + key);
        }

        return record;
    }

    /** Whether the table holds a row with this Index. */
    public boolean containsIndex(int key) {
        return byIndex.containsKey(key);
    }

    /**
     * The row with this Operator, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public TemplateRecord findByOperator(String key) {
        return byOperator.get(key);
    }

    /**
     * The row with this Operator, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByOperator(key).name() at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public TemplateRecord getByOperatorOrThrow(String key) {
        TemplateRecord record = byOperator.get(key);

        if (record == null) {
            throw new LiteBinaryReader.RecordNotFoundException(
                "there is no record in table `Template` that corresponds to field "
                + "`Operator` value " + key);
        }

        return record;
    }

    /** Whether the table holds a row with this Operator. */
    public boolean containsOperator(String key) {
        return byOperator.containsKey(key);
    }

    /** Loads the table from a .table file written by SheetMan. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public void read(Path filename) {
        LiteBinaryReader reader = new LiteBinaryReader(LiteBinaryReader.readAllBytes(filename));
        LiteBinaryReader.Header header = LiteBinaryReader.readTableHeader(reader);
        int count = header.rowCount;

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        List<TemplateRecord> loaded = new ArrayList<>(count);
        Map<Integer, TemplateRecord> loadedByIndex = new HashMap<>(count * 2);
        Map<String, TemplateRecord> loadedByOperator = new HashMap<>(count * 2);

        for (int i = 0; i < count; i++) {
            loaded.add(new TemplateRecord());
        }

        for (LiteBinaryReader.Column column : header.columns) {
            int blockEnd = reader.position() + column.byteLength;

            switch (column.tag) {
                case 1: {
                    LiteBinaryReader.checkColumn(column, "Template.Index", LiteBinaryReader.KIND_SCALAR, 1, LiteBinaryReader.ELEMENT_I32, LiteBinaryReader.ELEMENT_VARINT);
                    for (TemplateRecord record : loaded) {
                        record.index = reader.readI32As(column.element);
                    }
                    break;
                }
                case 2: {
                    LiteBinaryReader.checkColumn(column, "Template.Class", LiteBinaryReader.KIND_SCALAR, 1, LiteBinaryReader.ELEMENT_STRING);
                    for (TemplateRecord record : loaded) {
                        record.class_ = reader.readString();
                    }
                    break;
                }
                case 3: {
                    LiteBinaryReader.checkColumn(column, "Template.Int", LiteBinaryReader.KIND_SCALAR, 1, LiteBinaryReader.ELEMENT_I32, LiteBinaryReader.ELEMENT_VARINT);
                    for (TemplateRecord record : loaded) {
                        record.int_ = reader.readI32As(column.element);
                    }
                    break;
                }
                case 4: {
                    LiteBinaryReader.checkColumn(column, "Template.Delete", LiteBinaryReader.KIND_SCALAR, 1, LiteBinaryReader.ELEMENT_BOOL);
                    for (TemplateRecord record : loaded) {
                        record.delete = reader.readBool();
                    }
                    break;
                }
                case 5: {
                    LiteBinaryReader.checkColumn(column, "Template.Operator", LiteBinaryReader.KIND_SCALAR, 1, LiteBinaryReader.ELEMENT_STRING);
                    for (TemplateRecord record : loaded) {
                        record.operator = reader.readString();
                    }
                    break;
                }
                case 6: {
                    LiteBinaryReader.checkColumn(column, "Template.Namespace", LiteBinaryReader.KIND_SCALAR, 1, LiteBinaryReader.ELEMENT_STRING);
                    for (TemplateRecord record : loaded) {
                        record.namespace = reader.readString();
                    }
                    break;
                }
                case 7: {
                    LiteBinaryReader.checkColumn(column, "Template.Constructor", LiteBinaryReader.KIND_SCALAR, 1, LiteBinaryReader.ELEMENT_STRING);
                    for (TemplateRecord record : loaded) {
                        record.constructor = reader.readString();
                    }
                    break;
                }
                case 8: {
                    LiteBinaryReader.checkColumn(column, "Template.Function", LiteBinaryReader.KIND_SCALAR, 1, LiteBinaryReader.ELEMENT_STRING);
                    for (TemplateRecord record : loaded) {
                        record.function = reader.readString();
                    }
                    break;
                }
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byteLength);
                    break;
            }

            LiteBinaryReader.checkBlockEnd(reader, column, blockEnd);
        }

        for (TemplateRecord record : loaded) {
            loadedByIndex.put(record.index, record);
            loadedByOperator.put(record.operator, record);
        }

        // Published, now that every column read.
        records = loaded;
        byIndex = loadedByIndex;
        byOperator = loadedByOperator;
    }
}
