// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as path from 'path'

import { ExcelTypedTable } from './tables/ExcelTyped'

/** Tables */
export class Tables {
    /** Peroperty for table ExcelTyped */
    public get excelTyped(): ExcelTypedTable { return this._excelTyped }
    private _excelTyped: ExcelTypedTable = new ExcelTypedTable()

    /** Read all tables asynchronously. */
    public async readAll(basePath: string): Promise<void> {
        await this._excelTyped.read(path.join(basePath, 'ExcelTyped.json'))
    }

    /** Read all tables synchronously. */
    public readAllSync(basePath: string): void {
        this._excelTyped.readSync(path.join(basePath, 'ExcelTyped.json'))

        this.solveCrossReferences()
    }

    private solveCrossReferences(): void {
    }
}
