// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as path from 'path'

import { ExcelTypedTable } from './tables/excel-typed'

/** Tables */
export class Tables {
  /** Peroperty for table ExcelTyped */
  public get excelTyped(): ExcelTypedTable { return this._excelTyped }
  private _excelTyped: ExcelTypedTable = new ExcelTypedTable()

  /**
   * Read all tables asynchronously.
   *
   * `fileExtension` defaults to what the JSON exporter writes. Pass a different one when the
   * data files were renamed after export.
   */
  public async readAll(basePath: string, fileExtension: string = '.json'): Promise<void> {
    const excelTyped = new ExcelTypedTable()
    await excelTyped.read(path.join(basePath, `ExcelTyped${fileExtension}`))

    this.publish(excelTyped)
  }

  /** Read all tables synchronously. */
  public readAllSync(basePath: string, fileExtension: string = '.json'): void {
    const excelTyped = new ExcelTypedTable()
    excelTyped.readSync(path.join(basePath, `ExcelTyped${fileExtension}`))

    this.publish(excelTyped)
  }

  /**
   * Read all tables from the binary export.
   *
   * The counterpart of `readAllSync`, and the one to use when the data is binary: reading a
   * table on its own with `readBinarySync` leaves its references unlinked, because linking
   * needs every table. Both formats produce the same values.
   */
  public readAllBinarySync(basePath: string, fileExtension: string = '.scb'): void {
    const excelTyped = new ExcelTypedTable()
    excelTyped.readBinarySync(path.join(basePath, `ExcelTyped${fileExtension}`))

    this.publish(excelTyped)
  }

  /**
   * Publishes one whole load.
   *
   * Reading again - a refresh, a downloaded patch - loads into tables of its own and gets
   * here only once every file has been read. A failure anywhere leaves every table holding
   * what it held, which is the answer a running program wants: the data it already had, and
   * an exception saying why the new data was not taken.
   */
  private publish(excelTyped: ExcelTypedTable): void {
    this._excelTyped = excelTyped

    this.solveCrossReferences()
  }

  /**
   * Turns the stored keys into the rows they name, once every table is in memory.
   *
   * A `foreign` column travels as the target row's primary key, so a table read on its own
   * has the key and not the row - which is why this runs from `publish` and not from a
   * table's own read. A zero means the sheet left the cell empty and is left unresolved.
   */
  private solveCrossReferences(): void {
    // No table references another.
  }
}
