// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

// SheetMan's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using SheetMan.Binary;

namespace SheetMan.Fixtures.Core.Server
{
    /// <summary>
    /// One cell holding several delimited values, length varying per row.
    /// </summary>
    [System.Serializable]
    public partial class ArrayTypesTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Fields
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;
            private int _index;

            /// <summary>
            /// free-form tags
            /// </summary>
            public string[] Tags => _tags;
            private string[] _tags = System.Array.Empty<string>();

            /// <summary>
            /// cost per level
            /// </summary>
            public int[] Costs => _costs;
            private int[] _costs = System.Array.Empty<int>();

            /// <summary>
            /// drop weights
            /// </summary>
            public float[] Weights => _weights;
            private float[] _weights = System.Array.Empty<float>();

            /// <summary>
            /// allowed grades
            /// </summary>
            public global::SheetMan.Fixtures.Core.Server.Grade[] Grades => _grades;
            private global::SheetMan.Fixtures.Core.Server.Grade[] _grades = System.Array.Empty<global::SheetMan.Fixtures.Core.Server.Grade>();

            /// <summary>
            /// fixed slot 1
            /// </summary>
            public int[] SlotArray => _slotArray;
            public const int SlotArray_N = 2;
            private int[] _slotArray = new int[SlotArray_N];
            #endregion

            #region Read record
            /// <summary>
            /// Reads a table record.
            /// </summary>
            public Task ReadAsync(LiteBinaryReader reader)
            {
                int tempEnumInt = 0;
                reader.Read(out _index);

                reader.TryReadCounter32(out int Tags_count);
                _tags = new string[Tags_count];
                for (int i = 0; i < Tags_count; ++i)
                {
                    reader.Read(out _tags[i]);
                }

                reader.TryReadCounter32(out int Costs_count);
                _costs = new int[Costs_count];
                for (int i = 0; i < Costs_count; ++i)
                {
                    reader.Read(out _costs[i]);
                }

                reader.TryReadCounter32(out int Weights_count);
                _weights = new float[Weights_count];
                for (int i = 0; i < Weights_count; ++i)
                {
                    reader.Read(out _weights[i]);
                }

                reader.TryReadCounter32(out int Grades_count);
                _grades = new global::SheetMan.Fixtures.Core.Server.Grade[Grades_count];
                for (int i = 0; i < Grades_count; ++i)
                {
                    reader.ReadOptimalInt32(out tempEnumInt);
                    _grades[i] = (global::SheetMan.Fixtures.Core.Server.Grade)tempEnumInt;
                }

                for (int i = 0; i < SlotArray_N; ++i)
                {
                    reader.Read(out _slotArray[i]);
                }

                return Task.CompletedTask;
            }
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Tags\":"); ToStringHelper.ToString(Tags, sb);
                sb.Append(",\"Costs\":"); ToStringHelper.ToString(Costs, sb);
                sb.Append(",\"Weights\":"); ToStringHelper.ToString(Weights, sb);
                sb.Append(",\"Grades\":"); ToStringHelper.ToString(Grades, sb);
                sb.Append(",\"SlotArray\":"); ToStringHelper.ToString(SlotArray, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Tags", "Costs", "Weights", "Grades", "SlotArray" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Tags, r.Costs, r.Weights, r.Grades, r.SlotArray });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        public List<Record> Records => _records;
        private readonly List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private readonly Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// Gets the value associated with the specified key. throw SheetManException if not found.
        /// </summary>
        public Record GetByIndex(int key)
        {
            if (!TryGetByIndex(key, out Record record))
                throw new SheetManException($"There is no record in table `ArrayTypes` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>
        /// Gets the value associated with the specified key.
        /// </summary>
        public bool TryGetByIndex(int key, out Record result) => _recordsByIndex.TryGetValue(key, out result);

        /// <summary>
        /// Determines whether the table contains the specified key.
        /// </summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await Tables.ReadAllBytesAsync(filename);
            var reader = new LiteBinaryReader(bytes);
            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        public async Task ReadAsync(LiteBinaryReader reader)
        {
            // Version and reserved flags are checked by the reader.
            uint version = 0;
            reader.Read(out version);

            byte flags = 0;
            reader.Read(out flags);

            int count = reader.ReadCounter32();
            for (int i = 0; i < count; i++)
            {
                var record = new Record();
                await record.ReadAsync(reader);
                _records.Add(record);
            }

            // Index mapping
            foreach (var record in _records)
                _recordsByIndex.Add(record.Index, record);
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }

} // namespace SheetMan.Fixtures.Core.Server
