// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

// SheetMan's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using SheetMan.Binary;

namespace SheetMan.Fixtures.X
{
    /// <summary>
    /// Values entered as real Excel types rather than text.
    /// </summary>
    [System.Serializable]
    public partial class ExcelTypedTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Fields
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;
            internal int _index;

            /// <summary>
            /// numeric cell holding an integer
            /// </summary>
            public int IntFromNumeric => _intFromNumeric;
            internal int _intFromNumeric;

            /// <summary>
            /// numeric cell holding a fraction
            /// </summary>
            public float FloatFromNumeric => _floatFromNumeric;
            internal float _floatFromNumeric;

            /// <summary>
            /// genuine Excel date cell
            /// </summary>
            public System.DateTime WhenFromDateCell => _whenFromDateCell;
            internal System.DateTime _whenFromDateCell;

            /// <summary>
            /// numeric cell beyond double precision
            /// </summary>
            public long BigFromNumeric => _bigFromNumeric;
            internal long _bigFromNumeric;
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"IntFromNumeric\":"); ToStringHelper.ToString(IntFromNumeric, sb);
                sb.Append(",\"FloatFromNumeric\":"); ToStringHelper.ToString(FloatFromNumeric, sb);
                sb.Append(",\"WhenFromDateCell\":"); ToStringHelper.ToString(WhenFromDateCell, sb);
                sb.Append(",\"BigFromNumeric\":"); ToStringHelper.ToString(BigFromNumeric, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "IntFromNumeric", "FloatFromNumeric", "WhenFromDateCell", "BigFromNumeric" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.IntFromNumeric, r.FloatFromNumeric, r.WhenFromDateCell, r.BigFromNumeric });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        public List<Record> Records => _records;
        private readonly List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private readonly Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// Gets the value associated with the specified key. throw SheetManException if not found.
        /// </summary>
        public Record GetByIndex(int key)
        {
            if (!TryGetByIndex(key, out Record record))
                throw new SheetManException($"There is no record in table `ExcelTyped` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>
        /// Gets the value associated with the specified key.
        /// </summary>
        public bool TryGetByIndex(int key, out Record result) => _recordsByIndex.TryGetValue(key, out result);

        /// <summary>
        /// Determines whether the table contains the specified key.
        /// </summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await Tables.ReadAllBytesAsync(filename);
            var reader = new LiteBinaryReader(bytes);
            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(LiteBinaryReader reader)
        {
            var columns = LiteBinaryTable.ReadHeader(reader, out int count);

            _records.Clear();
            for (int i = 0; i < count; i++)
                _records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        LiteBinaryTable.CheckColumn(column, "ExcelTyped.Index", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            record._index = reader.ReadI32As(column.Element);
                        }
                        break;

                    case 2:
                        LiteBinaryTable.CheckColumn(column, "ExcelTyped.IntFromNumeric", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            record._intFromNumeric = reader.ReadI32As(column.Element);
                        }
                        break;

                    case 3:
                        LiteBinaryTable.CheckColumn(column, "ExcelTyped.FloatFromNumeric", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementF32);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            reader.Read(out record._floatFromNumeric);
                        }
                        break;

                    case 4:
                        LiteBinaryTable.CheckColumn(column, "ExcelTyped.WhenFromDateCell", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementI64);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            reader.Read(out record._whenFromDateCell);
                        }
                        break;

                    case 5:
                        LiteBinaryTable.CheckColumn(column, "ExcelTyped.BigFromNumeric", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementI64, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            record._bigFromNumeric = reader.ReadI64As(column.Element);
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                LiteBinaryTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping
            foreach (var record in _records)
                _recordsByIndex.Add(record.Index, record);

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }

} // namespace SheetMan.Fixtures.X
