// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef SHEETMAN_GENERATED_COREACCESSOR_ARRAY_TYPES_H
#define SHEETMAN_GENERATED_COREACCESSOR_ARRAY_TYPES_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "sheetman/scb_reader.h"
#include "CoreAccessor_forward.h"
#include "enums/CoreAccessor_enum_grade.h"

namespace sheetman_fixtures {
namespace core {
// Generated from test/fixtures/xlsx/core/core.xlsx : Arrays : B2
/// One cell holding several delimited values, length varying per row.
struct ArrayTypesRecord {
  /// primary index
  std::int32_t index = 0;
  /// free-form tags
  std::vector<std::string> tags;
  /// cost per level
  std::vector<std::int32_t> costs;
  /// drop weights
  std::vector<float> weights;
  /// allowed grades
  std::vector<Grade> grades;
  /// fixed slot 1
  std::vector<std::int32_t> slot_array;
};

/// One cell holding several delimited values, length varying per row.
class ArrayTypesTable {
 public:
  const std::vector<ArrayTypesRecord>& records() const { return records_; }

  /// The row with this Index, or nullptr when the table has none.
  ///
  /// The lookup to reach for when a missing row is an ordinary answer - an optional
  /// reference, a key that came from user input.
  const ArrayTypesRecord* find_by_index(std::int32_t key) const {
    const auto it = by_index_.find(key);
    return it == by_index_.end() ? nullptr : &records_[it->second];
  }

  /// The row with this Index, or a thrown exception naming what was missing.
  ///
  /// For a key that has to be there - one from another table, or a constant. The name says
  /// it throws, because a caller reading `get_by_index(key)->name` at a glance
  /// cannot otherwise tell whether the next line is a null check or a catch.
  const ArrayTypesRecord& get_by_index_or_throw(std::int32_t key) const {
    const ArrayTypesRecord* found = find_by_index(key);

    if (found == nullptr) {
      throw sheetman::RecordNotFound(
        std::string("there is no record in table `ArrayTypes` that corresponds to "
                    "field `Index` value ") + std::to_string(key));
    }

    return *found;
  }

  /// Whether the table holds a row with this Index.
  bool contains_index(std::int32_t key) const {
    return by_index_.find(key) != by_index_.end();
  }

  /// Loads the table from a .scb file written by SheetMan.
  void read(const std::string& filename) {
    const std::vector<std::uint8_t> buffer = sheetman::read_all_bytes(filename);
    sheetman::ScbReader reader(buffer);

    // Column by column, matched by tag rather than position: a column this build
    // does not know is skipped by its block length, and one whose type changed
    // incompatibly fails naming the field.
    const sheetman::Header header = sheetman::read_table_header(reader);
    const std::size_t row_count = static_cast<std::size_t>(header.row_count);

    // Read into storage of its own and swapped in at the end: reading a table that is
    // already loaded is a refresh, and one that throws part way through - a truncated
    // file, a column this build cannot read - has to leave the rows already there.
    std::vector<ArrayTypesRecord> records;
    records.resize(row_count);

    for (const sheetman::Column& column : header.columns) {
      const std::size_t block_end = reader.position() + static_cast<std::size_t>(column.byte_length);

      switch (column.tag) {
        case 1: {
          sheetman::check_column(column, "ArrayTypes.Index", sheetman::kKindScalar, 1, {sheetman::kElementI32, sheetman::kElementVarint});
          sheetman::ScbColumnCursor cursor(reader, column, header.row_count, "ArrayTypes.Index");
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            record.index = cursor.next_i32();
          }
          break;
        }
        case 2: {
          sheetman::check_column(column, "ArrayTypes.Tags", sheetman::kKindVarArray, 0, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            const std::int32_t element_count = reader.read_counter32();
            record.tags.resize(static_cast<std::size_t>(element_count));
            for (std::int32_t j = 0; j < element_count; ++j) {
              reader.read(record.tags[static_cast<std::size_t>(j)]);
            }
          }
          break;
        }
        case 3: {
          sheetman::check_column(column, "ArrayTypes.Costs", sheetman::kKindVarArray, 0, {sheetman::kElementI32, sheetman::kElementVarint});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            const std::int32_t element_count = reader.read_counter32();
            record.costs.resize(static_cast<std::size_t>(element_count));
            for (std::int32_t j = 0; j < element_count; ++j) {
              reader.read_i32_as(column.element, record.costs[static_cast<std::size_t>(j)]);
            }
          }
          break;
        }
        case 4: {
          sheetman::check_column(column, "ArrayTypes.Weights", sheetman::kKindVarArray, 0, {sheetman::kElementF32});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            const std::int32_t element_count = reader.read_counter32();
            record.weights.resize(static_cast<std::size_t>(element_count));
            for (std::int32_t j = 0; j < element_count; ++j) {
              reader.read(record.weights[static_cast<std::size_t>(j)]);
            }
          }
          break;
        }
        case 5: {
          sheetman::check_column(column, "ArrayTypes.Grades", sheetman::kKindVarArray, 0, {sheetman::kElementVarint});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            const std::int32_t element_count = reader.read_counter32();
            record.grades.resize(static_cast<std::size_t>(element_count));
            for (std::int32_t j = 0; j < element_count; ++j) {
              reader.read_enum(record.grades[static_cast<std::size_t>(j)]);
            }
          }
          break;
        }
        case 6: {
          sheetman::check_column(column, "ArrayTypes.Slot_array", sheetman::kKindFixedArray, 2, {sheetman::kElementI32, sheetman::kElementVarint});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            record.slot_array.resize(2);
            for (std::size_t j = 0; j < 2; ++j) {
              reader.read_i32_as(column.element, record.slot_array[j]);
            }
          }
          break;
        }
        default:
          // A column added after this code was generated.
          reader.skip(column.byte_length);
          break;
      }

      sheetman::check_block_end(reader, column, block_end);
    }

    publish(std::move(records));
  }

 private:
  friend class Tables;

  /// One whole load, in place of the previous one.
  ///
  /// The indexes are built here rather than by the caller, because they have to arrive
  /// with the rows: a table holding this load's rows and the last one's index would
  /// answer a lookup with a row that is no longer at that position.
  void publish(std::vector<ArrayTypesRecord>&& records) {
    std::unordered_map<std::int32_t, std::size_t> index_map;
    index_map.reserve(records.size());
    for (std::size_t i = 0; i < records.size(); ++i) {
      index_map.emplace(records[i].index, i);
    }

    records_ = std::move(records);
    by_index_ = std::move(index_map);
  }

  std::vector<ArrayTypesRecord> records_;
  std::unordered_map<std::int32_t, std::size_t> by_index_;
};

}  // namespace core
}  // namespace sheetman_fixtures

#endif  // SHEETMAN_GENERATED_COREACCESSOR_ARRAY_TYPES_H
