// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

// SheetMan's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using SheetMan.Binary;

namespace X
{
    /// <summary>
    /// Named after a C++ keyword.
    /// </summary>
    [System.Serializable]
    public partial class TemplateTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Values
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;

            /// <summary>
            /// class: keyword in C++ and C#
            /// </summary>
            public string Class => _class;

            /// <summary>
            /// int: keyword in C++ and C#
            /// </summary>
            public int Int => _int;

            /// <summary>
            /// delete: keyword in C++
            /// </summary>
            public bool Delete => _delete;

            /// <summary>
            /// operator: keyword in C++
            /// </summary>
            public string Operator => _operator;

            /// <summary>
            /// namespace: keyword in C++ and C#
            /// </summary>
            public string Namespace => _namespace;

            /// <summary>
            /// constructor: special member in TypeScript
            /// </summary>
            public string Constructor => _constructor;

            /// <summary>
            /// function: keyword in TypeScript
            /// </summary>
            public string Function => _function;
            #endregion

            #region Storage
            internal int _index;
            internal string _class = "";
            internal int _int;
            internal bool _delete;
            internal string _operator = "";
            internal string _namespace = "";
            internal string _constructor = "";
            internal string _function = "";
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Class\":"); ToStringHelper.ToString(Class, sb);
                sb.Append(",\"Int\":"); ToStringHelper.ToString(Int, sb);
                sb.Append(",\"Delete\":"); ToStringHelper.ToString(Delete, sb);
                sb.Append(",\"Operator\":"); ToStringHelper.ToString(Operator, sb);
                sb.Append(",\"Namespace\":"); ToStringHelper.ToString(Namespace, sb);
                sb.Append(",\"Constructor\":"); ToStringHelper.ToString(Constructor, sb);
                sb.Append(",\"Function\":"); ToStringHelper.ToString(Function, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Class", "Int", "Delete", "Operator", "Namespace", "Constructor", "Function" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Class, r.Int, r.Delete, r.Operator, r.Namespace, r.Constructor, r.Function });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        /// <remarks>
        /// The list a read publishes, not one a read fills. Whoever holds this reference holds
        /// the rows as they were when they took it, and a refresh underneath them replaces the
        /// reference rather than the contents - so an iteration in progress neither tears nor
        /// throws, and a read that fails leaves the previous rows exactly where they were.
        /// </remarks>
        public List<Record> Records => _records;
        private List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// Gets the value associated with the specified key. throw SheetManException if not found.
        /// </summary>
        public Record GetByIndex(int key)
        {
            if (!TryGetByIndex(key, out Record record))
                throw new SheetManException($"There is no record in table `Template` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>
        /// Gets the value associated with the specified key.
        /// </summary>
        public bool TryGetByIndex(int key, out Record result) => _recordsByIndex.TryGetValue(key, out result);

        /// <summary>
        /// Determines whether the table contains the specified key.
        /// </summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await Tables.ReadAllBytesAsync(filename);
            var reader = new LiteBinaryReader(bytes);
            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(LiteBinaryReader reader)
        {
            var columns = LiteBinaryTable.ReadHeader(reader, out int count);

            // Read into storage of its own and published at the end, which is what makes a
            // refresh atomic: nothing here touches what the table is currently holding, so a
            // file that turns out to be truncated - or a column this build cannot read -
            // leaves the previous rows in place and reports why.
            //
            // Sized once. The row count was checked against what the columns declare before
            // this point, so it is a number the file could actually hold rows for - and a
            // list that grows into twenty thousand rows reallocates fifteen times to get
            // there, copying everything each time.
            var records = new List<Record>(count);

            for (int i = 0; i < count; i++)
                records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        LiteBinaryTable.CheckColumn(column, "Template.Index", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            record._index = reader.ReadI32As(column.Element);
                        }
                        break;

                    case 2:
                        LiteBinaryTable.CheckColumn(column, "Template.Class", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementString);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            reader.Read(out record._class);
                        }
                        break;

                    case 3:
                        LiteBinaryTable.CheckColumn(column, "Template.Int", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            record._int = reader.ReadI32As(column.Element);
                        }
                        break;

                    case 4:
                        LiteBinaryTable.CheckColumn(column, "Template.Delete", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementBool);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            reader.Read(out record._delete);
                        }
                        break;

                    case 5:
                        LiteBinaryTable.CheckColumn(column, "Template.Operator", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementString);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            reader.Read(out record._operator);
                        }
                        break;

                    case 6:
                        LiteBinaryTable.CheckColumn(column, "Template.Namespace", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementString);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            reader.Read(out record._namespace);
                        }
                        break;

                    case 7:
                        LiteBinaryTable.CheckColumn(column, "Template.Constructor", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementString);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            reader.Read(out record._constructor);
                        }
                        break;

                    case 8:
                        LiteBinaryTable.CheckColumn(column, "Template.Function", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementString);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            reader.Read(out record._function);
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                LiteBinaryTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping. Sized to the rows, so nothing rehashes on the way in, and a
            // duplicate key throws here - before any of this is visible.
            var recordsByIndex = new Dictionary<int, Record>(count);
            foreach (var record in records)
                recordsByIndex.Add(record.Index, record);

            // Published. Everything above succeeded, and the barrier is what keeps the writes
            // that built these from being seen after the references to them - a reader on
            // another thread gets the whole table or the previous one, never half of either.
            System.Threading.Thread.MemoryBarrier();

            _records = records;
            _recordsByIndex = recordsByIndex;

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }

} // namespace X
