// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/lite_binary_reader'

/** A type for handling rows when parsing .json. */
interface IDataRow {
    index: number
    name: string
    value: number
}

// Generated from test/fixtures/xlsx/layout-edge\layout-edge.xlsx : Offset : F9
/** Starts at F9 rather than the top-left corner. */
export class OffsetTableRecord {
    /** Default constructor */
    constructor() {
    }

    /** primary index */
    public get index(): number { return this._index }
    public _index: number

    /** name */
    public get name(): string { return this._name }
    public _name: string

    /** value */
    public get value(): number { return this._value }
    public _value: number

    /** Populate field values. */
    public populateFieldValues(dataRow: IDataRow): void {
        this._index = dataRow.index
        this._name = dataRow.name
        this._value = dataRow.value
    }

    /** Populate field values. */
    public populateFieldValuesCompact(dataRow: any[]): void {
        let offset = 0
        this._index = dataRow[offset++]
        this._name = dataRow[offset++]
        this._value = dataRow[offset++]
    }
}

// Generated from test/fixtures/xlsx/layout-edge\layout-edge.xlsx : Offset : F9
/** Starts at F9 rather than the top-left corner. */
export class OffsetTableTable {
    /** Default constructor. */
    constructor() {
    }

    /** All records. */
    public get records(): OffsetTableRecord[] { return this._records }
    private _records: OffsetTableRecord[] = []

    // Indexing by 'index'
    public get recordsByIndex(): Map<number, OffsetTableRecord> { return this._recordsByIndex }
    private _recordsByIndex: Map<number, OffsetTableRecord> = new Map<number, OffsetTableRecord>()

    /** Gets the value associated with the specified key. throw Error if not found. */
    public getByIndex(key: number): OffsetTableRecord {
        const found = this._recordsByIndex.get(key)
        if (!found)
            throw new Error(`There is no record in table "OffsetTable" that corresponds to field "index" value ${key}`)

        return found
    }

    /** Gets the value associated with the specified key. */
    public tryGetByIndex(key: number): OffsetTableRecord | undefined {
        return this._recordsByIndex.get(key)
    }

    /** Determines whether the table contains the specified key. */
    public containsIndex(key: number): boolean {
        return !!this._recordsByIndex.has(key)
    }

    /** Read a table from specified file. */
    public async read(filename: string): Promise<void> {
        const json = await fs.promises.readFile(filename, "utf8")
        this.readFromJson(json)
    }

    /** Read a table from specified file synchronously. */
    public readSync(filename: string): void {
        const json = fs.readFileSync(filename, "utf8")
        this.readFromJson(json)
    }

    private readFromJson(json: string): void {
        const dataRows: any[] = JSON.parse(json)
        if (this.isCompactRowFormatted(dataRows)) {
            for (const dataRow of dataRows) {
                const record = new OffsetTableRecord()
                record.populateFieldValuesCompact(dataRow)
                this._records.push(record)
            }
        } else {
            for (const dataRow of dataRows as IDataRow[]) {
                const record = new OffsetTableRecord()
                record.populateFieldValues(dataRow)
                this._records.push(record)
            }
        }

        this.mapping()
    }

    private isCompactRowFormatted(rows: any[]): boolean {
        return rows.length > 0 && Array.isArray(rows[0])
    }

    /** Read a table from a binary .table file. */
    public readBinarySync(filename: string): void
    {
        this.readBinaryFrom(sheetman.readAllBytes(filename))
    }

    /**
     * Read a table from binary data already in memory.
     *
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public readBinaryFrom(data: Uint8Array): void
    {
        const reader = new sheetman.LiteBinaryReader(data)
        const { rowCount, columns } = sheetman.readTableHeader(reader)

        this._records = []
        for (let i = 0; i < rowCount; ++i)
            this._records.push(new OffsetTableRecord())

        for (const column of columns)
        {
            const blockEnd = reader.position + column.byteLength

            switch (column.tag)
            {
                case 1:
                    sheetman.checkColumn(column, 'OffsetTable.Index', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._index = reader.readI32As(column.element)
                    }
                    break
                case 2:
                    sheetman.checkColumn(column, 'OffsetTable.Name', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._name = reader.readString()
                    }
                    break
                case 3:
                    sheetman.checkColumn(column, 'OffsetTable.Value', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._value = reader.readI32As(column.element)
                    }
                    break
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byteLength)
                    break
            }

            sheetman.checkBlockEnd(reader, column, blockEnd)
        }

        this.mapping()
    }

    /** Index mapping. */
    private mapping(): void {
        for (const record of this._records)
        {
            this._recordsByIndex.set(record.index, record)
        }
    }
}
