/* ------------------------------------------------------------------------------
 * Generated by SheetMan. DO NOT EDIT.
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * ------------------------------------------------------------------------------
 */

#ifndef A_FORWARD_H
#define A_FORWARD_H
typedef struct A_TemplateRecord_t A_TemplateRecord_t;

#endif /* A_FORWARD_H */
