<?php

// ------------------------------------------------------------------------------
// Generated by SheetMan. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

declare(strict_types=1);

namespace X;

require_once __DIR__ . '/sheetman/LiteBinaryReader.php';
require_once __DIR__ . '/tables/TemplateTable.php';

use SheetMan\LiteBinaryReader;
use SheetMan\RecordNotFoundException;
use SheetMan\Uuid;

/** Every table, loaded together so cross-table references can be resolved. */
final class A
{
    public TemplateTable $template;

    public function __construct()
    {
        $this->template = new TemplateTable();
    }

    /** Reads every table from $basePath, then links the references between them. */
    /**
     * Safe to call on a loaded accessor. Every file is read into a table of its own and the
     * references are linked among those, so a failure part way through leaves every table
     * holding the load it already had, and no row points at a row from it.
     */
    public function readAll(string $basePath, string $fileExtension = '.table'): void
    {
        $loadedTemplateTable = new TemplateTable();
        $loadedTemplateTable->read($basePath . \DIRECTORY_SEPARATOR . 'Template' . $fileExtension);

        $this->solveCrossReferences($loadedTemplateTable);

        $this->template = $loadedTemplateTable;
    }

    /**
     * Turns the stored indices into usable values, once every table is in memory.
     *
     * The tables arrive as arguments rather than off $this, which is how this resolves the
     * load being read rather than the one already published.
     */
    private function solveCrossReferences(TemplateTable $template): void
    {
        // No table references another.
    }
}
