using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SheetMan.Helpers;
using SheetMan.Targets;

namespace SheetMan.CodeGeneration;

/// <summary>
/// What every code-generation target does the same way.
///
/// Two methods, and both used to be copied into each generator. Neither is interesting,
/// which is the point: thirteen copies of an uninteresting method are thirteen places for
/// one of them to drift, and nothing reports it. The Unreal generator's copy of the reader
/// writer pointed at the C++ reader for months, which is how it came to ship an Unreal
/// module full of std::string.
///
/// What is genuinely per-language stays in the generator: the file layout, the type names,
/// the escaping, the reader calls. This is only the plumbing they share.
///
/// Three generators keep their own <c>CommentLines</c> because theirs is not this one, and
/// they are worth naming so nobody folds them in later on the strength of the signature:
///
///   TypeScript wraps the whole comment in `/** ... */` and runs its lines together.
///
///   Python maps each line through its own doc escaping.
///
///   C# tests <c>IsNullOrEmpty</c> rather than <c>IsNullOrWhiteSpace</c>, so a comment of
///   nothing but spaces reaches its template as one blank line instead of none.
///
/// The last of those is a difference of two words and shows up as one blank line in one
/// generated file. Which is the reason this list exists rather than a note saying the
/// methods are all the same.
/// </summary>
public abstract class CodeGenerator<TRecipe> : Target<TRecipe>
    where TRecipe : class, IOutputRecipe
{
    /// <summary>
    /// A sheet comment split into the lines a comment block needs.
    ///
    /// Line endings are normalized because a comment typed into Excel on Windows carries
    /// CRLF, and a template emitting it verbatim after a `//` leaves a stray blank line in
    /// the generated file.
    /// </summary>
    protected static IReadOnlyList<string> CommentLines(string comment)
    {
        if (string.IsNullOrWhiteSpace(comment))
            return Array.Empty<string>();

        return comment.Replace("\r\n", "\n").Split('\n');
    }

    /// <summary>
    /// Writes the language's binary reader beside the generated code.
    /// </summary>
    /// <remarks>
    /// From an embedded resource rather than from `lib/` on disk, so what a published
    /// build writes cannot differ from what is committed - and so a generated output tree
    /// is self-contained: nothing to install, no include path to set, and no chance of a
    /// consumer pairing generated code with a reader of a different vintage.
    /// </remarks>
    /// <param name="resourceName">Logical name, as SheetMan.csproj declares it.</param>
    /// <param name="path">Where to write it. Made absolute here.</param>
    protected void WriteBinaryReaderRuntime(string resourceName, string path)
    {
        using var stream = GetType().Assembly.GetManifestResourceStream(resourceName);

        if (stream is null)
            throw new SheetManException($"Embedded resource `{resourceName}` is missing from the build.");

        using var reader = new StreamReader(stream);

        StagingFiles.WriteAllTextToFile(Path.GetFullPath(path), Marked(reader.ReadToEnd(), path));
    }

    /// <summary>
    /// Puts the sweep's marker at the top of a runtime file.
    /// </summary>
    /// <remarks>
    /// Runtime files are copied out of `lib/` verbatim, and until now that meant they
    /// arrived without the `Generated by SheetMan` header every other emitted file
    /// carries. The marker is what gives the sweep permission to remove a file, so
    /// without it a runtime file this tool stopped writing stayed in the consumer's
    /// project forever - which is exactly what happened when `scb_reader.ts`
    /// was renamed to `scb-reader.ts` and both were left sitting there.
    ///
    /// Added here rather than in `lib/`, because the file in `lib/` is not generated. It
    /// is the source, it is edited and reviewed, and a header claiming otherwise would
    /// be a lie told to every person who opens it.
    /// </remarks>
    private static string Marked(string contents, string path)
    {
        // Nothing in `lib/` should already say it - those files are source, and one that
        // claimed otherwise would both lie to its readers and stack a second banner here.
        // `GeneratedFileMarkerTests` is what keeps that true.
        if (GeneratedFileMarker.HeadIsMarked(contents))
            return contents;

        string extension = Path.GetExtension(path).ToLowerInvariant();
        string comment = extension == ".py" || extension == ".rb" ? "#" : "//";

        // Two toolchains read the header rather than merely display it, so the claim is
        // spelled the way each of them recognizes:
        //
        //   Go     - gofmt, vet and the linters skip a file whose header matches
        //            `^// Code generated .* DO NOT EDIT\.$` before the package clause.
        //   C#     - Roslyn analysers and formatters skip a file opening with an
        //            `<auto-generated>` block, which is what every C# file this tool
        //            emits already carries. A runtime file without it would be the one
        //            generated file a consumer's analysers complained about.
        //
        // The sweep finds its phrase inside all three, because that match ignores case.
        string[] claim = extension switch
        {
            ".go" => ["Code generated by SheetMan. DO NOT EDIT."],
            ".cs" =>
            [
                "<auto-generated>",
                "    THIS CODE WAS GENERATED BY SheetMan. DO NOT EDIT.",
                "</auto-generated>",
            ],
            _ => [$"Written here by SheetMan. {GeneratedFileMarker.TextWithWarning}"],
        };

        var lines = new List<string>
        {
            $"{comment} ------------------------------------------------------------------------------",
        };

        lines.AddRange(claim.Select(line => $"{comment} {line}"));

        lines.AddRange(
        [
            $"{comment}",
            $"{comment} The runtime, copied in beside the generated code so the output is",
            $"{comment} self-contained. Edit it in the SheetMan repository, not here: this file is",
            $"{comment} rewritten on every run, and the header above is what lets a later run remove",
            $"{comment} it if it ever moves.",
            $"{comment} ------------------------------------------------------------------------------",
            "",
            "",
        ]);

        string banner = string.Join("\n", lines);

        // Two first lines cannot have anything put in front of them: `<?php`, because
        // PHP prints whatever precedes it, and Ruby's `frozen_string_literal`, which
        // stops being a magic comment if it is not the first one. The banner goes after
        // either, which the sweep's marker window is wide enough to still see.
        bool afterFirstLine =
            contents.StartsWith("<?php", StringComparison.Ordinal)
            || contents.StartsWith("# frozen_string_literal:", StringComparison.Ordinal);

        if (afterFirstLine)
        {
            int firstBreak = contents.IndexOf('\n');

            if (firstBreak >= 0)
            {
                return contents.Substring(0, firstBreak + 1)
                       + "\n" + banner
                       + contents.Substring(firstBreak + 1).TrimStart('\n');
            }
        }

        return banner + contents;
    }

    /// <summary>
    /// Asks for the generated files this run did not write to be removed from
    /// <paramref name="directory"/> once the run commits.
    /// </summary>
    /// <remarks>
    /// Every target that writes a file per table needs this, and a target that writes one
    /// file wants it too the day it stops: delete a table from the sheets and its file
    /// stays behind, naming types nothing declares any more.
    ///
    /// Only files carrying this tool's own header are removed, so a target pointed at a
    /// directory holding somebody's own source cannot delete any of it. Which is why this
    /// is on by default and <c>Sweep: false</c> in a recipe entry turns it off - the option
    /// exists for a consumer who edits the output, and editing generated files is a
    /// decision that deserves a line in a recipe.
    /// </remarks>
    protected static void SweepStaleOutput(string directory, bool sweep)
    {
        if (sweep && !string.IsNullOrEmpty(directory))
            StagingFiles.SweepDirectory(directory);
    }
}
