using SheetMan.Models;
using SheetMan.Extensions;
using SheetMan.Helpers;
using SheetMan.Recipe;
using SheetMan.Targets;
using Serilog;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

using ValueType = SheetMan.Models.ValueType;

namespace SheetMan.CodeGeneration
{
    /// <summary>
    /// Settings for the Python target.
    ///
    /// Declared beside its generator and reached through the recipe's `Targets` list.
    /// </summary>
    public sealed class PythonRecipe : IOutputRecipe
    {
        /// <summary>Directory the package is written into. Created if it does not exist.</summary>
        public string Path { get; set; } = "";

        /// <summary>
        /// Name of the generated package, which is also the directory it goes in and how a
        /// consumer imports it.
        /// </summary>
        public string PackageName { get; set; } = "gamedata";

        /// <summary>Module the generated types live in, inside the package.</summary>
        public string ModuleName { get; set; } = "tables";

        /// <summary>
        /// Extension of the table files the generated reader opens. Must match what the
        /// binary exporter was told to write.
        /// </summary>
        public string BinaryTableFileExtension { get; set; } = ".table";

        /// <summary>Which side this output is built for: "c", "s", or "cs"/blank for both.</summary>
        public string TargetSide { get; set; } = "cs";
    }

    /// <summary>
    /// Emits a Python package: one module holding every generated type, the binary reader
    /// beside it, and an `__init__` that re-exports them.
    ///
    /// Records use `__slots__`. A localization table is tens of thousands of rows, and a
    /// per-instance dictionary on each is the difference between tens of megabytes and a
    /// few.
    ///
    /// The shape lives in templates/python.sbn.
    /// </summary>
    [SheetManTarget("python", TargetKind.CodeGeneration, Order = 70)]
    public class PythonCodeGenerator : Target<PythonRecipe>
    {
        private Model _model;
        private PythonRecipe _recipe;

        protected override void Run(TargetContext context, PythonRecipe recipe)
        {
            if (string.IsNullOrEmpty(recipe.Path))
                return;

            _recipe = recipe;
            _model = context.Model;

            Generate();
            WriteBinaryReaderRuntime();
            WriteInit();
        }

        private string PackageDir
            => System.IO.Path.Combine(_recipe.Path, _recipe.PackageName);

        private void Generate()
        {
            string filename = System.IO.Path.GetFullPath(
                System.IO.Path.Combine(PackageDir, _recipe.ModuleName + ".py"));

            Log.Information($"Generating codes for Python into `{filename}`");

            StagingFiles.WriteAllTextToFile(filename, TemplateEngine.Render("python.sbn", BuildView()));
        }

        private void WriteBinaryReaderRuntime()
        {
            const string resourceName = "SheetMan.Runtime.Python.lite_binary_reader.py";

            using var stream = typeof(PythonCodeGenerator).Assembly.GetManifestResourceStream(resourceName);
            if (stream == null)
                throw new SheetManException($"Embedded resource `{resourceName}` is missing from the build.");

            using var reader = new StreamReader(stream);

            StagingFiles.WriteAllTextToFile(
                System.IO.Path.GetFullPath(System.IO.Path.Combine(PackageDir, "sheetman.py")),
                reader.ReadToEnd());
        }

        /// <summary>
        /// Writes the package's `__init__`, which re-exports the generated module so a
        /// consumer imports the package rather than a file inside it.
        /// </summary>
        private void WriteInit()
        {
            var text = new StringBuilder();
            text.Append("# Generated by SheetMan. DO NOT EDIT.\n");
            text.Append('\n');
            text.Append("from .").Append(_recipe.ModuleName).Append(" import *  # noqa: F401,F403\n");

            StagingFiles.WriteAllTextToFile(
                System.IO.Path.GetFullPath(System.IO.Path.Combine(PackageDir, "__init__.py")),
                text.ToString());
        }

        // --------------------------------------------------------------- view

        private PythonFileView BuildView() => new PythonFileView
        {
            Enums = _model.Enums.Select(BuildEnum).ToList(),
            ConstantSets = _model.ConstantSets.Select(BuildConstantSet).ToList(),
            Tables = _model.Tables.Select(BuildTable).ToList(),
            Accessor = BuildAccessor(),
        };

        private PythonEnumView BuildEnum(Models.Enum enumm)
        {
            var fallback = enumm.Labels.FirstOrDefault(label => label.Value == 0) ?? enumm.Labels[0];

            return new PythonEnumView
            {
                Name = enumm.Name.ToPascalCase(),
                Location = DocText(enumm.Location.ToString()),
                Comment = CommentLines(enumm.Comment),
                DefaultValue = fallback.Value.ToString(CultureInfo.InvariantCulture),
                Labels = enumm.Labels.Select(label => new PythonEnumLabelView
                {
                    Name = PythonName(label.Name),
                    Value = label.Value.ToString(CultureInfo.InvariantCulture),
                    Comment = CommentLines(label.Comment),
                }).ToList(),
            };
        }

        private PythonConstantSetView BuildConstantSet(ConstantSet constantSet) => new PythonConstantSetView
        {
            Name = constantSet.Name.ToPascalCase(),
            Location = DocText(constantSet.Location.ToString()),
            Comment = CommentLines(constantSet.Comment),
            Constants = constantSet.Constants.Select(constant => new PythonConstantView
            {
                // Python constants are SCREAMING_SNAKE_CASE by convention.
                Name = constant.Name.ToSnakeCase().ToUpperInvariant(),
                Value = RenderConstantValue(constant),
                Comment = CommentLines(constant.Comment),
            }).ToList(),
        };

        private PythonTableView BuildTable(Table table)
        {
            var fields = table.SerialFields.Select(BuildField).ToList();

            // A reference contributes its index as well as its value, and both need a slot.
            var slots = new List<string>();
            foreach (var sf in table.SerialFields)
            {
                slots.Add(PythonName(sf.Name));

                if (sf.IsRef)
                    slots.Add(PythonName(sf.Name) + "_index");
            }

            return new PythonTableView
            {
                RawName = table.Name,
                RecordName = table.Name.ToPascalCase() + "Record",
                TableName = table.Name.ToPascalCase() + "Table",
                Location = DocText(table.Location.ToString()),
                Comment = CommentLines(table.Comment),
                IndexField = PythonName(table.Fields[0].Name),
                SlotNames = Tuple(slots),
                ReprFormat = string.Join(", ", table.SerialFields.Select(sf => PythonName(sf.Name) + "=%r")),
                ReprValues = Tuple(table.SerialFields.Select(sf => "self." + PythonName(sf.Name)).ToList(),
                                   quote: false),
                Fields = fields,
            };
        }

        private PythonFieldView BuildField(SerialField sf)
        {
            string name = PythonName(sf.Name);

            return new PythonFieldView
            {
                Comment = CommentLines(sf.FirstField.Comment),
                Name = name,
                Kind = ReadKind(sf),
                ElementCount = sf.Fields.Count,
                Initializers = Initializers(sf, name),
                ReadScalar = ReadExpression(sf),
                ReadElement = ReadExpression(sf),
            };
        }

        /// <summary>
        /// The constructor's assignments, so that a record is fully formed before it is read
        /// into and a consumer never meets a half-built one.
        /// </summary>
        private IReadOnlyList<string> Initializers(SerialField sf, string name)
        {
            if (sf.IsRef)
            {
                return sf.IsArray
                    ? new[] { $"self.{name} = []", $"self.{name}_index = []" }
                    : new[] { $"self.{name} = None", $"self.{name}_index = 0" };
            }

            if (sf.IsArray)
                return new[] { $"self.{name} = []" };

            return new[] { $"self.{name} = {DefaultValue(sf)}" };
        }

        private string DefaultValue(SerialField sf)
        {
            switch (sf.ElementType)
            {
                case ValueType.String: return "\"\"";
                case ValueType.Bool: return "False";
                case ValueType.Float:
                case ValueType.Double: return "0.0";
                case ValueType.Uuid: return "sheetman.Uuid()";
                case ValueType.Enum: return $"{sf.FirstField.Enum.Name.ToPascalCase()}(0)";
                default: return "0";
            }
        }

        private static string ReadKind(SerialField sf)
        {
            if (sf.IsVariableLengthArray)
                return "var_array";

            if (sf.IsArray)
                return sf.IsRef ? "serial_ref" : "serial";

            return sf.IsRef ? "scalar_ref" : "scalar";
        }

        private PythonAccessorView BuildAccessor() => new PythonAccessorView
        {
            FileExtension = _recipe.BinaryTableFileExtension,
            SlotNames = Tuple(_model.Tables.Select(table => PythonName(table.Name)).ToList()),

            Tables = _model.Tables.Select(table => new PythonTableSlotView
            {
                Name = PythonName(table.Name),
                TableName = table.Name.ToPascalCase() + "Table",

                // Unescaped: this one names the file the exporter wrote.
                DataFileName = table.Name,
            }).ToList(),

            CrossReferences = _model.Tables
                .Select(table => new
                {
                    Table = table,
                    Fields = table.SerialFields.Where(sf => sf.IsRef).ToList(),
                })
                .Where(x => x.Fields.Count > 0)
                .Select(x => new PythonCrossReferenceView
                {
                    Table = PythonName(x.Table.Name),
                    Fields = x.Fields.Select(sf => new PythonReferenceFieldView
                    {
                        Name = PythonName(sf.Name),
                        RefTable = PythonName(sf.FirstField.ResolvedRefTable.Name),
                        Value = sf.ElementType == ValueType.ForeignRecord
                            ? "target"
                            : "target." + PythonName(sf.FirstField.ResolvedRefField.Name),
                        IsArray = sf.IsArray,
                    }).ToList(),
                })
                .ToList(),
        };

        // ----------------------------------------------------------- rendering

        private string ReadExpression(SerialField sf)
        {
            switch (sf.ElementType)
            {
                case ValueType.String: return "reader.read_string()";
                case ValueType.Bool: return "reader.read_bool()";
                case ValueType.Int32: return "reader.read_int32()";
                case ValueType.Int64: return "reader.read_int64()";
                case ValueType.Float: return "reader.read_float()";
                case ValueType.Double: return "reader.read_double()";
                case ValueType.DateTime: return "reader.read_datetime_ticks()";
                case ValueType.TimeSpan: return "reader.read_duration_ticks()";
                case ValueType.Uuid: return "reader.read_uuid()";

                // Enum values travel zig-zag encoded rather than fixed width.
                case ValueType.Enum:
                    return $"{sf.FirstField.Enum.Name.ToPascalCase()}(reader.read_enum())";

                case ValueType.ForeignRecord: return "reader.read_int32()";

                default:
                    throw new SheetManException($"The python generator cannot read type `{sf.Type}`.");
            }
        }

        private string RenderConstantValue(ConstantSet.Constant constant)
        {
            switch (constant.Type)
            {
                case ValueType.String:
                    return Quote((string)constant.Value);

                case ValueType.Bool:
                    return (bool)constant.Value ? "True" : "False";

                case ValueType.Int32:
                    return ((int)constant.Value).ToString(CultureInfo.InvariantCulture);

                case ValueType.Int64:
                    return ((long)constant.Value).ToString(CultureInfo.InvariantCulture);

                case ValueType.Float:
                    return ((float)constant.Value).ToString("R", CultureInfo.InvariantCulture);

                case ValueType.Double:
                    return ((double)constant.Value).ToString("R", CultureInfo.InvariantCulture);

                // Ticks, matching what the generated fields hold and for the same reason.
                case ValueType.DateTime:
                    return ((DateTime)constant.Value).Ticks.ToString(CultureInfo.InvariantCulture);

                case ValueType.TimeSpan:
                    return ((TimeSpan)constant.Value).Ticks.ToString(CultureInfo.InvariantCulture);

                case ValueType.Uuid:
                    return "sheetman.Uuid(bytes([" + string.Join(", ",
                        ((Guid)constant.Value).ToByteArray()
                            .Select(b => b.ToString(CultureInfo.InvariantCulture))) + "]))";

                case ValueType.Enum:
                {
                    var label = constant.Enum.GetLabel(constant.Value, constant.Location);
                    return $"{constant.Enum.Name.ToPascalCase()}.{PythonName(label.Name)}";
                }

                default:
                    throw new SheetManException(constant.Location,
                        $"Constant `{constant.Name}` has type `{constant.Type}`, which the python generator cannot render.");
            }
        }

        private static string Quote(string value)
        {
            var literal = new StringBuilder("\"");

            foreach (var c in value ?? "")
            {
                if (c == '"')
                    literal.Append("\\\"");
                else if (c == '\\')
                    literal.Append(@"\\");
                else if (c == '\n')
                    literal.Append(@"\n");
                else if (c == '\r')
                    literal.Append(@"\r");
                else if (c == '\t')
                    literal.Append(@"\t");
                else if (c < 0x20)
                    literal.Append(@"\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                else
                    literal.Append(c);
            }

            return literal.Append('"').ToString();
        }

        /// <summary>
        /// A Python tuple literal, with the trailing comma a one-element tuple needs.
        /// </summary>
        private static string Tuple(IReadOnlyList<string> items, bool quote = true)
        {
            if (items.Count == 0)
                return "";

            string rendered = string.Join(", ", items.Select(item => quote ? $"\"{item}\"" : item));

            return items.Count == 1 ? rendered + "," : rendered;
        }

        // ------------------------------------------------------------- helpers

        /// <summary>
        /// An attribute name.
        ///
        /// snake_case, and escaped when it lands on a keyword - which it can, because
        /// Python members are lowercase and so is nearly every Python keyword.
        /// </summary>
        private static string PythonName(string name) => LanguageProfile.Python.MemberName(name.ToSnakeCase());

        private static IReadOnlyList<string> CommentLines(string comment)
        {
            if (string.IsNullOrWhiteSpace(comment))
                return Array.Empty<string>();

            return comment.Replace("\r\n", "\n").Split('\n').Select(DocText).ToArray();
        }

        /// <summary>
        /// Text safe to put inside a docstring.
        ///
        /// A sheet location contains a backslash on Windows, and a docstring is not raw, so
        /// the path reads as an escape sequence - which Python warns about today and will
        /// reject eventually. A triple quote inside one would end it.
        /// </summary>
        private static string DocText(string text)
            => (text ?? "").Replace("\\", "\\\\").Replace("\"\"\"", "\\\"\\\"\\\"");
    }
}
