# ------------------------------------------------------------------------------
# Generated by SheetMan. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------

require_relative 'sheetman/lite_binary_reader'

require_relative 'tables/template_table'


module X
  # Every table, loaded together so cross-table references can be resolved.
  class Tables
    attr_reader :template

    def initialize
      @template = TemplateTable.new
    end

    # Reads every table from base_path, then links the references between them.
    # Safe to call on a loaded accessor. Every file is read into a table of its own and
    # the references are linked among those, so a failure part way through leaves every
    # table holding the load it already had, and no row points at a row from it.
    def read_all(base_path, file_extension = '.scb')
      loaded_template = TemplateTable.new
      loaded_template.read(File.join(base_path, "Template#{file_extension}"))

      solve_cross_references(loaded_template)

      @template = loaded_template
    end

    private

    # Turns the stored indices into usable values, once every table is in memory.
    # The tables arrive as arguments rather than off the instance, which is how this
    # resolves the load being read rather than the one already published.
    def solve_cross_references(template)
      # No table references another.
      nil
    end
  end
end
