// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

// SheetMan's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using SheetMan.Binary;

namespace SheetMan.Fixtures.Core
{
    /// <summary>
    /// One cell holding several delimited values, length varying per row.
    /// </summary>
    [System.Serializable]
    public partial class ArrayTypesTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Fields
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;
            internal int _index;

            /// <summary>
            /// free-form tags
            /// </summary>
            public string[] Tags => _tags;
            internal string[] _tags = System.Array.Empty<string>();

            /// <summary>
            /// cost per level
            /// </summary>
            public int[] Costs => _costs;
            internal int[] _costs = System.Array.Empty<int>();

            /// <summary>
            /// drop weights
            /// </summary>
            public float[] Weights => _weights;
            internal float[] _weights = System.Array.Empty<float>();

            /// <summary>
            /// allowed grades
            /// </summary>
            public global::SheetMan.Fixtures.Core.Grade[] Grades => _grades;
            internal global::SheetMan.Fixtures.Core.Grade[] _grades = System.Array.Empty<global::SheetMan.Fixtures.Core.Grade>();

            /// <summary>
            /// fixed slot 1
            /// </summary>
            public int[] SlotArray => _slotArray;
            public const int SlotArray_N = 2;
            internal int[] _slotArray = System.Array.Empty<int>();
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Tags\":"); ToStringHelper.ToString(Tags, sb);
                sb.Append(",\"Costs\":"); ToStringHelper.ToString(Costs, sb);
                sb.Append(",\"Weights\":"); ToStringHelper.ToString(Weights, sb);
                sb.Append(",\"Grades\":"); ToStringHelper.ToString(Grades, sb);
                sb.Append(",\"SlotArray\":"); ToStringHelper.ToString(SlotArray, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Tags", "Costs", "Weights", "Grades", "SlotArray" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Tags, r.Costs, r.Weights, r.Grades, r.SlotArray });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        public List<Record> Records => _records;
        private readonly List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private readonly Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// Gets the value associated with the specified key. throw SheetManException if not found.
        /// </summary>
        public Record GetByIndex(int key)
        {
            if (!TryGetByIndex(key, out Record record))
                throw new SheetManException($"There is no record in table `ArrayTypes` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>
        /// Gets the value associated with the specified key.
        /// </summary>
        public bool TryGetByIndex(int key, out Record result) => _recordsByIndex.TryGetValue(key, out result);

        /// <summary>
        /// Determines whether the table contains the specified key.
        /// </summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await Tables.ReadAllBytesAsync(filename);
            var reader = new LiteBinaryReader(bytes);
            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(LiteBinaryReader reader)
        {
            var columns = LiteBinaryTable.ReadHeader(reader, out int count);
            int tempEnumInt = 0;

            _records.Clear();
            for (int i = 0; i < count; i++)
                _records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        LiteBinaryTable.CheckColumn(column, "ArrayTypes.Index", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            record._index = reader.ReadI32As(column.Element);
                        }
                        break;

                    case 2:
                        LiteBinaryTable.CheckColumn(column, "ArrayTypes.Tags", LiteBinaryTable.KindVarArray, 0, LiteBinaryTable.ElementString);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            reader.TryReadCounter32(out int elementCount);
                            record._tags = new string[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                reader.Read(out record._tags[j]);
                            }
                        }
                        break;

                    case 3:
                        LiteBinaryTable.CheckColumn(column, "ArrayTypes.Costs", LiteBinaryTable.KindVarArray, 0, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            reader.TryReadCounter32(out int elementCount);
                            record._costs = new int[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                record._costs[j] = reader.ReadI32As(column.Element);
                            }
                        }
                        break;

                    case 4:
                        LiteBinaryTable.CheckColumn(column, "ArrayTypes.Weights", LiteBinaryTable.KindVarArray, 0, LiteBinaryTable.ElementF32);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            reader.TryReadCounter32(out int elementCount);
                            record._weights = new float[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                reader.Read(out record._weights[j]);
                            }
                        }
                        break;

                    case 5:
                        LiteBinaryTable.CheckColumn(column, "ArrayTypes.Grades", LiteBinaryTable.KindVarArray, 0, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            reader.TryReadCounter32(out int elementCount);
                            record._grades = new global::SheetMan.Fixtures.Core.Grade[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                reader.ReadOptimalInt32(out tempEnumInt);
                                record._grades[j] = (global::SheetMan.Fixtures.Core.Grade)tempEnumInt;
                            }
                        }
                        break;

                    case 6:
                        LiteBinaryTable.CheckColumn(column, "ArrayTypes.Slot_array", LiteBinaryTable.KindFixedArray, 2, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            record._slotArray = new int[Record.SlotArray_N];
                            for (int j = 0; j < Record.SlotArray_N; ++j)
                            {
                                record._slotArray[j] = reader.ReadI32As(column.Element);
                            }
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                LiteBinaryTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping
            foreach (var record in _records)
                _recordsByIndex.Add(record.Index, record);

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }

} // namespace SheetMan.Fixtures.Core
