// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

// SheetMan's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using SheetMan.Binary;

namespace SheetMan.Fixtures.Core
{
    /// <summary>
    /// One column per supported primitive type.
    /// </summary>
    [System.Serializable]
    public partial class TestFieldTypesTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Values
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;

            /// <summary>
            /// utf8 text
            /// </summary>
            public string StringField => _stringField;

            /// <summary>
            /// logical flag
            /// </summary>
            public bool BoolField => _boolField;

            /// <summary>
            /// 32 bit integer
            /// </summary>
            public int IntField => _intField;

            /// <summary>
            /// 64 bit integer
            /// </summary>
            public long BigIntField => _bigIntField;

            /// <summary>
            /// single precision
            /// </summary>
            public float FloatField => _floatField;

            /// <summary>
            /// double precision
            /// </summary>
            public double DoubleField => _doubleField;

            /// <summary>
            /// date and time
            /// </summary>
            public System.DateTime DatetimeField => _datetimeField;

            /// <summary>
            /// time interval
            /// </summary>
            public System.TimeSpan TimespanField => _timespanField;

            /// <summary>
            /// globally unique id
            /// </summary>
            public System.Guid UuidField => _uuidField;

            /// <summary>
            /// enum reference
            /// </summary>
            public global::SheetMan.Fixtures.Core.ValueType ValueTypeField => _valueTypeField;
            #endregion

            #region Storage
            internal int _index;
            internal string _stringField = "";
            internal bool _boolField;
            internal int _intField;
            internal long _bigIntField;
            internal float _floatField;
            internal double _doubleField;
            internal System.DateTime _datetimeField;
            internal System.TimeSpan _timespanField;
            internal System.Guid _uuidField;
            internal global::SheetMan.Fixtures.Core.ValueType _valueTypeField;
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"StringField\":"); ToStringHelper.ToString(StringField, sb);
                sb.Append(",\"BoolField\":"); ToStringHelper.ToString(BoolField, sb);
                sb.Append(",\"IntField\":"); ToStringHelper.ToString(IntField, sb);
                sb.Append(",\"BigIntField\":"); ToStringHelper.ToString(BigIntField, sb);
                sb.Append(",\"FloatField\":"); ToStringHelper.ToString(FloatField, sb);
                sb.Append(",\"DoubleField\":"); ToStringHelper.ToString(DoubleField, sb);
                sb.Append(",\"DatetimeField\":"); ToStringHelper.ToString(DatetimeField, sb);
                sb.Append(",\"TimespanField\":"); ToStringHelper.ToString(TimespanField, sb);
                sb.Append(",\"UuidField\":"); ToStringHelper.ToString(UuidField, sb);
                sb.Append(",\"ValueTypeField\":"); ToStringHelper.ToString(ValueTypeField, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "StringField", "BoolField", "IntField", "BigIntField", "FloatField", "DoubleField", "DatetimeField", "TimespanField", "UuidField", "ValueTypeField" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.StringField, r.BoolField, r.IntField, r.BigIntField, r.FloatField, r.DoubleField, r.DatetimeField, r.TimespanField, r.UuidField, r.ValueTypeField });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        /// <remarks>
        /// The list a read publishes, not one a read fills. Whoever holds this reference holds
        /// the rows as they were when they took it, and a refresh underneath them replaces the
        /// reference rather than the contents - so an iteration in progress neither tears nor
        /// throws, and a read that fails leaves the previous rows exactly where they were.
        /// </remarks>
        public List<Record> Records => _records;
        private List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// The row with this `Index`, or null when the table has none.
        /// </summary>
        /// <remarks>
        /// The lookup to reach for when a missing row is an ordinary answer - an optional
        /// reference, a key that came from user input. Every language SheetMan generates has
        /// this one under the same name.
        /// </remarks>
        public Record FindByIndex(int key)
            => _recordsByIndex.TryGetValue(key, out Record record) ? record : null;

        /// <summary>
        /// The row with this `Index`, or a thrown exception naming what was
        /// missing.
        /// </summary>
        /// <remarks>
        /// For a key that has to be there - one from another table, or a constant. The name
        /// says it throws, because a caller reading `GetByIndex(id).Name` at
        /// a glance cannot otherwise tell whether the next line is a null check or a catch.
        /// </remarks>
        public Record GetByIndexOrThrow(int key)
        {
            if (!_recordsByIndex.TryGetValue(key, out Record record))
                throw new SheetManException($"There is no record in table `TestFieldTypes` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>Whether the table holds a row with this `Index`.</summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await Tables.ReadAllBytesAsync(filename);
            var reader = new ScbReader(bytes);
            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(ScbReader reader)
        {
            var columns = ScbTable.ReadHeader(reader, out int count);
            ScbColumnCursor cursor;

            // Read into storage of its own and published at the end, which is what makes a
            // refresh atomic: nothing here touches what the table is currently holding, so a
            // file that turns out to be truncated - or a column this build cannot read -
            // leaves the previous rows in place and reports why.
            //
            // Sized once. The row count was checked against what the columns declare before
            // this point, so it is a number the file could actually hold rows for - and a
            // list that grows into twenty thousand rows reallocates fifteen times to get
            // there, copying everything each time.
            var records = new List<Record>(count);

            for (int i = 0; i < count; i++)
                records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        ScbTable.CheckColumn(column, "TestFieldTypes.Index", ScbTable.KindScalar, 1, ScbTable.ElementI32, ScbTable.ElementVarint);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.Index");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameI32(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._index = value;
                            } while (--n > 0);
                        }
                        break;

                    case 2:
                        ScbTable.CheckColumn(column, "TestFieldTypes.StringField", ScbTable.KindScalar, 1, ScbTable.ElementString);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.StringField");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameString(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._stringField = value;
                            } while (--n > 0);
                        }
                        break;

                    case 3:
                        ScbTable.CheckColumn(column, "TestFieldTypes.BoolField", ScbTable.KindScalar, 1, ScbTable.ElementBool);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.BoolField");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            record._boolField = cursor.NextBool();
                        }
                        break;

                    case 4:
                        ScbTable.CheckColumn(column, "TestFieldTypes.IntField", ScbTable.KindScalar, 1, ScbTable.ElementI32, ScbTable.ElementVarint);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.IntField");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameI32(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._intField = value;
                            } while (--n > 0);
                        }
                        break;

                    case 5:
                        ScbTable.CheckColumn(column, "TestFieldTypes.BigIntField", ScbTable.KindScalar, 1, ScbTable.ElementI64, ScbTable.ElementI32, ScbTable.ElementVarint);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.BigIntField");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            record._bigIntField = cursor.NextI64();
                        }
                        break;

                    case 6:
                        ScbTable.CheckColumn(column, "TestFieldTypes.FloatField", ScbTable.KindScalar, 1, ScbTable.ElementF32);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.FloatField");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            record._floatField = cursor.NextF32();
                        }
                        break;

                    case 7:
                        ScbTable.CheckColumn(column, "TestFieldTypes.DoubleField", ScbTable.KindScalar, 1, ScbTable.ElementF64, ScbTable.ElementF32, ScbTable.ElementI32);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.DoubleField");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            record._doubleField = cursor.NextF64();
                        }
                        break;

                    case 8:
                        ScbTable.CheckColumn(column, "TestFieldTypes.DatetimeField", ScbTable.KindScalar, 1, ScbTable.ElementI64);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.DatetimeField");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            record._datetimeField = new System.DateTime(cursor.NextI64());
                        }
                        break;

                    case 9:
                        ScbTable.CheckColumn(column, "TestFieldTypes.TimespanField", ScbTable.KindScalar, 1, ScbTable.ElementI64);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.TimespanField");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            record._timespanField = new System.TimeSpan(cursor.NextI64());
                        }
                        break;

                    case 10:
                        ScbTable.CheckColumn(column, "TestFieldTypes.UuidField", ScbTable.KindScalar, 1, ScbTable.ElementUuid);
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            reader.Read(out record._uuidField);
                        }
                        break;

                    case 11:
                        ScbTable.CheckColumn(column, "TestFieldTypes.ValueTypeField", ScbTable.KindScalar, 1, ScbTable.ElementVarint);
                        cursor = new ScbColumnCursor(reader, column, count, "TestFieldTypes.ValueTypeField");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameI32(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._valueTypeField = (global::SheetMan.Fixtures.Core.ValueType)value;
                            } while (--n > 0);
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                ScbTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping. Sized to the rows, so nothing rehashes on the way in, and a
            // duplicate key throws here - before any of this is visible.
            var recordsByIndex = new Dictionary<int, Record>(count);
            foreach (var record in records)
                recordsByIndex.Add(record.Index, record);

            // Published. Everything above succeeded, and the barrier is what keeps the writes
            // that built these from being seen after the references to them - a reader on
            // another thread gets the whole table or the previous one, never half of either.
            System.Threading.Thread.MemoryBarrier();

            _records = records;
            _recordsByIndex = recordsByIndex;

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }

} // namespace SheetMan.Fixtures.Core
