// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef SHEETMAN_GENERATED_A_TEMPLATE_H
#define SHEETMAN_GENERATED_A_TEMPLATE_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "sheetman/lite_binary_reader.h"
#include "A_forward.h"

namespace x {
// Generated from test/fixtures/xlsx/reserved-words\reserved-words.xlsx : Data : B2
/// Named after a C++ keyword.
struct TemplateRecord {
  /// primary index
  std::int32_t index = 0;
  /// class: keyword in C++ and C#
  std::string sm_class;
  /// int: keyword in C++ and C#
  std::int32_t sm_int = 0;
  /// delete: keyword in C++
  bool sm_delete = false;
  /// operator: keyword in C++
  std::string sm_operator;
  /// namespace: keyword in C++ and C#
  std::string sm_namespace;
  /// constructor: special member in TypeScript
  std::string constructor;
  /// function: keyword in TypeScript
  std::string function;
};

/// Named after a C++ keyword.
class TemplateTable {
 public:
  const std::vector<TemplateRecord>& records() const { return records_; }

  /// Record with the given primary index, or nullptr when there is none.
  const TemplateRecord* find(std::int32_t index) const {
    const auto it = by_index_.find(index);
    return it == by_index_.end() ? nullptr : &records_[it->second];
  }

  /// Loads the table from a .table file written by SheetMan.
  void read(const std::string& filename) {
    const std::vector<std::uint8_t> buffer = sheetman::read_all_bytes(filename);
    sheetman::LiteBinaryReader reader(buffer);

    // Column by column, matched by tag rather than position: a column this build
    // does not know is skipped by its block length, and one whose type changed
    // incompatibly fails naming the field.
    const sheetman::Header header = sheetman::read_table_header(reader);
    const std::size_t row_count = static_cast<std::size_t>(header.row_count);

    // Read into storage of its own and swapped in at the end: reading a table that is
    // already loaded is a refresh, and one that throws part way through - a truncated
    // file, a column this build cannot read - has to leave the rows already there.
    std::vector<TemplateRecord> records;
    records.resize(row_count);

    for (const sheetman::Column& column : header.columns) {
      const std::size_t block_end = reader.position() + static_cast<std::size_t>(column.byte_length);

      switch (column.tag) {
        case 1: {
          sheetman::check_column(column, "Template.Index", sheetman::kKindScalar, 1, {sheetman::kElementI32, sheetman::kElementVarint});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read_i32_as(column.element, record.index);
          }
          break;
        }
        case 2: {
          sheetman::check_column(column, "Template.Class", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.sm_class);
          }
          break;
        }
        case 3: {
          sheetman::check_column(column, "Template.Int", sheetman::kKindScalar, 1, {sheetman::kElementI32, sheetman::kElementVarint});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read_i32_as(column.element, record.sm_int);
          }
          break;
        }
        case 4: {
          sheetman::check_column(column, "Template.Delete", sheetman::kKindScalar, 1, {sheetman::kElementBool});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.sm_delete);
          }
          break;
        }
        case 5: {
          sheetman::check_column(column, "Template.Operator", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.sm_operator);
          }
          break;
        }
        case 6: {
          sheetman::check_column(column, "Template.Namespace", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.sm_namespace);
          }
          break;
        }
        case 7: {
          sheetman::check_column(column, "Template.Constructor", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.constructor);
          }
          break;
        }
        case 8: {
          sheetman::check_column(column, "Template.Function", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.function);
          }
          break;
        }
        default:
          // A column added after this code was generated.
          reader.skip(column.byte_length);
          break;
      }

      sheetman::check_block_end(reader, column, block_end);
    }

    publish(std::move(records));
  }

 private:
  friend class Tables;

  /// One whole load, in place of the previous one.
  ///
  /// The index is built here rather than by the caller, because the two have to arrive
  /// together: a table holding this load's rows and the last one's index would answer
  /// `find` with a row that is no longer at that position.
  void publish(std::vector<TemplateRecord>&& records) {
    std::unordered_map<std::int32_t, std::size_t> by_index;
    by_index.reserve(records.size());
    for (std::size_t i = 0; i < records.size(); ++i) {
      by_index.emplace(records[i].index, i);
    }

    records_ = std::move(records);
    by_index_ = std::move(by_index);
  }

  std::vector<TemplateRecord> records_;
  std::unordered_map<std::int32_t, std::size_t> by_index_;
};

}  // namespace x

#endif  // SHEETMAN_GENERATED_A_TEMPLATE_H
