// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as path from 'path'

import { TestFieldTypesTable } from './tables/TestFieldTypes'
import { ItemCategoryTable } from './tables/ItemCategory'
import { ItemTable } from './tables/Item'
import { LocalizationTable } from './tables/Localization'
import { ArrayTypesTable } from './tables/ArrayTypes'
import { ServerTuningTable } from './tables/ServerTuning'

/** Tables */
export class Tables {
    /** Peroperty for table TestFieldTypes */
    public get testFieldTypes(): TestFieldTypesTable { return this._testFieldTypes }
    private _testFieldTypes: TestFieldTypesTable = new TestFieldTypesTable()

    /** Peroperty for table ItemCategory */
    public get itemCategory(): ItemCategoryTable { return this._itemCategory }
    private _itemCategory: ItemCategoryTable = new ItemCategoryTable()

    /** Peroperty for table Item */
    public get item(): ItemTable { return this._item }
    private _item: ItemTable = new ItemTable()

    /** Peroperty for table Localization */
    public get localization(): LocalizationTable { return this._localization }
    private _localization: LocalizationTable = new LocalizationTable()

    /** Peroperty for table ArrayTypes */
    public get arrayTypes(): ArrayTypesTable { return this._arrayTypes }
    private _arrayTypes: ArrayTypesTable = new ArrayTypesTable()

    /** Peroperty for table ServerTuning */
    public get serverTuning(): ServerTuningTable { return this._serverTuning }
    private _serverTuning: ServerTuningTable = new ServerTuningTable()

    /** Read all tables asynchronously. */
    public async readAll(basePath: string): Promise<void> {
        await this._testFieldTypes.read(path.join(basePath, 'TestFieldTypes.json'))
        await this._itemCategory.read(path.join(basePath, 'ItemCategory.json'))
        await this._item.read(path.join(basePath, 'Item.json'))
        await this._localization.read(path.join(basePath, 'Localization.json'))
        await this._arrayTypes.read(path.join(basePath, 'ArrayTypes.json'))
        await this._serverTuning.read(path.join(basePath, 'ServerTuning.json'))
    }

    /** Read all tables synchronously. */
    public readAllSync(basePath: string): void {
        this._testFieldTypes.readSync(path.join(basePath, 'TestFieldTypes.json'))
        this._itemCategory.readSync(path.join(basePath, 'ItemCategory.json'))
        this._item.readSync(path.join(basePath, 'Item.json'))
        this._localization.readSync(path.join(basePath, 'Localization.json'))
        this._arrayTypes.readSync(path.join(basePath, 'ArrayTypes.json'))
        this._serverTuning.readSync(path.join(basePath, 'ServerTuning.json'))

        this.solveCrossReferences()
    }

    private solveCrossReferences(): void {
    }
}

