// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/scb-reader'

/** A type for handling rows when parsing .json. */
interface IDataRow {
  index: number
  class: string
  int: number
  delete: boolean
  operator: string
  namespace: string
  constructor_: string
  function: string
}

// Generated from test/fixtures/xlsx/reserved-words/reserved-words.xlsx : Data : B2
/** Named after a C++ keyword. */
export class TemplateRecord {
  /** Default constructor */
  constructor() {
  }

  /** primary index */
  public get index(): number { return this._index }

  /** class: keyword in C++ and C# */
  public get class(): string { return this._class }

  /** int: keyword in C++ and C# */
  public get int(): number { return this._int }

  /** delete: keyword in C++ */
  public get delete(): boolean { return this._delete }

  /** operator: keyword in C++, and a secondary index */
  public get operator(): string { return this._operator }

  /** namespace: keyword in C++ and C# */
  public get namespace(): string { return this._namespace }

  /** constructor: special member in TypeScript */
  public get constructor_(): string { return this._constructor_ }

  /** function: keyword in TypeScript */
  public get function(): string { return this._function }

  public _index: number = 0
  public _class: string = ''
  public _int: number = 0
  public _delete: boolean = false
  public _operator: string = ''
  public _namespace: string = ''
  public _constructor_: string = ''
  public _function: string = ''

  /** Populate field values. */
  public populateFieldValues(dataRow: IDataRow): void {
    this._index = dataRow.index
    this._class = dataRow.class
    this._int = dataRow.int
    this._delete = dataRow.delete
    this._operator = dataRow.operator
    this._namespace = dataRow.namespace
    this._constructor_ = dataRow.constructor_
    this._function = dataRow.function
  }

  /** Populate field values. */
  public populateFieldValuesCompact(dataRow: any[]): void {
    let offset = 0
    this._index = dataRow[offset++]
    this._class = dataRow[offset++]
    this._int = dataRow[offset++]
    this._delete = dataRow[offset++]
    this._operator = dataRow[offset++]
    this._namespace = dataRow[offset++]
    this._constructor_ = dataRow[offset++]
    this._function = dataRow[offset++]
  }
}

// Generated from test/fixtures/xlsx/reserved-words/reserved-words.xlsx : Data : B2
/** Named after a C++ keyword. */
export class TemplateTable {
  /** Default constructor. */
  constructor() {
  }

  /** All records. */
  public get records(): TemplateRecord[] { return this._records }
  private _records: TemplateRecord[] = []

  // Indexing by 'index'
  public get recordsByIndex(): Map<number, TemplateRecord> { return this._recordsByIndex }
  private _recordsByIndex: Map<number, TemplateRecord> = new Map<number, TemplateRecord>()

  /**
   * The row with this index, or undefined when the table has none.
   *
   * The lookup to reach for when a missing row is an ordinary answer.
   */
  public findByIndex(key: number): TemplateRecord | undefined {
    return this._recordsByIndex.get(key)
  }

  /**
   * The row with this index, or a thrown Error naming what was missing.
   *
   * For a key that has to be there. The name says it throws, because a caller reading
   * `getByIndex(id).name` at a glance cannot otherwise tell whether the
   * next line is a check or a catch.
   */
  public getByIndexOrThrow(key: number): TemplateRecord {
    const found = this._recordsByIndex.get(key)
    if (!found)
      throw new Error(`There is no record in table "Template" that corresponds to field "index" value ${key}`)

    return found
  }

  /** Whether the table holds a row with this index. */
  public containsIndex(key: number): boolean {
    return this._recordsByIndex.has(key)
  }

  // Indexing by 'operator'
  public get recordsByOperator(): Map<string, TemplateRecord> { return this._recordsByOperator }
  private _recordsByOperator: Map<string, TemplateRecord> = new Map<string, TemplateRecord>()

  /**
   * The row with this operator, or undefined when the table has none.
   *
   * The lookup to reach for when a missing row is an ordinary answer.
   */
  public findByOperator(key: string): TemplateRecord | undefined {
    return this._recordsByOperator.get(key)
  }

  /**
   * The row with this operator, or a thrown Error naming what was missing.
   *
   * For a key that has to be there. The name says it throws, because a caller reading
   * `getByOperator(id).name` at a glance cannot otherwise tell whether the
   * next line is a check or a catch.
   */
  public getByOperatorOrThrow(key: string): TemplateRecord {
    const found = this._recordsByOperator.get(key)
    if (!found)
      throw new Error(`There is no record in table "Template" that corresponds to field "operator" value ${key}`)

    return found
  }

  /** Whether the table holds a row with this operator. */
  public containsOperator(key: string): boolean {
    return this._recordsByOperator.has(key)
  }

  /** Read a table from specified file. */
  public async read(filename: string): Promise<void> {
    const json = await fs.promises.readFile(filename, "utf8")
    this.readFromJson(json)
  }

  /** Read a table from specified file synchronously. */
  public readSync(filename: string): void {
    const json = fs.readFileSync(filename, "utf8")
    this.readFromJson(json)
  }

  private readFromJson(json: string): void {
    const dataRows: any[] = JSON.parse(json)
    const records: TemplateRecord[] = []

    if (this.isCompactRowFormatted(dataRows)) {
      for (const dataRow of dataRows) {
        const record = new TemplateRecord()
        record.populateFieldValuesCompact(dataRow)
        records.push(record)
      }
    } else {
      for (const dataRow of dataRows as IDataRow[]) {
        const record = new TemplateRecord()
        record.populateFieldValues(dataRow)
        records.push(record)
      }
    }

    this.publish(records)
  }

  private isCompactRowFormatted(rows: any[]): boolean {
    return rows.length > 0 && Array.isArray(rows[0])
  }

  /** Read a table from a binary .scb file. */
  public readBinarySync(filename: string): void {
    this.readBinaryFrom(sheetman.readAllBytes(filename))
  }

  /**
   * Read a table from binary data already in memory.
   *
   * Column by column, matched by tag rather than position: a column this build does not
   * know is skipped by its block length, and one whose type changed incompatibly fails
   * naming the field.
   */
  public readBinaryFrom(data: Uint8Array): void {
    const reader = new sheetman.ScbReader(data)
    const { rowCount, columns } = sheetman.readTableHeader(reader)
    let cursor: sheetman.ScbColumnCursor

    // Built here and published at the end, so a file that turns out to be truncated - or
    // a column this build cannot read - leaves the rows already loaded exactly as they are.
    const records: TemplateRecord[] = []
    for (let i = 0; i < rowCount; ++i)
      records.push(new TemplateRecord())

    for (const column of columns) {
      const blockEnd = reader.position + column.byteLength

      switch (column.tag) {
        case 1:
          sheetman.checkColumn(column, 'Template.Index', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
          cursor = new sheetman.ScbColumnCursor(reader, column, rowCount, 'Template.Index')
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            record._index = cursor.nextI32()
          }
          break
        case 2:
          sheetman.checkColumn(column, 'Template.Class', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
          cursor = new sheetman.ScbColumnCursor(reader, column, rowCount, 'Template.Class')
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            record._class = cursor.nextString()
          }
          break
        case 3:
          sheetman.checkColumn(column, 'Template.Int', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
          cursor = new sheetman.ScbColumnCursor(reader, column, rowCount, 'Template.Int')
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            record._int = cursor.nextI32()
          }
          break
        case 4:
          sheetman.checkColumn(column, 'Template.Delete', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_BOOL])
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            record._delete = reader.readBool()
          }
          break
        case 5:
          sheetman.checkColumn(column, 'Template.Operator', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
          cursor = new sheetman.ScbColumnCursor(reader, column, rowCount, 'Template.Operator')
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            record._operator = cursor.nextString()
          }
          break
        case 6:
          sheetman.checkColumn(column, 'Template.Namespace', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
          cursor = new sheetman.ScbColumnCursor(reader, column, rowCount, 'Template.Namespace')
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            record._namespace = cursor.nextString()
          }
          break
        case 7:
          sheetman.checkColumn(column, 'Template.Constructor', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
          cursor = new sheetman.ScbColumnCursor(reader, column, rowCount, 'Template.Constructor')
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            record._constructor_ = cursor.nextString()
          }
          break
        case 8:
          sheetman.checkColumn(column, 'Template.Function', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
          cursor = new sheetman.ScbColumnCursor(reader, column, rowCount, 'Template.Function')
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            record._function = cursor.nextString()
          }
          break
        default:
          // A column added after this code was generated.
          reader.skip(column.byteLength)
          break
      }

      sheetman.checkBlockEnd(reader, column, blockEnd)
    }

    this.publish(records)
  }

  /** Index mapping. */
  /**
   * Publishes one whole load: the rows and the lookups built from them, together.
   *
   * Reading a table that is already loaded - a refresh, a patched file - used to mutate what
   * consumers were holding: the rows were appended to or emptied first, so a read that threw
   * partway left the table holding some of the new data and none of the old. Everything above
   * builds its own arrays and gets here only if it finished, and this replaces the references
   * in one step. Whoever took `records` before still has the previous load, whole.
   */
  private publish(records: TemplateRecord[]): void {
    const recordsByIndex = new Map<number, TemplateRecord>()
    const recordsByOperator = new Map<string, TemplateRecord>()

    for (const record of records) {
      recordsByIndex.set(record.index, record)
      recordsByOperator.set(record.operator, record)
    }

    this._records = records
    this._recordsByIndex = recordsByIndex
    this._recordsByOperator = recordsByOperator
  }
}
