// ------------------------------------------------------------------------------
// Generated by SheetMan. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

// ignore_for_file: unused_import, constant_identifier_names

import 'dart:io';
import 'dart:typed_data';

import 'sheetman/lite_binary_reader.dart';

part 'tables/template_table.dart';

/// Every table, loaded together so cross-table references can be resolved.
class Tables {
  TemplateTable template = TemplateTable();

  /// Reads every table from basePath, then links the references between them.
  ///
  /// Safe to call on a loaded accessor: every file is read into a table of its own and
  /// the references are linked among those, so a failure part way through leaves every
  /// table holding the load it already had.
  void readAll(String basePath,
      [String fileExtension = '.table']) {
    final loadedTemplateTable = TemplateTable();
    loadedTemplateTable.read('$basePath${Platform.pathSeparator}Template$fileExtension');

    _solveCrossReferences(loadedTemplateTable);

    template = loadedTemplateTable;
  }

  /// Turns the stored indices into usable values, once every table is in memory.
  ///
  /// The tables arrive as arguments and shadow the fields of the same name, which is how
  /// this resolves the load being read rather than the one already published.
  void _solveCrossReferences(TemplateTable template) {
    // No table references another.
  }
}
