// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

// SheetMan's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using SheetMan.Binary;

namespace SheetMan.Fixtures.X
{
    #region Static tables
    public partial class Tables
    {
        public delegate Task<byte[]> ReadAllBytesAsyncDelegate(string filename);

        /// <summary>
        /// How a table file is read.
        /// </summary>
        /// <remarks>
        /// Replaceable, and that is the supported way to change it: assign your own before
        /// calling <c>ReadAllAsync</c> to read from a pack file, a CDN, an addressable, or
        /// anywhere else. The default below is chosen for the platform being compiled for
        /// and is correct for reading a file from disk.
        /// </remarks>
        public static ReadAllBytesAsyncDelegate ReadAllBytesAsync = DefaultReadAllBytesAsync;

        private static async Task<byte[]> DefaultReadAllBytesAsync(string filename)
        {
#if UNITY_WEBGL && !UNITY_EDITOR
            // WebGL has no threads, so nothing here can be moved off the main one. What it
            // does have is two different places a file can live, and they are not read the
            // same way:
            //
            //   StreamingAssets is served over HTTP - Application.streamingAssetsPath is a
            //   URL here, not a path - and the File API cannot see it at all.
            //
            //   persistentDataPath is a synchronous virtual filesystem over IndexedDB, and
            //   the File API does work on it.
            //
            // So the URL case goes through UnityWebRequest, which is genuinely asynchronous
            // because the browser does the waiting, and the rest is a synchronous read. The
            // synchronous read will block a frame; on WebGL that is the platform's answer
            // and not something this can improve on.
            if (filename.Contains("://"))
                return await ReadViaWebRequestAsync(filename);

            return File.ReadAllBytes(filename);
#elif !UNITY_5_3_OR_NEWER || UNITY_2021_2_OR_NEWER
            // Outside Unity, and inside Unity from 2021.2 - which is where the API level
            // moved to .NET Standard 2.1 and File.ReadAllBytesAsync arrived. Real
            // asynchronous I/O: no thread is held while the disk works.
            return await File.ReadAllBytesAsync(filename);
#else
            // Unity 2019 and 2020 on .NET Standard 2.0, which has no asynchronous file API.
            // A worker thread is the only way to keep the main one moving, so this is the
            // one branch that spends one.
            return await Task.Run(() => File.ReadAllBytes(filename));
#endif
        }

#if UNITY_WEBGL && !UNITY_EDITOR
        /// <summary>
        /// Fetches a file the browser has to go and get.
        /// </summary>
        private static async Task<byte[]> ReadViaWebRequestAsync(string url)
        {
            using (var request = UnityEngine.Networking.UnityWebRequest.Get(url))
            {
                var operation = request.SendWebRequest();

                // Yielding rather than blocking: WebGL is single threaded, so waiting on a
                // handle here would stop the frame that the request needs in order to
                // finish, and nothing would ever complete.
                while (!operation.isDone)
                    await Task.Yield();

#if UNITY_2020_2_OR_NEWER
                if (request.result != UnityEngine.Networking.UnityWebRequest.Result.Success)
                    throw new SheetManException($"Cannot read '{url}': {request.error}");
#else
                if (request.isNetworkError || request.isHttpError)
                    throw new SheetManException($"Cannot read '{url}': {request.error}");
#endif

                return request.downloadHandler.data;
            }
        }
#endif

        /// <summary>
        /// Property for OffsetTable table.
        /// </summary>
        public static OffsetTableTable OffsetTable { get; private set; }

        /// <summary>
        /// Property for SecondTable table.
        /// </summary>
        public static SecondTableTable SecondTable { get; private set; }

        /// <summary>
        /// Read all tables.
        /// </summary>
        public static async Task ReadAllAsync(string basePath, string fileExtension = ".table")
        {
            var tasks = new List<Task>();

            OffsetTable = new OffsetTableTable();
            tasks.Add(OffsetTable.ReadAsync(System.IO.Path.Combine(basePath, $"OffsetTable{fileExtension}")));

            SecondTable = new SecondTableTable();
            tasks.Add(SecondTable.ReadAsync(System.IO.Path.Combine(basePath, $"SecondTable{fileExtension}")));

            await Task.WhenAll(tasks);

            SolveCrossReferences();
        }

        /// <summary>
        /// Solve cross references.
        /// </summary>
        private static void SolveCrossReferences()
        {
        }
    }
    #endregion

    #region OffsetTableTable
    /// <summary>
    /// Starts at F9 rather than the top-left corner.
    /// </summary>
    [System.Serializable]
    public partial class OffsetTableTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Fields
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;
            private int _index;

            /// <summary>
            /// name
            /// </summary>
            public string Name => _name;
            private string _name;

            /// <summary>
            /// value
            /// </summary>
            public int Value => _value;
            private int _value;
            #endregion

            #region Read record
            /// <summary>
            /// Reads a table record.
            /// </summary>
            public Task ReadAsync(LiteBinaryReader reader)
            {
                reader.Read(out _index);

                reader.Read(out _name);

                reader.Read(out _value);

                return Task.CompletedTask;
            }
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Name\":"); ToStringHelper.ToString(Name, sb);
                sb.Append(",\"Value\":"); ToStringHelper.ToString(Value, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Name", "Value" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Name, r.Value });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        public List<Record> Records => _records;
        private readonly List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private readonly Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// Gets the value associated with the specified key. throw SheetManException if not found.
        /// </summary>
        public Record GetByIndex(int key)
        {
            if (!TryGetByIndex(key, out Record record))
                throw new SheetManException($"There is no record in table `OffsetTable` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>
        /// Gets the value associated with the specified key.
        /// </summary>
        public bool TryGetByIndex(int key, out Record result) => _recordsByIndex.TryGetValue(key, out result);

        /// <summary>
        /// Determines whether the table contains the specified key.
        /// </summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await Tables.ReadAllBytesAsync(filename);
            var reader = new LiteBinaryReader(bytes);
            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        public async Task ReadAsync(LiteBinaryReader reader)
        {
            // Version and reserved flags are checked by the reader.
            uint version = 0;
            reader.Read(out version);

            byte flags = 0;
            reader.Read(out flags);

            int count = reader.ReadCounter32();
            for (int i = 0; i < count; i++)
            {
                var record = new Record();
                await record.ReadAsync(reader);
                _records.Add(record);
            }

            // Index mapping
            foreach (var record in _records)
                _recordsByIndex.Add(record.Index, record);
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }
    #endregion

    #region SecondTableTable
    /// <summary>
    /// Keeps the ragged row from being trimmed as a trailing blank.
    /// </summary>
    [System.Serializable]
    public partial class SecondTableTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Fields
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;
            private int _index;

            /// <summary>
            /// label
            /// </summary>
            public string Label => _label;
            private string _label;

            /// <summary>
            /// amount
            /// </summary>
            public int Amount => _amount;
            private int _amount;
            #endregion

            #region Read record
            /// <summary>
            /// Reads a table record.
            /// </summary>
            public Task ReadAsync(LiteBinaryReader reader)
            {
                reader.Read(out _index);

                reader.Read(out _label);

                reader.Read(out _amount);

                return Task.CompletedTask;
            }
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Label\":"); ToStringHelper.ToString(Label, sb);
                sb.Append(",\"Amount\":"); ToStringHelper.ToString(Amount, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Label", "Amount" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Label, r.Amount });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        public List<Record> Records => _records;
        private readonly List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private readonly Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// Gets the value associated with the specified key. throw SheetManException if not found.
        /// </summary>
        public Record GetByIndex(int key)
        {
            if (!TryGetByIndex(key, out Record record))
                throw new SheetManException($"There is no record in table `SecondTable` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>
        /// Gets the value associated with the specified key.
        /// </summary>
        public bool TryGetByIndex(int key, out Record result) => _recordsByIndex.TryGetValue(key, out result);

        /// <summary>
        /// Determines whether the table contains the specified key.
        /// </summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await Tables.ReadAllBytesAsync(filename);
            var reader = new LiteBinaryReader(bytes);
            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        public async Task ReadAsync(LiteBinaryReader reader)
        {
            // Version and reserved flags are checked by the reader.
            uint version = 0;
            reader.Read(out version);

            byte flags = 0;
            reader.Read(out flags);

            int count = reader.ReadCounter32();
            for (int i = 0; i < count; i++)
            {
                var record = new Record();
                await record.ReadAsync(reader);
                _records.Add(record);
            }

            // Index mapping
            foreach (var record in _records)
                _recordsByIndex.Add(record.Index, record);
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }
    #endregion

    #region Helpers
    /// <summary>
    /// Exception about SheetMan.
    /// </summary>
    public class SheetManException : System.Exception
    {
        public SheetManException()
        {
        }

        public SheetManException(string message) : base(message)
        {
        }

        public SheetManException(string message, System.Exception inner) : base(message, inner)
        {
        }
    }

    /// <summary>
    /// Collection helper class.
    /// </summary>
    public static class CollectionsHelper
    {
        /// <summary>
        /// This will return true if the two collections are value-wise the same.
        /// If the collection contains a collection, the collections will be compared using this method.
        /// </summary>
        public static bool Equals(IEnumerable first, IEnumerable second)
        {
            if (first == null && second == null)
                return true;

            if (first == null || second == null)
                return false;

            var fiter = first.GetEnumerator();
            var siter = second.GetEnumerator();

            var fnext = fiter.MoveNext();
            var snext = siter.MoveNext();

            while (fnext && snext)
            {
                var fenum = fiter.Current as IEnumerable;
                var senum = siter.Current as IEnumerable;

                if (fenum != null && senum != null)
                {
                    if (!Equals(fenum, senum))
                        return false;
                }
                else if (fenum == null ^ senum == null)
                {
                    return false;
                }
                else if (!Equals(fiter.Current, siter.Current))
                {
                    return false;
                }

                fnext = fiter.MoveNext();
                snext = siter.MoveNext();
            }

            return fnext == snext;
        }

        /// <summary>
        /// This returns a hashcode based on the value of the enumerable.
        /// </summary>
        public static int GetHashCode(IEnumerable enumerable)
        {
            if (enumerable == null)
                return 0;

            int hashcode = 0;
            foreach (var item in enumerable)
            {
                int objHash = !(item is IEnumerable enumerableItem) ? item.GetHashCode() : GetHashCode(enumerableItem);

                unchecked
                {
                    hashcode = (hashcode * 397) ^ objHash;
                }
            }

            return hashcode;
        }
    }
    /// <summary>
    /// ToString helper class.
    /// </summary>
    public static class ToStringHelper
    {
        public static void ToString(object self, StringBuilder target, bool first = true)
        {
            if (!first)
                target.Append(", ");

            bool firstChild = true;
            if (self is string)
            {
                target.Append('"');
                target.Append(self);
                target.Append('"');
            }
            else if (self is IDictionary dictionary)
            {
                target.Append("{");
                foreach (DictionaryEntry pair in dictionary)
                {
                    if (firstChild)
                        firstChild = false;
                    else
                        target.Append(", ");

                    target.Append("{");
                    ToString(pair.Key, target, true);
                    target.Append(", ");
                    ToString(pair.Value, target, true);
                    target.Append("}");
                }
                target.Append("}");
            }
            else if (self is IEnumerable enumerable)
            {
                target.Append("[");
                foreach (var element in enumerable)
                {
                    ToString(element, target, firstChild);
                    firstChild = false;
                }
                target.Append("]");
            }
            else
            {
                target.Append(self);
            }
        }
    }
    #endregion

} // namespace SheetMan.Fixtures.X

