// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/lite_binary_reader'

// Automatically import to handle external type references.
import { ValueType } from '../enums/ValueType'

/** A type for handling rows when parsing .json. */
interface IDataRow {
    index: number
    stringField: string
    boolField: boolean
    intField: number
    bigIntField: string
    floatField: number
    doubleField: number
    datetimeField: string
    timespanField: string
    uuidField: string
    valueTypeField: ValueType
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Types : B2
/** One column per supported primitive type. */
export class TestFieldTypesRecord {
    /** Default constructor */
    constructor() {
    }

    /** primary index */
    public get index(): number { return this._index }
    private _index: number

    /** utf8 text */
    public get stringField(): string { return this._stringField }
    private _stringField: string

    /** logical flag */
    public get boolField(): boolean { return this._boolField }
    private _boolField: boolean

    /** 32 bit integer */
    public get intField(): number { return this._intField }
    private _intField: number

    /** 64 bit integer */
    public get bigIntField(): bigint { return this._bigIntField }
    private _bigIntField: bigint

    /** single precision */
    public get floatField(): number { return this._floatField }
    private _floatField: number

    /** double precision */
    public get doubleField(): number { return this._doubleField }
    private _doubleField: number

    /** date and time */
    public get datetimeField(): string { return this._datetimeField }
    private _datetimeField: string

    /** time interval */
    public get timespanField(): string { return this._timespanField }
    private _timespanField: string

    /** globally unique id */
    public get uuidField(): string { return this._uuidField }
    private _uuidField: string

    /** enum reference */
    public get valueTypeField(): ValueType { return this._valueTypeField }
    private _valueTypeField: ValueType

    /** Populate field values. */
    public populateFieldValues(dataRow: IDataRow): void {
        this._index = dataRow.index
        this._stringField = dataRow.stringField
        this._boolField = dataRow.boolField
        this._intField = dataRow.intField
        this._bigIntField = BigInt(dataRow.bigIntField)
        this._floatField = Math.fround(dataRow.floatField)
        this._doubleField = dataRow.doubleField
        this._datetimeField = dataRow.datetimeField
        this._timespanField = dataRow.timespanField
        this._uuidField = dataRow.uuidField
        this._valueTypeField = dataRow.valueTypeField
    }

    /** Populate field values. */
    public populateFieldValuesCompact(dataRow: any[]): void {
        let offset = 0
        this._index = dataRow[offset++]
        this._stringField = dataRow[offset++]
        this._boolField = dataRow[offset++]
        this._intField = dataRow[offset++]
        this._bigIntField = BigInt(dataRow[offset++])
        this._floatField = Math.fround(dataRow[offset++])
        this._doubleField = dataRow[offset++]
        this._datetimeField = dataRow[offset++]
        this._timespanField = dataRow[offset++]
        this._uuidField = dataRow[offset++]
        this._valueTypeField = dataRow[offset++]
    }

    /** Read one record. Field order must match the exporter's. */
    public readBinary(reader: sheetman.LiteBinaryReader): void
    {
        this._index = reader.readInt32()
        this._stringField = reader.readString()
        this._boolField = reader.readBool()
        this._intField = reader.readInt32()
        this._bigIntField = reader.readInt64()
        this._floatField = reader.readFloat()
        this._doubleField = reader.readDouble()
        this._datetimeField = reader.readDateTime()
        this._timespanField = reader.readTimeSpan()
        this._uuidField = reader.readUuid()
        this._valueTypeField = reader.readEnum() as ValueType
    }
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Types : B2
/** One column per supported primitive type. */
export class TestFieldTypesTable {
    /** Default constructor. */
    constructor() {
    }

    /** All records. */
    public get records(): TestFieldTypesRecord[] { return this._records }
    private _records: TestFieldTypesRecord[] = []

    // Indexing by 'index'
    public get recordsByIndex(): Map<number, TestFieldTypesRecord> { return this._recordsByIndex }
    private _recordsByIndex: Map<number, TestFieldTypesRecord> = new Map<number, TestFieldTypesRecord>()

    /** Gets the value associated with the specified key. throw Error if not found. */
    public getByIndex(key: number): TestFieldTypesRecord {
        const found = this._recordsByIndex.get(key)
        if (!found)
            throw new Error(`There is no record in table "TestFieldTypes" that corresponds to field "index" value ${key}`)

        return found
    }

    /** Gets the value associated with the specified key. */
    public tryGetByIndex(key: number): TestFieldTypesRecord | undefined {
        return this._recordsByIndex.get(key)
    }

    /** Determines whether the table contains the specified key. */
    public containsIndex(key: number): boolean {
        return !!this._recordsByIndex.has(key)
    }

    /** Read a table from specified file. */
    public async read(filename: string): Promise<void> {
        const json = await fs.promises.readFile(filename, "utf8")
        this.readFromJson(json)
    }

    /** Read a table from specified file synchronously. */
    public readSync(filename: string): void {
        const json = fs.readFileSync(filename, "utf8")
        this.readFromJson(json)
    }

    private readFromJson(json: string): void {
        const dataRows: any[] = JSON.parse(json)
        if (this.isCompactRowFormatted(dataRows)) {
            for (const dataRow of dataRows) {
                const record = new TestFieldTypesRecord()
                record.populateFieldValuesCompact(dataRow)
                this._records.push(record)
            }
        } else {
            for (const dataRow of dataRows as IDataRow[]) {
                const record = new TestFieldTypesRecord()
                record.populateFieldValues(dataRow)
                this._records.push(record)
            }
        }

        this.mapping()
    }

    private isCompactRowFormatted(rows: any[]): boolean {
        return rows.length > 0 && Array.isArray(rows[0])
    }

    /** Read a table from a binary .table file. */
    public readBinarySync(filename: string): void
    {
        this.readBinaryFrom(sheetman.readAllBytes(filename))
    }

    /** Read a table from binary data already in memory. */
    public readBinaryFrom(data: Uint8Array): void
    {
        const reader = new sheetman.LiteBinaryReader(data)
        const rowCount = sheetman.readTableHeader(reader)

        for (let i = 0; i < rowCount; ++i)
        {
            const record = new TestFieldTypesRecord()
            record.readBinary(reader)
            this._records.push(record)
        }

        this.mapping()
    }

    /** Index mapping. */
    private mapping(): void {
        for (const record of this._records)
        {
            this._recordsByIndex.set(record.index, record)
        }
    }
}
