// ------------------------------------------------------------------------------
// Generated by SheetMan. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

part of '../a.dart';
// Generated from test/fixtures/xlsx/reserved-words\reserved-words.xlsx : Data : B2
/// Named after a C++ keyword.
class TemplateRecord {
  /// primary index
  int index = 0;
  /// class: keyword in C++ and C#
  String class_ = '';
  /// int: keyword in C++ and C#
  int int_ = 0;
  /// delete: keyword in C++
  bool delete = false;
  /// operator: keyword in C++
  String operator = '';
  /// namespace: keyword in C++ and C#
  String namespace = '';
  /// constructor: special member in TypeScript
  String constructor = '';
  /// function: keyword in TypeScript
  String function = '';

}

/// Every row of Template.
class TemplateTable {
  /// Every row, in the order the sheet declared them.
  ///
  /// The list a read published, not one a read fills. A refresh replaces the reference
  /// rather than the contents, so whoever holds this holds one whole load.
  List<TemplateRecord> get records => _records;
  List<TemplateRecord> _records = [];

  Map<int, TemplateRecord> _byIndex = {};

  /// The row with the given primary index, or null when there is none.
  TemplateRecord? find(int index) => _byIndex[index];

  /// Loads the table from a .table file written by SheetMan.
  /// Column by column, matched by tag rather than position: a column this build does
  /// not know is skipped by its block length, and one whose type changed incompatibly
  /// fails naming the field.
  void read(String filename) {
    final reader = LiteBinaryReader(readAllBytes(filename));
    final header = readTableHeader(reader);
    final count = header.rowCount;

    // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
    final loaded = <TemplateRecord>[];
    final loadedByIndex = <int, TemplateRecord>{};

    for (var i = 0; i < count; i++) {
      loaded.add(TemplateRecord());
    }

    for (final column in header.columns) {
      final blockEnd = reader.position + column.byteLength;

      switch (column.tag) {
        case 1:
          checkColumn(column, 'Template.Index', kindScalar, 1, [elementI32, elementVarint]);
          for (final record in loaded) {
            record.index = reader.readI32As(column.element);
          }
          break;
        case 2:
          checkColumn(column, 'Template.Class', kindScalar, 1, [elementString]);
          for (final record in loaded) {
            record.class_ = reader.readString();
          }
          break;
        case 3:
          checkColumn(column, 'Template.Int', kindScalar, 1, [elementI32, elementVarint]);
          for (final record in loaded) {
            record.int_ = reader.readI32As(column.element);
          }
          break;
        case 4:
          checkColumn(column, 'Template.Delete', kindScalar, 1, [elementBool]);
          for (final record in loaded) {
            record.delete = reader.readBool();
          }
          break;
        case 5:
          checkColumn(column, 'Template.Operator', kindScalar, 1, [elementString]);
          for (final record in loaded) {
            record.operator = reader.readString();
          }
          break;
        case 6:
          checkColumn(column, 'Template.Namespace', kindScalar, 1, [elementString]);
          for (final record in loaded) {
            record.namespace = reader.readString();
          }
          break;
        case 7:
          checkColumn(column, 'Template.Constructor', kindScalar, 1, [elementString]);
          for (final record in loaded) {
            record.constructor = reader.readString();
          }
          break;
        case 8:
          checkColumn(column, 'Template.Function', kindScalar, 1, [elementString]);
          for (final record in loaded) {
            record.function = reader.readString();
          }
          break;
        default:
          // A column added after this code was generated.
          reader.skip(column.byteLength);
          break;
      }

      checkBlockEnd(reader, column, blockEnd);
    }

    for (final record in loaded) {
      loadedByIndex[record.index] = record;
    }

    // Published, now that every column read.
    _records = loaded;
    _byIndex = loadedByIndex;
  }
}
