// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

// SheetMan's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using SheetMan.Binary;

namespace SheetMan.Fixtures.X
{
    /// <summary>
    /// Target of the field-level reference below.
    /// </summary>
    [System.Serializable]
    public partial class ItemCategoryTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Values
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;

            /// <summary>
            /// category name
            /// </summary>
            public string Name => _name;

            /// <summary>
            /// description
            /// </summary>
            public string Description => _description;
            #endregion

            #region Storage
            internal int _index;
            internal string _name = "";
            internal string _description = "";
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Name\":"); ToStringHelper.ToString(Name, sb);
                sb.Append(",\"Description\":"); ToStringHelper.ToString(Description, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Name", "Description" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Name, r.Description });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        public List<Record> Records => _records;
        private readonly List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private readonly Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// Gets the value associated with the specified key. throw SheetManException if not found.
        /// </summary>
        public Record GetByIndex(int key)
        {
            if (!TryGetByIndex(key, out Record record))
                throw new SheetManException($"There is no record in table `ItemCategory` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>
        /// Gets the value associated with the specified key.
        /// </summary>
        public bool TryGetByIndex(int key, out Record result) => _recordsByIndex.TryGetValue(key, out result);

        /// <summary>
        /// Determines whether the table contains the specified key.
        /// </summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await Tables.ReadAllBytesAsync(filename);
            var reader = new LiteBinaryReader(bytes);
            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(LiteBinaryReader reader)
        {
            var columns = LiteBinaryTable.ReadHeader(reader, out int count);

            _records.Clear();
            _recordsByIndex.Clear();

            // Sized once. The row count was checked against what the columns declare before
            // this point, so it is a number the file could actually hold rows for - and a
            // list that grows into twenty thousand rows reallocates fifteen times to get
            // there, copying everything each time.
            if (_records.Capacity < count)
                _records.Capacity = count;

            for (int i = 0; i < count; i++)
                _records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        LiteBinaryTable.CheckColumn(column, "ItemCategory.Index", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementI32, LiteBinaryTable.ElementVarint);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            record._index = reader.ReadI32As(column.Element);
                        }
                        break;

                    case 2:
                        LiteBinaryTable.CheckColumn(column, "ItemCategory.Name", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementString);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            reader.Read(out record._name);
                        }
                        break;

                    case 3:
                        LiteBinaryTable.CheckColumn(column, "ItemCategory.Description", LiteBinaryTable.KindScalar, 1, LiteBinaryTable.ElementString);
                        for (int i = 0; i < count; i++)
                        {
                            var record = _records[i];
                            reader.Read(out record._description);
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                LiteBinaryTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping
            foreach (var record in _records)
                _recordsByIndex.Add(record.Index, record);

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }

} // namespace SheetMan.Fixtures.X
