// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/lite_binary_reader'

// Automatically import to handle external type references.
import { Grade } from '../enums/Grade'

/** A type for handling rows when parsing .json. */
interface IDataRow {
    index: number
    tags: string[]
    costs: number[]
    weights: number[]
    grades: Grade[]
    slotArray: number[]
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Arrays : B2
/** One cell holding several delimited values, length varying per row. */
export class ArrayTypesRecord {
    /** Default constructor */
    constructor() {
    }

    /** primary index */
    public get index(): number { return this._index }
    private _index: number

    /** free-form tags */
    public get tags(): string[] { return this._tags }
    private _tags: string[] = []

    /** cost per level */
    public get costs(): number[] { return this._costs }
    private _costs: number[] = []

    /** drop weights */
    public get weights(): number[] { return this._weights }
    private _weights: number[] = []

    /** allowed grades */
    public get grades(): Grade[] { return this._grades }
    private _grades: Grade[] = []

    /** fixed slot 1 */
    public get slotArray(): number[] { return this._slotArray }
    public static readonly slotArray_N = 2
    private _slotArray: number[]

    /** Populate field values. */
    public populateFieldValues(dataRow: IDataRow): void {
        this._index = dataRow.index
        this._tags = dataRow.tags
        this._costs = dataRow.costs
        this._weights = dataRow.weights.map(v => Math.fround(v))
        this._grades = dataRow.grades
        this._slotArray = dataRow.slotArray
    }

    /** Populate field values. */
    public populateFieldValuesCompact(dataRow: any[]): void {
        let offset = 0
        this._index = dataRow[offset++]
        this._tags = dataRow[offset++]
        this._costs = dataRow[offset++]
        this._weights = dataRow[offset++].map(v => Math.fround(v))
        this._grades = dataRow[offset++]
        this._slotArray = dataRow.slice(offset, offset + 2)
        offset += 2
    }

    /** Read one record. Field order must match the exporter's. */
    public readBinary(reader: sheetman.LiteBinaryReader): void
    {
        this._index = reader.readInt32()
        {
            const count = reader.readCounter32()
            this._tags = []
            for (let i = 0; i < count; ++i)
            {
                this._tags.push(reader.readString())
            }
        }
        {
            const count = reader.readCounter32()
            this._costs = []
            for (let i = 0; i < count; ++i)
            {
                this._costs.push(reader.readInt32())
            }
        }
        {
            const count = reader.readCounter32()
            this._weights = []
            for (let i = 0; i < count; ++i)
            {
                this._weights.push(reader.readFloat())
            }
        }
        {
            const count = reader.readCounter32()
            this._grades = []
            for (let i = 0; i < count; ++i)
            {
                this._grades.push(reader.readEnum() as Grade)
            }
        }
        this._slotArray = []
        for (let i = 0; i < 2; ++i)
        {
            this._slotArray.push(reader.readInt32())
        }
    }
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Arrays : B2
/** One cell holding several delimited values, length varying per row. */
export class ArrayTypesTable {
    /** Default constructor. */
    constructor() {
    }

    /** All records. */
    public get records(): ArrayTypesRecord[] { return this._records }
    private _records: ArrayTypesRecord[] = []

    // Indexing by 'index'
    public get recordsByIndex(): Map<number, ArrayTypesRecord> { return this._recordsByIndex }
    private _recordsByIndex: Map<number, ArrayTypesRecord> = new Map<number, ArrayTypesRecord>()

    /** Gets the value associated with the specified key. throw Error if not found. */
    public getByIndex(key: number): ArrayTypesRecord {
        const found = this._recordsByIndex.get(key)
        if (!found)
            throw new Error(`There is no record in table "ArrayTypes" that corresponds to field "index" value ${key}`)

        return found
    }

    /** Gets the value associated with the specified key. */
    public tryGetByIndex(key: number): ArrayTypesRecord | undefined {
        return this._recordsByIndex.get(key)
    }

    /** Determines whether the table contains the specified key. */
    public containsIndex(key: number): boolean {
        return !!this._recordsByIndex.has(key)
    }

    /** Read a table from specified file. */
    public async read(filename: string): Promise<void> {
        const json = await fs.promises.readFile(filename, "utf8")
        this.readFromJson(json)
    }

    /** Read a table from specified file synchronously. */
    public readSync(filename: string): void {
        const json = fs.readFileSync(filename, "utf8")
        this.readFromJson(json)
    }

    private readFromJson(json: string): void {
        const dataRows: any[] = JSON.parse(json)
        if (this.isCompactRowFormatted(dataRows)) {
            for (const dataRow of dataRows) {
                const record = new ArrayTypesRecord()
                record.populateFieldValuesCompact(dataRow)
                this._records.push(record)
            }
        } else {
            for (const dataRow of dataRows as IDataRow[]) {
                const record = new ArrayTypesRecord()
                record.populateFieldValues(dataRow)
                this._records.push(record)
            }
        }

        this.mapping()
    }

    private isCompactRowFormatted(rows: any[]): boolean {
        return rows.length > 0 && Array.isArray(rows[0])
    }

    /** Read a table from a binary .table file. */
    public readBinarySync(filename: string): void
    {
        this.readBinaryFrom(sheetman.readAllBytes(filename))
    }

    /** Read a table from binary data already in memory. */
    public readBinaryFrom(data: Uint8Array): void
    {
        const reader = new sheetman.LiteBinaryReader(data)
        const rowCount = sheetman.readTableHeader(reader)

        for (let i = 0; i < rowCount; ++i)
        {
            const record = new ArrayTypesRecord()
            record.readBinary(reader)
            this._records.push(record)
        }

        this.mapping()
    }

    /** Index mapping. */
    private mapping(): void {
        for (const record of this._records)
        {
            this._recordsByIndex.set(record.index, record)
        }
    }
}

