// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/lite_binary_reader'

/** A type for handling rows when parsing .json. */
interface IDataRow {
    index: number
    key: string
    textEnArray: string[]
    textKoArray: string[]
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Serial : B2
/** Trailing-number columns collapse into arrays. */
export class LocalizationRecord {
    /** Default constructor */
    constructor() {
    }

    /** primary index */
    public get index(): number { return this._index }

    /** lookup key */
    public get key(): string { return this._key }

    /** english text 1 */
    public get textEnArray(): string[] { return this._textEnArray }
    public static readonly textEnArray_N: number = 2

    /** korean text 1 */
    public get textKoArray(): string[] { return this._textKoArray }
    public static readonly textKoArray_N: number = 2

    public _index: number = 0
    public _key: string = ''
    public _textEnArray: string[] = []
    public _textKoArray: string[] = []

    /** Populate field values. */
    public populateFieldValues(dataRow: IDataRow): void {
        this._index = dataRow.index
        this._key = dataRow.key
        this._textEnArray = dataRow.textEnArray
        this._textKoArray = dataRow.textKoArray
    }

    /** Populate field values. */
    public populateFieldValuesCompact(dataRow: any[]): void {
        let offset = 0
        this._index = dataRow[offset++]
        this._key = dataRow[offset++]
        this._textEnArray = dataRow.slice(offset, offset + 2)
        offset += 2
        this._textKoArray = dataRow.slice(offset, offset + 2)
        offset += 2
    }
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Serial : B2
/** Trailing-number columns collapse into arrays. */
export class LocalizationTable {
    /** Default constructor. */
    constructor() {
    }

    /** All records. */
    public get records(): LocalizationRecord[] { return this._records }
    private _records: LocalizationRecord[] = []

    // Indexing by 'index'
    public get recordsByIndex(): Map<number, LocalizationRecord> { return this._recordsByIndex }
    private _recordsByIndex: Map<number, LocalizationRecord> = new Map<number, LocalizationRecord>()

    /** Gets the value associated with the specified key. throw Error if not found. */
    public getByIndex(key: number): LocalizationRecord {
        const found = this._recordsByIndex.get(key)
        if (!found)
            throw new Error(`There is no record in table "Localization" that corresponds to field "index" value ${key}`)

        return found
    }

    /** Gets the value associated with the specified key. */
    public tryGetByIndex(key: number): LocalizationRecord | undefined {
        return this._recordsByIndex.get(key)
    }

    /** Determines whether the table contains the specified key. */
    public containsIndex(key: number): boolean {
        return !!this._recordsByIndex.has(key)
    }

    /** Read a table from specified file. */
    public async read(filename: string): Promise<void> {
        const json = await fs.promises.readFile(filename, "utf8")
        this.readFromJson(json)
    }

    /** Read a table from specified file synchronously. */
    public readSync(filename: string): void {
        const json = fs.readFileSync(filename, "utf8")
        this.readFromJson(json)
    }

    private readFromJson(json: string): void {
        const dataRows: any[] = JSON.parse(json)
        const records: LocalizationRecord[] = []

        if (this.isCompactRowFormatted(dataRows)) {
            for (const dataRow of dataRows) {
                const record = new LocalizationRecord()
                record.populateFieldValuesCompact(dataRow)
                records.push(record)
            }
        } else {
            for (const dataRow of dataRows as IDataRow[]) {
                const record = new LocalizationRecord()
                record.populateFieldValues(dataRow)
                records.push(record)
            }
        }

        this.publish(records)
    }

    private isCompactRowFormatted(rows: any[]): boolean {
        return rows.length > 0 && Array.isArray(rows[0])
    }

    /** Read a table from a binary .table file. */
    public readBinarySync(filename: string): void
    {
        this.readBinaryFrom(sheetman.readAllBytes(filename))
    }

    /**
     * Read a table from binary data already in memory.
     *
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public readBinaryFrom(data: Uint8Array): void
    {
        const reader = new sheetman.LiteBinaryReader(data)
        const { rowCount, columns } = sheetman.readTableHeader(reader)

        // Built here and published at the end, so a file that turns out to be truncated - or
        // a column this build cannot read - leaves the rows already loaded exactly as they are.
        const records: LocalizationRecord[] = []
        for (let i = 0; i < rowCount; ++i)
            records.push(new LocalizationRecord())

        for (const column of columns)
        {
            const blockEnd = reader.position + column.byteLength

            switch (column.tag)
            {
                case 1:
                    sheetman.checkColumn(column, 'Localization.Index', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = records[i]
                        record._index = reader.readI32As(column.element)
                    }
                    break
                case 2:
                    sheetman.checkColumn(column, 'Localization.Key', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = records[i]
                        record._key = reader.readString()
                    }
                    break
                case 3:
                    sheetman.checkColumn(column, 'Localization.TextEn_array', sheetman.KIND_FIXED_ARRAY, 2, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = records[i]
                        record._textEnArray = []
                        for (let j = 0; j < 2; ++j)
                            record._textEnArray.push(reader.readString())
                    }
                    break
                case 4:
                    sheetman.checkColumn(column, 'Localization.TextKo_array', sheetman.KIND_FIXED_ARRAY, 2, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = records[i]
                        record._textKoArray = []
                        for (let j = 0; j < 2; ++j)
                            record._textKoArray.push(reader.readString())
                    }
                    break
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byteLength)
                    break
            }

            sheetman.checkBlockEnd(reader, column, blockEnd)
        }

        this.publish(records)
    }

    /** Index mapping. */
    /**
     * Publishes one whole load: the rows and the lookups built from them, together.
     *
     * Reading a table that is already loaded - a refresh, a patched file - used to mutate what
     * consumers were holding: the rows were appended to or emptied first, so a read that threw
     * partway left the table holding some of the new data and none of the old. Everything above
     * builds its own arrays and gets here only if it finished, and this replaces the references
     * in one step. Whoever took `records` before still has the previous load, whole.
     */
    private publish(records: LocalizationRecord[]): void {
        const recordsByIndex = new Map<number, LocalizationRecord>()

        for (const record of records)
        {
            recordsByIndex.set(record.index, record)
        }

        this._records = records
        this._recordsByIndex = recordsByIndex
    }
}
