// ------------------------------------------------------------------------------
// Generated by SheetMan. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

@file:Suppress("unused", "RedundantVisibilityModifier", "UNUSED_IMPORT")

package x

import java.io.File
import sheetman.ScbReader
import sheetman.RecordNotFoundException
import sheetman.Uuid
import sheetman.readAllBytes
import sheetman.readTableHeader
import sheetman.checkColumn
import sheetman.checkBlockEnd
import sheetman.ColumnCursor
import sheetman.ELEMENT_VARINT
import sheetman.ELEMENT_BOOL
import sheetman.ELEMENT_I32
import sheetman.ELEMENT_I64
import sheetman.ELEMENT_F32
import sheetman.ELEMENT_F64
import sheetman.ELEMENT_STRING
import sheetman.ELEMENT_UUID
import sheetman.KIND_SCALAR
import sheetman.KIND_FIXED_ARRAY
import sheetman.KIND_VAR_ARRAY
/** Every table, loaded together so cross-table references can be resolved. */
object A {
    var template: TemplateTable = TemplateTable()
        private set

    /**
     * Reads every table from basePath, then links the references between them.
     *
     * Safe to call on a loaded accessor. Every file is read into a set of its own and the references are linked among those, so nothing here is visible until all of it is: a failure part way through leaves the tables holding the load they already had, and no row ever points at a row from it.
     */
    fun readAll(basePath: String, fileExtension: String = ".scb") {
        val loadedTemplateTable = TemplateTable()
        loadedTemplateTable.read(File(basePath, "Template$fileExtension").path)

        solveCrossReferences(loadedTemplateTable)

        template = loadedTemplateTable
    }

    /**
     * Turns the stored indices into usable values, once every table is in memory.
     *
     * The tables arrive as arguments and shadow the properties of the same name, which is
     * how this resolves the load being read rather than the one already published.
     */
    private fun solveCrossReferences(template: TemplateTable) {
        // No table references another.
    }
}
