// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as path from 'path'

import { OffsetTableTable } from './tables/offset-table'
import { SecondTableTable } from './tables/second-table'

/** Tables */
export class Tables {
  /** Peroperty for table OffsetTable */
  public get offsetTable(): OffsetTableTable { return this._offsetTable }
  private _offsetTable: OffsetTableTable = new OffsetTableTable()

  /** Peroperty for table SecondTable */
  public get secondTable(): SecondTableTable { return this._secondTable }
  private _secondTable: SecondTableTable = new SecondTableTable()

  /**
   * Read all tables asynchronously.
   *
   * `fileExtension` defaults to what the JSON exporter writes. Pass a different one when the
   * data files were renamed after export.
   */
  public async readAll(basePath: string, fileExtension: string = '.json'): Promise<void> {
    const offsetTable = new OffsetTableTable()
    await offsetTable.read(path.join(basePath, `OffsetTable${fileExtension}`))
    const secondTable = new SecondTableTable()
    await secondTable.read(path.join(basePath, `SecondTable${fileExtension}`))

    this.publish(offsetTable, secondTable)
  }

  /** Read all tables synchronously. */
  public readAllSync(basePath: string, fileExtension: string = '.json'): void {
    const offsetTable = new OffsetTableTable()
    offsetTable.readSync(path.join(basePath, `OffsetTable${fileExtension}`))
    const secondTable = new SecondTableTable()
    secondTable.readSync(path.join(basePath, `SecondTable${fileExtension}`))

    this.publish(offsetTable, secondTable)
  }

  /**
   * Read all tables from the binary export.
   *
   * The counterpart of `readAllSync`, and the one to use when the data is binary: reading a
   * table on its own with `readBinarySync` leaves its references unlinked, because linking
   * needs every table. Both formats produce the same values.
   */
  public readAllBinarySync(basePath: string, fileExtension: string = '.table'): void {
    const offsetTable = new OffsetTableTable()
    offsetTable.readBinarySync(path.join(basePath, `OffsetTable${fileExtension}`))
    const secondTable = new SecondTableTable()
    secondTable.readBinarySync(path.join(basePath, `SecondTable${fileExtension}`))

    this.publish(offsetTable, secondTable)
  }

  /**
   * Publishes one whole load.
   *
   * Reading again - a refresh, a downloaded patch - loads into tables of its own and gets
   * here only once every file has been read. A failure anywhere leaves every table holding
   * what it held, which is the answer a running program wants: the data it already had, and
   * an exception saying why the new data was not taken.
   */
  private publish(offsetTable: OffsetTableTable, secondTable: SecondTableTable): void {
    this._offsetTable = offsetTable
    this._secondTable = secondTable

    this.solveCrossReferences()
  }

  /**
   * Turns the stored keys into the rows they name, once every table is in memory.
   *
   * A `foreign` column travels as the target row's primary key, so a table read on its own
   * has the key and not the row - which is why this runs from `publish` and not from a
   * table's own read. A zero means the sheet left the cell empty and is left unresolved.
   */
  private solveCrossReferences(): void {
    // No table references another.
  }
}
