// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/lite_binary_reader'

/** A type for handling rows when parsing .json. */
interface IDataRow {
    index: number
    name: string
    description: string
}

// Generated from test/fixtures/xlsx/foreign-field\foreign-field.xlsx : Refs : B2
/** Target of the field-level reference below. */
export class ItemCategoryRecord {
    /** Default constructor */
    constructor() {
    }

    /** primary index */
    public get index(): number { return this._index }
    private _index: number

    /** category name */
    public get name(): string { return this._name }
    private _name: string

    /** description */
    public get description(): string { return this._description }
    private _description: string

    /** Populate field values. */
    public populateFieldValues(dataRow: IDataRow): void {
        this._index = dataRow.index
        this._name = dataRow.name
        this._description = dataRow.description
    }

    /** Populate field values. */
    public populateFieldValuesCompact(dataRow: any[]): void {
        let offset = 0
        this._index = dataRow[offset++]
        this._name = dataRow[offset++]
        this._description = dataRow[offset++]
    }

    /** Read one record. Field order must match the exporter's. */
    public readBinary(reader: sheetman.LiteBinaryReader): void
    {
        this._index = reader.readInt32()
        this._name = reader.readString()
        this._description = reader.readString()
    }
}

// Generated from test/fixtures/xlsx/foreign-field\foreign-field.xlsx : Refs : B2
/** Target of the field-level reference below. */
export class ItemCategoryTable {
    /** Default constructor. */
    constructor() {
    }

    /** All records. */
    public get records(): ItemCategoryRecord[] { return this._records }
    private _records: ItemCategoryRecord[] = []

    // Indexing by 'index'
    public get recordsByIndex(): Map<number, ItemCategoryRecord> { return this._recordsByIndex }
    private _recordsByIndex: Map<number, ItemCategoryRecord> = new Map<number, ItemCategoryRecord>()

    /** Gets the value associated with the specified key. throw Error if not found. */
    public getByIndex(key: number): ItemCategoryRecord {
        const found = this._recordsByIndex.get(key)
        if (!found)
            throw new Error(`There is no record in table "ItemCategory" that corresponds to field "index" value ${key}`)

        return found
    }

    /** Gets the value associated with the specified key. */
    public tryGetByIndex(key: number): ItemCategoryRecord | undefined {
        return this._recordsByIndex.get(key)
    }

    /** Determines whether the table contains the specified key. */
    public containsIndex(key: number): boolean {
        return !!this._recordsByIndex.has(key)
    }

    /** Read a table from specified file. */
    public async read(filename: string): Promise<void> {
        const json = await fs.promises.readFile(filename, "utf8")
        this.readFromJson(json)
    }

    /** Read a table from specified file synchronously. */
    public readSync(filename: string): void {
        const json = fs.readFileSync(filename, "utf8")
        this.readFromJson(json)
    }

    private readFromJson(json: string): void {
        const dataRows: any[] = JSON.parse(json)
        if (this.isCompactRowFormatted(dataRows)) {
            for (const dataRow of dataRows) {
                const record = new ItemCategoryRecord()
                record.populateFieldValuesCompact(dataRow)
                this._records.push(record)
            }
        } else {
            for (const dataRow of dataRows as IDataRow[]) {
                const record = new ItemCategoryRecord()
                record.populateFieldValues(dataRow)
                this._records.push(record)
            }
        }

        this.mapping()
    }

    private isCompactRowFormatted(rows: any[]): boolean {
        return rows.length > 0 && Array.isArray(rows[0])
    }

    /** Read a table from a binary .table file. */
    public readBinarySync(filename: string): void
    {
        this.readBinaryFrom(sheetman.readAllBytes(filename))
    }

    /** Read a table from binary data already in memory. */
    public readBinaryFrom(data: Uint8Array): void
    {
        const reader = new sheetman.LiteBinaryReader(data)
        const rowCount = sheetman.readTableHeader(reader)

        for (let i = 0; i < rowCount; ++i)
        {
            const record = new ItemCategoryRecord()
            record.readBinary(reader)
            this._records.push(record)
        }

        this.mapping()
    }

    /** Index mapping. */
    private mapping(): void {
        for (const record of this._records)
        {
            this._recordsByIndex.set(record.index, record)
        }
    }
}

