// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/lite_binary_reader'

// Automatically import to handle external type references.
import { ItemCategoryRecord } from './ItemCategory'
import { Grade } from '../enums/Grade'
import { SkillType } from '../enums/SkillType'

/** A type for handling rows when parsing .json. */
interface IDataRow {
    index: number
    name: string
    categoryId: ItemCategoryRecord
    gradeField: Grade
    skillField: SkillType
    description: string
    price: number
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Refs : I2
/** References ItemCategory by record. */
export class ItemRecord {
    /** Default constructor */
    constructor() {
    }

    /** primary index */
    public get index(): number { return this._index }

    /** item name */
    public get name(): string { return this._name }

    /** owning category */
    public get categoryId(): ItemCategoryRecord { return this._categoryId }

    /** item grade */
    public get gradeField(): Grade { return this._gradeField }

    /** granted skill */
    public get skillField(): SkillType { return this._skillField }

    /** shop blurb */
    public get description(): string { return this._description }

    /** shop price */
    public get price(): number { return this._price }

    public setReference_categoryId_INTERNAL(value: ItemCategoryRecord) { this._categoryId = value; }

    public _index: number = 0
    public _name: string = ''
    public _categoryId: ItemCategoryRecord
    public _categoryId_ItemCategory_index: number = 0
    public _categoryId_F: boolean = false
    public _gradeField: Grade = 0 as Grade
    public _skillField: SkillType = 0 as SkillType
    public _description: string = ''
    public _price: number = 0

    /** Populate field values. */
    public populateFieldValues(dataRow: IDataRow): void {
        this._index = dataRow.index
        this._name = dataRow.name
        this._categoryId = dataRow.categoryId
        this._gradeField = dataRow.gradeField
        this._skillField = dataRow.skillField
        this._description = dataRow.description
        this._price = dataRow.price
    }

    /** Populate field values. */
    public populateFieldValuesCompact(dataRow: any[]): void {
        let offset = 0
        this._index = dataRow[offset++]
        this._name = dataRow[offset++]
        this._categoryId = dataRow[offset++]
        this._gradeField = dataRow[offset++]
        this._skillField = dataRow[offset++]
        this._description = dataRow[offset++]
        this._price = dataRow[offset++]
    }
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Refs : I2
/** References ItemCategory by record. */
export class ItemTable {
    /** Default constructor. */
    constructor() {
    }

    /** All records. */
    public get records(): ItemRecord[] { return this._records }
    private _records: ItemRecord[] = []

    // Indexing by 'index'
    public get recordsByIndex(): Map<number, ItemRecord> { return this._recordsByIndex }
    private _recordsByIndex: Map<number, ItemRecord> = new Map<number, ItemRecord>()

    /** Gets the value associated with the specified key. throw Error if not found. */
    public getByIndex(key: number): ItemRecord {
        const found = this._recordsByIndex.get(key)
        if (!found)
            throw new Error(`There is no record in table "Item" that corresponds to field "index" value ${key}`)

        return found
    }

    /** Gets the value associated with the specified key. */
    public tryGetByIndex(key: number): ItemRecord | undefined {
        return this._recordsByIndex.get(key)
    }

    /** Determines whether the table contains the specified key. */
    public containsIndex(key: number): boolean {
        return !!this._recordsByIndex.has(key)
    }

    /** Read a table from specified file. */
    public async read(filename: string): Promise<void> {
        const json = await fs.promises.readFile(filename, "utf8")
        this.readFromJson(json)
    }

    /** Read a table from specified file synchronously. */
    public readSync(filename: string): void {
        const json = fs.readFileSync(filename, "utf8")
        this.readFromJson(json)
    }

    private readFromJson(json: string): void {
        const dataRows: any[] = JSON.parse(json)
        if (this.isCompactRowFormatted(dataRows)) {
            for (const dataRow of dataRows) {
                const record = new ItemRecord()
                record.populateFieldValuesCompact(dataRow)
                this._records.push(record)
            }
        } else {
            for (const dataRow of dataRows as IDataRow[]) {
                const record = new ItemRecord()
                record.populateFieldValues(dataRow)
                this._records.push(record)
            }
        }

        this.mapping()
    }

    private isCompactRowFormatted(rows: any[]): boolean {
        return rows.length > 0 && Array.isArray(rows[0])
    }

    /** Read a table from a binary .table file. */
    public readBinarySync(filename: string): void
    {
        this.readBinaryFrom(sheetman.readAllBytes(filename))
    }

    /**
     * Read a table from binary data already in memory.
     *
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public readBinaryFrom(data: Uint8Array): void
    {
        const reader = new sheetman.LiteBinaryReader(data)
        const { rowCount, columns } = sheetman.readTableHeader(reader)

        this._records = []
        for (let i = 0; i < rowCount; ++i)
            this._records.push(new ItemRecord())

        for (const column of columns)
        {
            const blockEnd = reader.position + column.byteLength

            switch (column.tag)
            {
                case 1:
                    sheetman.checkColumn(column, 'Item.Index', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._index = reader.readI32As(column.element)
                    }
                    break
                case 2:
                    sheetman.checkColumn(column, 'Item.Name', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._name = reader.readString()
                    }
                    break
                case 3:
                    sheetman.checkColumn(column, 'Item.CategoryId', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._categoryId_ItemCategory_index = reader.readInt32()
                    }
                    break
                case 4:
                    sheetman.checkColumn(column, 'Item.GradeField', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._gradeField = reader.readEnum() as Grade
                    }
                    break
                case 5:
                    sheetman.checkColumn(column, 'Item.SkillField', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._skillField = reader.readEnum() as SkillType
                    }
                    break
                case 6:
                    sheetman.checkColumn(column, 'Item.Description', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._description = reader.readString()
                    }
                    break
                case 7:
                    sheetman.checkColumn(column, 'Item.Price', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._price = reader.readI32As(column.element)
                    }
                    break
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byteLength)
                    break
            }

            sheetman.checkBlockEnd(reader, column, blockEnd)
        }

        this.mapping()
    }

    /** Index mapping. */
    private mapping(): void {
        for (const record of this._records)
        {
            this._recordsByIndex.set(record.index, record)
        }
    }
}
