// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as sheetman from '../sheetman/lite_binary_reader'

/** A type for handling rows when parsing .json. */
interface IDataRow {
    index: number
    key: string
    textEnArray: string[]
    textKoArray: string[]
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Serial : B2
/** Trailing-number columns collapse into arrays. */
export class LocalizationRecord {
    /** Default constructor */
    constructor() {
    }

    /** primary index */
    public get index(): number { return this._index }
    public _index: number = 0

    /** lookup key */
    public get key(): string { return this._key }
    public _key: string = ''

    /** english text 1 */
    public get textEnArray(): string[] { return this._textEnArray }
    public static readonly textEnArray_N = 2
    public _textEnArray: string[] = []

    /** korean text 1 */
    public get textKoArray(): string[] { return this._textKoArray }
    public static readonly textKoArray_N = 2
    public _textKoArray: string[] = []

    /** Populate field values. */
    public populateFieldValues(dataRow: IDataRow): void {
        this._index = dataRow.index
        this._key = dataRow.key
        this._textEnArray = dataRow.textEnArray
        this._textKoArray = dataRow.textKoArray
    }

    /** Populate field values. */
    public populateFieldValuesCompact(dataRow: any[]): void {
        let offset = 0
        this._index = dataRow[offset++]
        this._key = dataRow[offset++]
        this._textEnArray = dataRow.slice(offset, offset + 2)
        offset += 2
        this._textKoArray = dataRow.slice(offset, offset + 2)
        offset += 2
    }
}

// Generated from test/fixtures/xlsx/core\core.xlsx : Serial : B2
/** Trailing-number columns collapse into arrays. */
export class LocalizationTable {
    /** Default constructor. */
    constructor() {
    }

    /** All records. */
    public get records(): LocalizationRecord[] { return this._records }
    private _records: LocalizationRecord[] = []

    // Indexing by 'index'
    public get recordsByIndex(): Map<number, LocalizationRecord> { return this._recordsByIndex }
    private _recordsByIndex: Map<number, LocalizationRecord> = new Map<number, LocalizationRecord>()

    /** Gets the value associated with the specified key. throw Error if not found. */
    public getByIndex(key: number): LocalizationRecord {
        const found = this._recordsByIndex.get(key)
        if (!found)
            throw new Error(`There is no record in table "Localization" that corresponds to field "index" value ${key}`)

        return found
    }

    /** Gets the value associated with the specified key. */
    public tryGetByIndex(key: number): LocalizationRecord | undefined {
        return this._recordsByIndex.get(key)
    }

    /** Determines whether the table contains the specified key. */
    public containsIndex(key: number): boolean {
        return !!this._recordsByIndex.has(key)
    }

    /** Read a table from specified file. */
    public async read(filename: string): Promise<void> {
        const json = await fs.promises.readFile(filename, "utf8")
        this.readFromJson(json)
    }

    /** Read a table from specified file synchronously. */
    public readSync(filename: string): void {
        const json = fs.readFileSync(filename, "utf8")
        this.readFromJson(json)
    }

    private readFromJson(json: string): void {
        const dataRows: any[] = JSON.parse(json)
        if (this.isCompactRowFormatted(dataRows)) {
            for (const dataRow of dataRows) {
                const record = new LocalizationRecord()
                record.populateFieldValuesCompact(dataRow)
                this._records.push(record)
            }
        } else {
            for (const dataRow of dataRows as IDataRow[]) {
                const record = new LocalizationRecord()
                record.populateFieldValues(dataRow)
                this._records.push(record)
            }
        }

        this.mapping()
    }

    private isCompactRowFormatted(rows: any[]): boolean {
        return rows.length > 0 && Array.isArray(rows[0])
    }

    /** Read a table from a binary .table file. */
    public readBinarySync(filename: string): void
    {
        this.readBinaryFrom(sheetman.readAllBytes(filename))
    }

    /**
     * Read a table from binary data already in memory.
     *
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public readBinaryFrom(data: Uint8Array): void
    {
        const reader = new sheetman.LiteBinaryReader(data)
        const { rowCount, columns } = sheetman.readTableHeader(reader)

        this._records = []
        for (let i = 0; i < rowCount; ++i)
            this._records.push(new LocalizationRecord())

        for (const column of columns)
        {
            const blockEnd = reader.position + column.byteLength

            switch (column.tag)
            {
                case 1:
                    sheetman.checkColumn(column, 'Localization.Index', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_I32, sheetman.ELEMENT_VARINT])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._index = reader.readI32As(column.element)
                    }
                    break
                case 2:
                    sheetman.checkColumn(column, 'Localization.Key', sheetman.KIND_SCALAR, 1, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._key = reader.readString()
                    }
                    break
                case 3:
                    sheetman.checkColumn(column, 'Localization.TextEn_array', sheetman.KIND_FIXED_ARRAY, 2, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._textEnArray = []
                        for (let j = 0; j < 2; ++j)
                            record._textEnArray.push(reader.readString())
                    }
                    break
                case 4:
                    sheetman.checkColumn(column, 'Localization.TextKo_array', sheetman.KIND_FIXED_ARRAY, 2, [sheetman.ELEMENT_STRING])
                    for (let i = 0; i < rowCount; ++i)
                    {
                        const record = this._records[i]
                        record._textKoArray = []
                        for (let j = 0; j < 2; ++j)
                            record._textKoArray.push(reader.readString())
                    }
                    break
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byteLength)
                    break
            }

            sheetman.checkBlockEnd(reader, column, blockEnd)
        }

        this.mapping()
    }

    /** Index mapping. */
    private mapping(): void {
        for (const record of this._records)
        {
            this._recordsByIndex.set(record.index, record)
        }
    }
}
