// ------------------------------------------------------------------------------
// Generated by SheetMan. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

use std::path::Path;
use crate::sheetman;
use crate::template_table::TemplateTable;

/// Every table, loaded together.
#[derive(Clone, Debug, Default)]
pub struct Tables {
    pub template: TemplateTable,
}

impl Tables {
    /// Reads every table from `base_path`.
    ///
    /// The data files are expected to carry the extension the recipe told the exporter to
    /// write. Use `read_all_with_extension` to name a different one.
    pub fn read_all(&mut self, base_path: &Path) -> sheetman::Result<()> {
        self.read_all_with_extension(base_path, ".scb")
    }

    /// The same, for data files that carry some other extension.
    ///
    /// Safe to call on a loaded `Tables`. Every file is read into a set of its own, so `?`
    /// on an unreadable one returns before anything is replaced and leaves the tables
    /// holding the load they already had.
    pub fn read_all_with_extension(
        &mut self, base_path: &Path, file_extension: &str) -> sheetman::Result<()> {
        let mut loaded = Tables::default();

        loaded.template.read(
            &base_path.join(format!("Template{}", file_extension)))?;

        *self = loaded;

        Ok(())
    }
}
