// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------


// Automatically import to handle external type references.
import { Grade } from '../enums/Grade'

// Generated from test/fixtures/xlsx/core\core.xlsx : Consts : B2
/** Assorted tuning constants. */
export class GameConfig {
    /** level cap */
    public static readonly maxLevel: number = 100

    /** gold granted to new accounts */
    public static readonly startGold: bigint = 1000n

    /** base drop rate */
    public static readonly dropRate: number = 0.25

    /** whether debug hooks are active */
    public static readonly debugMode: boolean = false

    /** grade assigned when unspecified */
    public static readonly defaultGrade: Grade = Grade.Rare
}

