// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY SheetMan.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef SHEETMAN_GENERATED_A_TEMPLATE_H
#define SHEETMAN_GENERATED_A_TEMPLATE_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "sheetman/scb_reader.h"
#include "A_forward.h"

namespace x {
// Generated from test/fixtures/xlsx/reserved-words/reserved-words.xlsx : Data : B2
/// Named after a C++ keyword.
struct TemplateRecord {
  /// primary index
  std::int32_t index = 0;
  /// class: keyword in C++ and C#
  std::string sm_class;
  /// int: keyword in C++ and C#
  std::int32_t sm_int = 0;
  /// delete: keyword in C++
  bool sm_delete = false;
  /// operator: keyword in C++, and a secondary index
  std::string sm_operator;
  /// namespace: keyword in C++ and C#
  std::string sm_namespace;
  /// constructor: special member in TypeScript
  std::string constructor;
  /// function: keyword in TypeScript
  std::string function;
};

/// Named after a C++ keyword.
class TemplateTable {
 public:
  const std::vector<TemplateRecord>& records() const { return records_; }

  /// The row with this Index, or nullptr when the table has none.
  ///
  /// The lookup to reach for when a missing row is an ordinary answer - an optional
  /// reference, a key that came from user input.
  const TemplateRecord* find_by_index(std::int32_t key) const {
    const auto it = by_index_.find(key);
    return it == by_index_.end() ? nullptr : &records_[it->second];
  }

  /// The row with this Index, or a thrown exception naming what was missing.
  ///
  /// For a key that has to be there - one from another table, or a constant. The name says
  /// it throws, because a caller reading `get_by_index(key)->name` at a glance
  /// cannot otherwise tell whether the next line is a null check or a catch.
  const TemplateRecord& get_by_index_or_throw(std::int32_t key) const {
    const TemplateRecord* found = find_by_index(key);

    if (found == nullptr) {
      throw sheetman::RecordNotFound(
        std::string("there is no record in table `Template` that corresponds to "
                    "field `Index` value ") + std::to_string(key));
    }

    return *found;
  }

  /// Whether the table holds a row with this Index.
  bool contains_index(std::int32_t key) const {
    return by_index_.find(key) != by_index_.end();
  }

  /// The row with this Operator, or nullptr when the table has none.
  ///
  /// The lookup to reach for when a missing row is an ordinary answer - an optional
  /// reference, a key that came from user input.
  const TemplateRecord* find_by_operator(const std::string& key) const {
    const auto it = by_operator_.find(key);
    return it == by_operator_.end() ? nullptr : &records_[it->second];
  }

  /// The row with this Operator, or a thrown exception naming what was missing.
  ///
  /// For a key that has to be there - one from another table, or a constant. The name says
  /// it throws, because a caller reading `get_by_operator(key)->name` at a glance
  /// cannot otherwise tell whether the next line is a null check or a catch.
  const TemplateRecord& get_by_operator_or_throw(const std::string& key) const {
    const TemplateRecord* found = find_by_operator(key);

    if (found == nullptr) {
      throw sheetman::RecordNotFound(
        std::string("there is no record in table `Template` that corresponds to "
                    "field `Operator` value ") + key);
    }

    return *found;
  }

  /// Whether the table holds a row with this Operator.
  bool contains_operator(const std::string& key) const {
    return by_operator_.find(key) != by_operator_.end();
  }

  /// Loads the table from a .scb file written by SheetMan.
  void read(const std::string& filename) {
    const std::vector<std::uint8_t> buffer = sheetman::read_all_bytes(filename);
    sheetman::ScbReader reader(buffer);

    // Column by column, matched by tag rather than position: a column this build
    // does not know is skipped by its block length, and one whose type changed
    // incompatibly fails naming the field.
    const sheetman::Header header = sheetman::read_table_header(reader);
    const std::size_t row_count = static_cast<std::size_t>(header.row_count);

    // Read into storage of its own and swapped in at the end: reading a table that is
    // already loaded is a refresh, and one that throws part way through - a truncated
    // file, a column this build cannot read - has to leave the rows already there.
    std::vector<TemplateRecord> records;
    records.resize(row_count);

    for (const sheetman::Column& column : header.columns) {
      const std::size_t block_end = reader.position() + static_cast<std::size_t>(column.byte_length);

      switch (column.tag) {
        case 1: {
          sheetman::check_column(column, "Template.Index", sheetman::kKindScalar, 1, {sheetman::kElementI32, sheetman::kElementVarint});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read_i32_as(column.element, record.index);
          }
          break;
        }
        case 2: {
          sheetman::check_column(column, "Template.Class", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.sm_class);
          }
          break;
        }
        case 3: {
          sheetman::check_column(column, "Template.Int", sheetman::kKindScalar, 1, {sheetman::kElementI32, sheetman::kElementVarint});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read_i32_as(column.element, record.sm_int);
          }
          break;
        }
        case 4: {
          sheetman::check_column(column, "Template.Delete", sheetman::kKindScalar, 1, {sheetman::kElementBool});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.sm_delete);
          }
          break;
        }
        case 5: {
          sheetman::check_column(column, "Template.Operator", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.sm_operator);
          }
          break;
        }
        case 6: {
          sheetman::check_column(column, "Template.Namespace", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.sm_namespace);
          }
          break;
        }
        case 7: {
          sheetman::check_column(column, "Template.Constructor", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.constructor);
          }
          break;
        }
        case 8: {
          sheetman::check_column(column, "Template.Function", sheetman::kKindScalar, 1, {sheetman::kElementString});
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            reader.read(record.function);
          }
          break;
        }
        default:
          // A column added after this code was generated.
          reader.skip(column.byte_length);
          break;
      }

      sheetman::check_block_end(reader, column, block_end);
    }

    publish(std::move(records));
  }

 private:
  friend class Tables;

  /// One whole load, in place of the previous one.
  ///
  /// The indexes are built here rather than by the caller, because they have to arrive
  /// with the rows: a table holding this load's rows and the last one's index would
  /// answer a lookup with a row that is no longer at that position.
  void publish(std::vector<TemplateRecord>&& records) {
    std::unordered_map<std::int32_t, std::size_t> index_map;
    index_map.reserve(records.size());
    for (std::size_t i = 0; i < records.size(); ++i) {
      index_map.emplace(records[i].index, i);
    }

    std::unordered_map<std::string, std::size_t> operator_map;
    operator_map.reserve(records.size());
    for (std::size_t i = 0; i < records.size(); ++i) {
      operator_map.emplace(records[i].sm_operator, i);
    }

    records_ = std::move(records);
    by_index_ = std::move(index_map);
    by_operator_ = std::move(operator_map);
  }

  std::vector<TemplateRecord> records_;
  std::unordered_map<std::int32_t, std::size_t> by_index_;
  std::unordered_map<std::string, std::size_t> by_operator_;
};

}  // namespace x

#endif  // SHEETMAN_GENERATED_A_TEMPLATE_H
