using System;
using System.IO;
using Xunit;

namespace SheetMan.Tests
{
    /// <summary>
    /// Removing the generated files a run no longer produces.
    ///
    /// Needed because a target writes a file per table, and nothing ever deleted one. Take a
    /// table out of the sheets and its file stays where it was, still naming types nothing
    /// declares any more - untidy at best and a compile error at worst. TypeScript has written
    /// per-table files from the start and has had this the whole time.
    ///
    /// What is removed is not "everything the run did not write". It is every file that says
    /// `Generated by SheetMan` in its own header and that the run did not write, so the marker
    /// is the permission - and the test that matters most here is the one proving a
    /// hand-written file in the same directory survives.
    ///
    /// These convert through <see cref="Reconvert"/> rather than
    /// <see cref="SheetManRunner.Convert"/>. That one deletes the whole output tree first, so
    /// every file planted here would vanish whether the sweep worked or not - which is exactly
    /// how the first version of these tests passed while measuring nothing.
    /// </summary>
    public class SweepTests
    {
        private const string Scenario = "core";

        private static string TypescriptDir => Path.Combine(RepoLayout.OutputDir(Scenario), "typescript");

        /// <summary>A first conversion, from a clean tree.</summary>
        private static void Convert()
        {
            var result = SheetManRunner.Convert(Scenario);

            Assert.True(result.Succeeded, $"Conversion failed.{Environment.NewLine}{result.Describe()}");
        }

        /// <summary>
        /// A second conversion over the output of the first, which is what a person running the
        /// tool twice does and the only way to see the sweep at all.
        /// </summary>
        private static void Reconvert()
        {
            var result = SheetManRunner.Invoke("--recipe", RepoLayout.Recipe(Scenario), "--debug");

            Assert.True(result.Succeeded, $"Reconversion failed.{Environment.NewLine}{result.Describe()}");
        }

        [Fact]
        public void A_generated_file_the_run_no_longer_writes_is_removed()
        {
            Convert();

            // A table that used to exist: same header, same directory, not written any more.
            string stale = Path.Combine(TypescriptDir, "tables", "DeletedTable.ts");

            File.WriteAllText(stale,
                "// Generated by SheetMan. DO NOT EDIT." + Environment.NewLine +
                "export class DeletedTableRecord {}" + Environment.NewLine);

            Reconvert();

            Assert.False(File.Exists(stale),
                "A generated file the conversion no longer produces was left behind.");
        }

        /// <summary>
        /// And a file this tool did not write is not touched, whatever it is called and
        /// wherever it sits.
        ///
        /// This is the one that decides whether sweeping can be on by default. A sweep that
        /// emptied the directory would be a data-loss bug waiting for somebody to point a
        /// target at a folder they also keep their own code in.
        /// </summary>
        [Fact]
        public void A_file_this_tool_did_not_write_is_left_alone()
        {
            Convert();

            string mine = Path.Combine(TypescriptDir, "tables", "MyOwnHelper.ts");
            const string content = "// Mine, hand written.\nexport const answer = 42;\n";

            File.WriteAllText(mine, content);

            Reconvert();

            Assert.True(File.Exists(mine), "A hand-written file was deleted by the sweep.");
            Assert.Equal(content.Replace("\r\n", "\n"), File.ReadAllText(mine).Replace("\r\n", "\n"));
        }

        /// <summary>
        /// The files the conversion does write are still there afterwards.
        ///
        /// The sweep runs after the commit and skips everything the run wrote, but "skips
        /// everything it wrote" is exactly the sort of claim worth one assertion: a sweep that
        /// deleted its own output would leave an empty directory and a passing conversion.
        /// </summary>
        [Fact]
        public void The_files_the_run_writes_survive_it()
        {
            Convert();
            Reconvert();

            foreach (var expected in new[]
                     {
                         Path.Combine("tables", "Item.ts"),
                         Path.Combine("enums", "Grade.ts"),
                         Path.Combine("constants", "game-config.ts"),
                         "index.ts",
                         Path.Combine("sheetman", "lite-binary-reader.ts"),
                     })
            {
                Assert.True(File.Exists(Path.Combine(TypescriptDir, expected)),
                    $"{expected} is missing after a second conversion.");
            }
        }

        /// <summary>
        /// `Sweep: false` leaves a stale file where it is.
        ///
        /// The option exists for a consumer who edits the generated output. Checked because an
        /// option nothing exercises is a guess, and this one is the difference between a tool
        /// that deletes your work and one that does not.
        /// </summary>
        [Fact]
        public void Sweeping_can_be_turned_off()
        {
            Convert();

            string stale = Path.Combine(TypescriptDir, "tables", "KeptOnPurpose.ts");

            File.WriteAllText(stale,
                "// Generated by SheetMan. DO NOT EDIT." + Environment.NewLine +
                "export class KeptOnPurposeRecord {}" + Environment.NewLine);

            var result = SheetManRunner.Invoke(
                "--recipe", RepoLayout.Recipe("core-no-sweep"), "--debug");

            Assert.True(result.Succeeded, $"Conversion failed.{Environment.NewLine}{result.Describe()}");

            Assert.True(File.Exists(stale),
                "`Sweep: false` did not stop the stale file from being removed.");

            File.Delete(stale);
        }
    }
}
