// ------------------------------------------------------------------------------
// Written here by SheetMan. Generated by SheetMan. DO NOT EDIT.
//
// The runtime, copied in beside the generated code so the output is
// self-contained. Edit it in the SheetMan repository, not here: this file is
// rewritten on every run, and the header above is what lets a later run remove
// it if it ever moves.
// ------------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// SheetMan Scb reader for Unreal Engine 4.x and 5.x.
//
// Reads the .scb files produced by SheetMan's binary exporter. The format is
// defined by the C# writer in src/Exporters/ScbWriter.cs, and this is a
// deliberate re-implementation of the reading half of it:
//
//   fixed8      one byte
//   fixed32     four bytes, little endian
//   fixed64     eight bytes, little endian
//   varint32    seven bits per byte, high bit set while more bytes follow,
//               at most five bytes
//   counter32   zig-zag encoded int32 written as a varint32, so small values
//               of either sign cost one byte
//   string      counter32 byte length, then that many UTF-8 bytes
//   int32/uint32   fixed32
//   int64          fixed64
//   bool           fixed8, zero meaning false
//   float/double   fixed32 / fixed64 holding the IEEE-754 bit pattern
//   datetime       fixed64 of .NET ticks: 100 ns units since 0001-01-01
//   timespan       fixed64 of .NET ticks
//   uuid           sixteen bytes in .NET Guid layout
//
// A separate reader from lib/cpp rather than that one wrapped, for two reasons.
//
// The engine already has every type this needs. Going through std::string and a
// SheetMan Uuid struct meant two allocations for every string cell and a text
// parse for every uuid - building what FString and FGuid already are, only to
// convert back.
//
// And an Unreal module is built with exceptions disabled by default, so the
// throwing reader could not report a malformed file: the throw was not a
// recoverable failure but a termination, in a function whose signature promised
// a bool. Failure here is a sticky flag instead.
//
// Nothing from the standard library appears below. Nothing outside Core is
// needed - not even for reading the file, which the generated accessor does with
// FFileHelper.
// ---------------------------------------------------------------------------

#pragma once

#include "CoreMinimal.h"

namespace SheetMan
{
    /**
     * Version stamped at the head of every table file by the exporter. 102 replaced 101
     * outright - a descriptor gained its encoding byte - before any 101 file had shipped.
     */
    static constexpr uint32 BinaryFileFormatVersion = 102;

    // The wire element types and kinds, as a column descriptor spells them.
    static constexpr uint8 ElementVarint = 0;
    static constexpr uint8 ElementBool = 1;
    static constexpr uint8 ElementI32 = 2;
    static constexpr uint8 ElementI64 = 3;
    static constexpr uint8 ElementF32 = 4;
    static constexpr uint8 ElementF64 = 5;
    static constexpr uint8 ElementString = 6;
    static constexpr uint8 ElementUuid = 7;

    /**
     * One element type as a bit, so the set a member accepts is one argument.
     *
     * A set rather than a container because the generated code has to spell it inline, and
     * an engine module has no business reaching for std::initializer_list to do it.
     */
    constexpr uint32 ElementMask(uint8 Element) { return 1u << Element; }

    static constexpr uint8 KindScalar = 0;
    static constexpr uint8 KindFixedArray = 1;
    static constexpr uint8 KindVarArray = 2;

    // How a block's values are laid out. Raw is the layout 101 had; the others compress
    // a column that repeats itself. spec/scb-v102-column-encoding.md is the contract.
    static constexpr uint8 EncodingRaw = 0;
    static constexpr uint8 EncodingVarint = 1;
    static constexpr uint8 EncodingDelta = 2;
    static constexpr uint8 EncodingRle = 3;
    static constexpr uint8 EncodingDeltaRle = 4;
    static constexpr uint8 EncodingDict = 5;
    static constexpr uint8 EncodingDictRle = 6;

    /** One column as the file describes it. */
    struct FSheetManColumn
    {
        /** What identifies the column, instead of its position. */
        int32 Tag = 0;

        uint8 Element = 0;
        uint8 Kind = 0;

        /** How the block's values are laid out: one of the Encoding* constants. */
        uint8 Encoding = 0;

        /** Elements per row: 1 for a scalar, N for a fixed array, 0 for a variable one. */
        int32 Count = 0;

        /** Total bytes of the column block - what a skip advances by. */
        int32 ByteLength = 0;
    };

    /** A parsed header: the row count and the column descriptors that follow it. */
    struct FSheetManTableHeader
    {
        int32 RowCount = 0;
        TArray<FSheetManColumn> Columns;
    };

    /**
     * Sequential reader over a table file's bytes.
     *
     * Non-owning: the buffer has to outlive the reader.
     *
     * Failure is sticky. The first read that runs out of data records why and every
     * read after it does nothing, which is what lets the generated code read a
     * record's twenty fields in a row and ask once, at the end, whether any of it
     * worked. Values left behind by a failed read keep whatever they held, so a
     * half-read record holds defaults rather than debris.
     */
    class FSheetManBinaryReader
    {
    public:
        explicit FSheetManBinaryReader(TArrayView<const uint8> InData)
            : Data(InData)
        {
        }

        /** Whether any read so far has run out of data or found the file malformed. */
        bool HasFailed() const { return bFailed; }

        /** Why the first failure happened. Empty while nothing has gone wrong. */
        const FString& GetError() const { return Error; }

        int32 Tell() const { return Position; }
        int32 Remaining() const { return Data.Num() - Position; }

        // ------------------------------------------------------------- primitives

        bool Read(bool& Out)
        {
            uint8 Byte = 0;
            if (!ReadFixed8(Byte))
            {
                return false;
            }

            Out = Byte != 0;
            return true;
        }

        bool Read(int32& Out)
        {
            uint32 Bits = 0;
            if (!ReadFixed32(Bits))
            {
                return false;
            }

            Out = static_cast<int32>(Bits);
            return true;
        }

        bool Read(uint32& Out) { return ReadFixed32(Out); }

        /** A single byte as itself: the wire byte in a column descriptor. */
        bool Read(uint8& Out) { return ReadFixed8(Out); }

        bool Read(int64& Out)
        {
            uint64 Bits = 0;
            if (!ReadFixed64(Bits))
            {
                return false;
            }

            Out = static_cast<int64>(Bits);
            return true;
        }

        bool Read(float& Out)
        {
            uint32 Bits = 0;
            if (!ReadFixed32(Bits))
            {
                return false;
            }

            FMemory::Memcpy(&Out, &Bits, sizeof(Out));
            return true;
        }

        bool Read(double& Out)
        {
            uint64 Bits = 0;
            if (!ReadFixed64(Bits))
            {
                return false;
            }

            FMemory::Memcpy(&Out, &Bits, sizeof(Out));
            return true;
        }

        /**
         * UTF-8 bytes straight into an FString.
         *
         * FUTF8ToTCHAR with an explicit length rather than the UTF8_TO_TCHAR macro:
         * the bytes in a table file are not null terminated, and the macro requires
         * that they are.
         *
         * The cast is to UTF8CHAR rather than ANSICHAR because UE 5.3 made UTF8CHAR a
         * distinct type; before that the two were the same, so this spelling is the one
         * that compiles on 4.x and 5.x alike.
         */
        bool Read(FString& Out)
        {
            int32 Length = 0;
            if (!ReadCounter32(Length))
            {
                return false;
            }

            if (Length < 0)
            {
                return Fail(TEXT("string length is negative"));
            }

            if (!Require(Length))
            {
                return false;
            }

            if (Length == 0)
            {
                Out.Reset();
                Position += Length;
                return true;
            }

            const FUTF8ToTCHAR Converted(
                reinterpret_cast<const UTF8CHAR*>(Data.GetData() + Position), Length);

            Out = FString(Converted.Length(), Converted.Get());

            Position += Length;
            return true;
        }

        /**
         * Ticks into an FDateTime.
         *
         * Both sides count 100 nanosecond ticks from 0001-01-01, so there is nothing to
         * convert - only to check. A tick count outside the range FDateTime accepts
         * would assert inside the engine on some versions, which is exactly the kind of
         * failure this reader exists to turn into a message.
         */
        bool Read(FDateTime& Out)
        {
            int64 Ticks = 0;
            if (!Read(Ticks))
            {
                return false;
            }

            if (Ticks < 0 || Ticks > FDateTime::MaxValue().GetTicks())
            {
                return Fail(FString::Printf(
                    TEXT("datetime tick count %lld is outside what FDateTime can hold"), Ticks));
            }

            Out = FDateTime(Ticks);
            return true;
        }

        /** Ticks into an FTimespan. Signed, and every int64 is a valid one. */
        bool Read(FTimespan& Out)
        {
            int64 Ticks = 0;
            if (!Read(Ticks))
            {
                return false;
            }

            Out = FTimespan(Ticks);
            return true;
        }

        /**
         * Sixteen bytes in .NET's Guid layout, straight into an FGuid.
         *
         * That layout is not plain big-endian: the first three components are little
         * endian and the trailing eight bytes are in order. FGuid's four integers are
         * laid out so that A is the first component, B holds the second and third, and
         * C and D hold the remaining eight bytes big-endian - so the same text comes
         * out of FGuid::ToString as out of .NET's Guid.ToString("D").
         *
         * Assembled rather than parsed. The previous route built a 36 character string
         * and handed it to FGuid::Parse, for sixteen bytes that were already there.
         */
        bool Read(FGuid& Out)
        {
            if (!Require(16))
            {
                return false;
            }

            const uint8* Bytes = Data.GetData() + Position;

            const uint32 A = static_cast<uint32>(Bytes[0])
                           | static_cast<uint32>(Bytes[1]) << 8
                           | static_cast<uint32>(Bytes[2]) << 16
                           | static_cast<uint32>(Bytes[3]) << 24;

            const uint32 Data2 = static_cast<uint32>(Bytes[4]) | static_cast<uint32>(Bytes[5]) << 8;
            const uint32 Data3 = static_cast<uint32>(Bytes[6]) | static_cast<uint32>(Bytes[7]) << 8;

            const uint32 B = Data2 << 16 | Data3;

            const uint32 C = static_cast<uint32>(Bytes[8]) << 24
                           | static_cast<uint32>(Bytes[9]) << 16
                           | static_cast<uint32>(Bytes[10]) << 8
                           | static_cast<uint32>(Bytes[11]);

            const uint32 D = static_cast<uint32>(Bytes[12]) << 24
                           | static_cast<uint32>(Bytes[13]) << 16
                           | static_cast<uint32>(Bytes[14]) << 8
                           | static_cast<uint32>(Bytes[15]);

            Out = FGuid(A, B, C, D);

            Position += 16;
            return true;
        }

        /** An enum, as the zig-zag encoded int32 the exporter writes. */
        template <typename TEnum>
        bool ReadEnum(TEnum& Out)
        {
            int32 Value = 0;
            if (!ReadCounter32(Value))
            {
                return false;
            }

            Out = static_cast<TEnum>(Value);
            return true;
        }

        /**
         * The element count in front of a variable length array.
         *
         * Public because the generated code reads it directly to size the TArray, and
         * because a caller wanting to bound that allocation needs to see the number
         * before trusting it.
         */
        bool ReadCounter32(int32& Out)
        {
            uint32 Encoded = 0;
            if (!ReadVarint32(Encoded))
            {
                return false;
            }

            Out = static_cast<int32>(Encoded >> 1) ^ -static_cast<int32>(Encoded & 1);
            return true;
        }

        /**
         * Records a reason of the caller's own and fails the reader.
         *
         * For the column checks, which find the file disagreeing with the generated code
         * rather than running out of it. Sticky like every other failure, and always
         * returns false so it reads as `return Reader.FailWith(...)`.
         */
        bool FailWith(const FString& Why) { return Fail(Why); }

        /**
         * Advances past bytes without interpreting them: a whole column block this build
         * has no member for.
         *
         * One call is the entirety of skipping, because a column declares its own length.
         * That is what the column-oriented layout buys - there is no per-type skip to get
         * wrong, and thirteen readers get it right the same way.
         */
        bool Skip(int32 ByteCount)
        {
            if (bFailed)
            {
                return false;
            }

            if (ByteCount < 0 || ByteCount > Remaining())
            {
                return Fail(FString::Printf(TEXT("cannot skip %d bytes with %d remaining"),
                    ByteCount, Remaining()));
            }

            Position += ByteCount;
            return true;
        }

        // Promotions: a member reading a file element narrower than itself. Only the
        // mathematically lossless directions exist; CheckColumn already refused the rest.
        //
        // Everything else forwards to the overload for its own type, so the generated code
        // has one spelling for every field rather than a promoted spelling and a plain one.

        template <typename T>
        bool ReadAs(uint8 Element, T& Out)
        {
            (void)Element;
            return Read(Out);
        }

        /** An int32 member, from i32 or varint. */
        bool ReadAs(uint8 Element, int32& Out)
        {
            return Element == ElementI32 ? Read(Out) : ReadCounter32(Out);
        }

        /** An int64 member, from i64, i32 or varint. */
        bool ReadAs(uint8 Element, int64& Out)
        {
            if (Element == ElementI64)
            {
                return Read(Out);
            }

            int32 Narrower = 0;
            const bool bOk = Element == ElementI32 ? Read(Narrower) : ReadCounter32(Narrower);

            Out = Narrower;
            return bOk;
        }

        /** A double member, from f64, f32 or i32 - all of them exact in a double. */
        bool ReadAs(uint8 Element, double& Out)
        {
            if (Element == ElementF64)
            {
                return Read(Out);
            }

            if (Element == ElementF32)
            {
                float Single = 0.0f;
                const bool bOk = Read(Single);

                Out = Single;
                return bOk;
            }

            int32 Integer = 0;
            const bool bOk = Read(Integer);

            Out = Integer;
            return bOk;
        }

        /** An enum, which travels as a varint and has nothing to promote. */
        template <typename TEnum>
        bool ReadEnumAs(uint8 Element, TEnum& Out)
        {
            (void)Element;
            return ReadEnum(Out);
        }

    private:
        bool Fail(const FString& Why)
        {
            // The first failure is the informative one; everything after it is a
            // consequence of reading past the end.
            if (!bFailed)
            {
                bFailed = true;
                Error = Why;
            }

            return false;
        }

        bool Require(int32 Count)
        {
            if (bFailed)
            {
                return false;
            }

            if (Remaining() < Count)
            {
                return Fail(FString::Printf(
                    TEXT("table data ended after %d of %d bytes while %d more were expected"),
                    Position, Data.Num(), Count));
            }

            return true;
        }

        bool ReadFixed8(uint8& Out)
        {
            if (!Require(1))
            {
                return false;
            }

            Out = Data[Position++];
            return true;
        }

        bool ReadFixed32(uint32& Out)
        {
            if (!Require(4))
            {
                return false;
            }

            Out = static_cast<uint32>(Data[Position + 0])
                | static_cast<uint32>(Data[Position + 1]) << 8
                | static_cast<uint32>(Data[Position + 2]) << 16
                | static_cast<uint32>(Data[Position + 3]) << 24;

            Position += 4;
            return true;
        }

        bool ReadFixed64(uint64& Out)
        {
            if (!Require(8))
            {
                return false;
            }

            uint64 Value = 0;
            for (int32 Index = 0; Index < 8; ++Index)
            {
                Value |= static_cast<uint64>(Data[Position + Index]) << (8 * Index);
            }

            Out = Value;
            Position += 8;
            return true;
        }

        bool ReadVarint32(uint32& Out)
        {
            uint32 Value = 0;

            for (int32 Shift = 0; Shift < 35; Shift += 7)
            {
                uint8 Byte = 0;
                if (!ReadFixed8(Byte))
                {
                    return false;
                }

                Value |= static_cast<uint32>(Byte & 0x7F) << Shift;

                if ((Byte & 0x80) == 0)
                {
                    Out = Value;
                    return true;
                }
            }

            return Fail(TEXT("varint32 is longer than five bytes"));
        }

        TArrayView<const uint8> Data;
        int32 Position = 0;
        bool bFailed = false;
        FString Error;
    };

    /**
     * Reads and checks the file header, handing back the row count and the column
     * descriptors that follow it.
     *
     * The reserved byte is written as zero and is where compression or encryption
     * flags would go; a non-zero value means the file needs handling this build does
     * not have.
     *
     * The descriptors are checked against the file's own size before anybody allocates
     * for the row count: the blocks are all that follows the header, so their declared
     * lengths have to add up to the bytes left, and every row costs at least one byte in
     * every block. A row count larger than that is one the exporter could not have
     * written, and finding that out here rather than during the read is what keeps a
     * corrupt count from becoming an allocation of two billion rows.
     */
    inline bool ReadTableHeader(FSheetManBinaryReader& Reader, FSheetManTableHeader& OutHeader)
    {
        OutHeader.RowCount = 0;
        OutHeader.Columns.Empty();

        uint32 Version = 0;
        if (!Reader.Read(Version))
        {
            return false;
        }

        if (Version != BinaryFileFormatVersion)
        {
            return Reader.FailWith(FString::Printf(
                TEXT("table format version %u is not supported (expected %u)"),
                Version, BinaryFileFormatVersion));
        }

        bool bReserved = false;
        if (!Reader.Read(bReserved))
        {
            return false;
        }

        if (bReserved)
        {
            return Reader.FailWith(TEXT("table declares unsupported features"));
        }

        if (!Reader.ReadCounter32(OutHeader.RowCount))
        {
            return false;
        }

        if (OutHeader.RowCount < 0)
        {
            const int32 Bad = OutHeader.RowCount;

            OutHeader.RowCount = 0;
            return Reader.FailWith(
                FString::Printf(TEXT("table row count %d is negative"), Bad));
        }

        int32 ColumnCount = 0;
        if (!Reader.ReadCounter32(ColumnCount))
        {
            return false;
        }

        if (ColumnCount < 0)
        {
            return Reader.FailWith(
                FString::Printf(TEXT("table column count %d is negative"), ColumnCount));
        }

        // Bounded, because the count came out of the file: no file describes more columns
        // than it has bytes left, and a descriptor is several bytes each.
        OutHeader.Columns.Empty(ColumnCount < Reader.Remaining() ? ColumnCount : Reader.Remaining());

        for (int32 At = 0; At < ColumnCount && !Reader.HasFailed(); ++At)
        {
            FSheetManColumn Column;

            Reader.ReadCounter32(Column.Tag);

            uint8 Wire = 0;
            Reader.Read(Wire);
            Column.Element = static_cast<uint8>(Wire & 0x0F);
            Column.Kind = static_cast<uint8>((Wire >> 4) & 0x03);

            Reader.Read(Column.Encoding);

            Reader.ReadCounter32(Column.Count);

            uint32 ByteLength = 0;
            Reader.Read(ByteLength);
            Column.ByteLength = static_cast<int32>(ByteLength);

            OutHeader.Columns.Add(Column);
        }

        if (Reader.HasFailed())
        {
            return false;
        }

        const int32 Remaining = Reader.Remaining();
        int32 Declared = 0;

        for (const FSheetManColumn& Column : OutHeader.Columns)
        {
            if (Column.ByteLength < 0 || Column.ByteLength > Remaining - Declared)
            {
                return Reader.FailWith(FString::Printf(
                    TEXT("column tag %d declares %d bytes, which the file cannot hold"),
                    Column.Tag, Column.ByteLength));
            }

            Declared += Column.ByteLength;

            if (Column.Encoding == EncodingRaw && OutHeader.RowCount > Column.ByteLength)
            {
                const int32 Bad = OutHeader.RowCount;

                OutHeader.RowCount = 0;
                return Reader.FailWith(FString::Printf(
                    TEXT("the row count %d is larger than column tag %d can hold in its %d bytes"),
                    Bad, Column.Tag, Column.ByteLength));
            }
        }

        if (Declared != Remaining)
        {
            return Reader.FailWith(FString::Printf(
                TEXT("the columns declare %d bytes but %d follow the header"),
                Declared, Remaining));
        }

        return true;
    }

    /**
     * That a column is what the generated member expects, or a lossless promotion of it.
     *
     * Refusal names the field and both types, because a column whose type changed
     * incompatibly is a schema mistake to fix, not bytes to reinterpret.
     */
    inline bool CheckColumn(FSheetManBinaryReader& Reader, const FSheetManColumn& Column,
        const TCHAR* FieldName, uint8 Kind, int32 Count, uint32 Accepted)
    {
        if (Reader.HasFailed())
        {
            return false;
        }

        if (Column.Kind != Kind || (Kind != KindVarArray && Column.Count != Count))
        {
            return Reader.FailWith(FString::Printf(
                TEXT("%s: the file column (kind %d, count %d) does not match the generated ")
                TEXT("member (kind %d, count %d). The schema changed shape; regenerate the ")
                TEXT("code or rebuild the data."),
                FieldName, Column.Kind, Column.Count, Kind, Count));
        }

        // An encoding this build cannot decode is refused by name, exactly like an
        // element it cannot read. An unknown column's encoding never gets here - a skip
        // is a skip whatever the block's layout.
        if (Column.Encoding != EncodingRaw)
        {
            return Reader.FailWith(FString::Printf(
                TEXT("%s: the file's column uses encoding %d, which this reader does not ")
                TEXT("support. Regenerate the code or rebuild the data."),
                FieldName, Column.Encoding));
        }

        if ((Accepted & ElementMask(Column.Element)) != 0)
        {
            return true;
        }

        return Reader.FailWith(FString::Printf(
            TEXT("%s: the file carries element type %d, which this member cannot read. The ")
            TEXT("column changed type incompatibly; regenerate the code or rebuild the data."),
            FieldName, Column.Element));
    }

    /**
     * That a block was consumed exactly.
     *
     * A mismatch means the file and this code disagree about the encoding, and stopping
     * here names the column instead of reading the next one out of the wrong bytes.
     */
    inline bool CheckBlockEnd(FSheetManBinaryReader& Reader, const FSheetManColumn& Column,
        int32 ExpectedEnd)
    {
        if (Reader.HasFailed())
        {
            return false;
        }

        if (Reader.Tell() != ExpectedEnd)
        {
            return Reader.FailWith(FString::Printf(
                TEXT("column tag %d: its block declared %d bytes but the read ended %d bytes ")
                TEXT("short of its boundary"),
                Column.Tag, Column.ByteLength, ExpectedEnd - Reader.Tell()));
        }

        return true;
    }

    /**
     * How much to reserve up front for a row count that came off the wire.
     *
     * A corrupt count of two billion would otherwise be an immediate allocation of
     * that many rows, which fails long before the reader gets to notice the file is
     * short. The array grows past this if the rows really are there.
     */
    inline int32 ReserveBound(int32 Count)
    {
        constexpr int32 MaxUpFront = 65536;

        return FMath::Clamp(Count, 0, MaxUpFront);
    }
}
